#!groovy

def gitCommit = ""
def shortCommit = ""
def branchName = ""

def buildBranches = []

final ansiColorMapName = 'xterm'

node('digitalprint'){
  wrap([$class: 'AnsiColorBuildWrapper', colorMapName: ansiColorMapName]) {
    configFileProvider([configFile(fileId: 'slave_ssh_config', targetLocation: '.ssh/config')]) {
      wrap([$class: 'TimestamperBuildWrapper']) {

        def app
        stage('Checkout') {
          def scmVars = checkout scm
          branchName = scmVars.GIT_BRANCH
          gitCommit = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
          shortCommit = gitCommit.take(6)
          releaseVersion = sh(returnStdout: true, script: 'echo "${BRANCH_NAME#release/*}"').trim()
        }

        milestone()

        stage('Build image') {
          app = docker.build("dp-editor:${shortCommit}", "-f ./Dockerfile .")
        }

        milestone()

        stage('Test image') {
            app.inside {
                sh 'echo "Here should be some test!!!!"'
            }
        }

        milestone()
        try{
        stage('SonarQube Analysis') {
          def scannerHome = tool 'sonarqube';

          withSonarQubeEnv() {
            sh """
              ${scannerHome}/bin/sonar-scanner \

            """
          }
        }
        } catch (e) {
            res = "FAIL" // make sure other exceptions are recorded as failure too
         }


        if (branchName in buildBranches || branchName =~ /(release|hotfix)\/.*/) {

            milestone()
            stage('Push image') {
                docker.withRegistry('https://registry.dreamsoft.pro', 'registry-dreamsoft-credentials') {
                    app.push("${releaseVersion}")
                    app.push("latest")
                }
            }
        }
      }
    }
  }
}
