FROM ubuntu:jammy as build

WORKDIR /var/www/app/

COPY ./ /var/www/app/

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt-get install -y -o Dpkg::Options::="--force-confold" \
    ghostscript php-fpm libxml2-dev gettext-base supervisor php-mbstring php-xml php-bcmath php-soap php-mysql php-mongodb php-imagick php-curl php-gd php-zip composer unzip nginx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm ./.docker* \
    && composer install && composer dumpautoload -o && composer clear-cache

FROM ubuntu:jammy as final

ENV PHP_MAX_CHILDREN 5
ENV PHP_START_SERVERS 2
ENV PHP_MIN_SPARE 1
ENV PHP_MAX_SPARE 3
ENV PHP_ERROR_REPORTING "E_ALL"
ENV NGINX_REAL_IP 172.18.0.0/16
ARG DEBIAN_FRONTEND=noninteractive


WORKDIR /var/www/app/

COPY ./.docker_entrypoint /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh
COPY .docker_supervisor /etc/supervisor/conf.d/supervisor.conf
COPY .docker_nginx /etc/nginx/app.conf.tmp
COPY .docker_fpm /etc/php/8.1/fpm/pool.d/www.conf.tmp
COPY .docker_fpmconf /etc/php/8.1/fpm/php-fpm.conf
#COPY .docker_php-ini /etc/php/8.1/cli/php.ini
COPY --from=build /var/www/app/ /var/www/app/
COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN apt update \
    && apt-get install -y -o Dpkg::Options::="--force-confold" \
    ghostscript php-fpm php-xdebug libxml2 gettext-base supervisor php-mbstring php-xml php-bcmath php-soap php-mysql php-mongodb php-imagick php-curl php-gd php-zip unzip nginx\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -f /etc/nginx/sites-enabled/default \
    && rm -f /var/log/nginx/*.log \
    && ln -s /dev/stdout /var/log/nginx/access.log \
    && ln -s /dev/stderr /var/log/nginx/error.log

COPY ./.docker_imagick-policy /etc/ImageMagick-6/policy.xml

EXPOSE 80 443

ENTRYPOINT ["/usr/bin/entrypoint.sh"]

CMD ["/usr/bin/supervisord"]