# Generated by Django 5.2.10 on 2026-01-07 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0004_alter_widget_widget_type"),
        ("registry", "0003_shift"),
        ("telemetry", "0003_metricdefinition_alter_telemetrypoint_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("oee_gauge", "OEE Gauge"),
                    ("production_trend", "Production Trend"),
                    ("oee_trend", "OEE Trend Line"),
                    ("oee_bar", "OEE Components Bar"),
                    ("downtime_pareto", "Downtime Pareto"),
                    ("status_card", "Machine Status Card"),
                    ("machine_gantt", "Machine Status Gantt"),
                    ("reliability_card", "Reliability (MTBF/MTTR)"),
                    ("oee_heatmap", "OEE Heatmap (Lines vs Time)"),
                    ("alerts_list", "Recent Alerts List"),
                    ("multi_series_chart", "Multi-Series Chart (Custom)"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="WidgetSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Override metric name (optional)",
                        max_length=50,
                    ),
                ),
                (
                    "y_axis",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")],
                        default="left",
                        max_length=10,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "Line"),
                            ("bar", "Bar"),
                            ("scatter", "Scatter"),
                        ],
                        default="line",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color (e.g. #ff0000)", max_length=7
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.machine",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telemetry.metricdefinition",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="dashboards.widget",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
