# lang_th.py
# -*- coding: utf-8 -*-
"""
Thai (Thailand) translations — LTR.
"""

LANG = {
    "barcode_font_size_label": "ขนาดตัวอักษรของคำอธิบายบาร์โค้ด [pt]:",
    "__meta__": {
        "language_name_native": "ไทย (ประเทศไทย)",
        "language_name_en": "Thai (Thailand)",
        "locale": "th-TH",
        "direction": "ltr",
        "font_hint": "Noto Sans Thai, Noto Serif Thai"
    },

    # Application - General
    "app_title": "Billboard Splitter v1.8",
    "error": "ข้อผิดพลาด",
    "no_file": "ไม่มีไฟล์",
    "language": "ภาษา",
    "language_switch": "เปลี่ยนภาษา",
    "choose_language": "เลือกภาษา:",
    "apply_language": "นำไปใช้",
    "language_changed": "เปลี่ยนภาษาแล้ว การเปลี่ยนแปลงบางอย่างจะมีผลหลังจากรีสตาร์ทแอปฯ",

    # GUI Elements
    "tab_home": " หน้าแรก ",
    "tab_settings": " การตั้งค่า ",
    "tab_help": " วิธีใช้ ",
    "tab_license": " ใบอนุญาต ",

    "button_browse": "เลือกไฟล์…",
    "browse_folder": "เลือกโฟลเดอร์…",
    "button_save": "บันทึก",
    "button_delete": "ลบ",
    "button_close": "ปิด",
    "save_all_settings": "บันทึกการตั้งค่าทั้งหมด",

    "label_rows": "แบ่งแนวตั้ง (แถว):",
    "label_columns": "แบ่งแนวนอน (คอลัมน์):",
    "label_overlap": "ซ้อนทับ (ซม.):",
    "label_white_stripe": "แถบสีขาว (ซม.):",
    "label_add_white_stripe": "นับแถบสีขาวรวมในค่าซ้อนทับที่มีผล",
    "label_layout": "เลย์เอาต์:",
    "label_output_type": "ประเภทเอาต์พุต:",
    "label_enable_reg_marks": "เปิดใช้เครื่องหมายกำหนดตำแหน่ง:",
    "label_enable_codes": "เปิดใช้โค้ด:",
    "label_enable_sep_lines": "เปิดใช้เส้นแบ่ง (ระหว่างพาเนล)",
    "label_enable_start_line": "เปิดใช้เส้นบน/เริ่มต้นของแผ่น",
    "label_enable_end_line": "เปิดใช้เส้นล่าง/สิ้นสุดของแผ่น",
    "label_bryt_order": "ลำดับพาเนล:",
    "label_slice_rotation": "การหมุนพาเนล:",
    "label_create_order_folder": "สร้างโฟลเดอร์ตามหมายเลขคำสั่งซื้อ",

    "section_input_file": " ไฟล์นำเข้า ",
    "section_scale_and_dimensions": " มาตราส่วนและขนาดผลลัพธ์ ",
    "label_original_size": "ขนาดดั้งเดิม:",
    "label_scale_non_uniform": "ปรับขนาดไม่สมส่วน",
    "label_scale": "มาตราส่วน: 1:",
    "label_scale_x": "มาตราส่วน X: 1:",
    "label_scale_y": "มาตราส่วน Y: 1:",
    "label_output_dimensions": "ขนาดไฟล์ผลลัพธ์:",
    "label_width_cm": "ความกว้าง [ซม.]:",
    "label_height_cm": "ความสูง [ซม.]:",
    "section_split_settings": " การตั้งค่าการแบ่ง ",
    "section_profiles": " โปรไฟล์ ",
    "section_save_location": " ตำแหน่งบันทึก ",
    "section_input_preview": " พรีวิวไฟล์นำเข้า ",
    "section_output_preview": " พรีวิวผลลัพธ์ ",

    "layout_vertical": "แนวตั้ง",
    "layout_horizontal": "แนวนอน",
    "output_common_sheet": "แผ่นรวม",
    "output_separate_files": "ไฟล์แยก",
    "output_both": "แผ่นรวม & ไฟล์แยก",
    "output_common": "แผ่นรวม",
    "output_separate": "ไฟล์แยก",
    "reg_mark_cross": "กากบาท",
    "reg_mark_line": "เส้น",
    "code_qr": "คิวอาร์โค้ด",
    "code_barcode": "บาร์โค้ด",
    "bryt_order_1": "A1–An, B1–Bn … มาตรฐาน จากด้านบน",
    "bryt_order_2": "A1–An, Bn–B1 … ซิกแซก (ตามแถว) จากด้านบน",
    "bryt_order_3": "A1..B1, A2..B2 … ตามคอลัมน์ จากด้านบน",
    "bryt_order_4": "A1–A2..B2–B1 … ซิกแซก (ตามคอลัมน์) จากด้านบน",
    "bryt_order_5": "N1–Nn, (N-1)1–(N-1)n … มาตรฐาน จากด้านล่าง",
    "bryt_order_6": "N1–Nn, (N-1)n–(N-1)1 … ซิกแซก (ตามแถว) จากด้านล่าง",
    "logging_console": "คอนโซล",
    "logging_file": "ไฟล์",
    "logging_both": "ทั้งสองอย่าง",

    "section_processing_mode": " งานตัด ",
    "processing_mode_ram": "RAM (หน่วยความจำ)",
    "processing_mode_hdd": "HDD (ดิสก์)",
    "graphic_settings": "การตั้งค่ากราฟิก",
    "code_settings": "การตั้งค่า QR / บาร์โค้ด",
    "logging_settings": "การตั้งค่า log",
    "barcode_text_position_label": "ตำแหน่งข้อความใต้บาร์โค้ด:",
    "barcode_text_bottom": "ด้านล่าง",
    "barcode_text_side": "ด้านข้าง",
    "barcode_text_none": "ไม่มี",

    "extra_margin_label": "ระยะขอบรอบพาเนล (ซม.):",
    "margin_top_label": "ขอบบน (ซม.):",
    "margin_bottom_label": "ขอบล่าง (ซม.):",
    "margin_left_label": "ขอบซ้าย (ซม.):",
    "margin_right_label": "ขอบขวา (ซม.):",
    "reg_mark_width_label": "เครื่องหมายกำหนดตำแหน่ง — กว้าง (ซม.):",
    "reg_mark_height_label": "เครื่องหมายกำหนดตำแหน่ง — สูง (ซม.):",
    "reg_mark_white_line_width_label": "เครื่องหมายกำหนดตำแหน่ง — ความหนาเส้นสีขาว (ซม.):",
    "reg_mark_black_line_width_label": "เครื่องหมายกำหนดตำแหน่ง — ความหนาเส้นสีดำ (ซม.):",
    "sep_line_black_width_label": "เส้นแบ่ง — ความหนาเส้นสีดำ (ซม.):",
    "sep_line_white_width_label": "เส้นแบ่ง — ความหนาเส้นสีขาว (ซม.):",
    "slice_gap_label": "ช่องว่างระหว่างพาเนล (ซม.):",
    "label_draw_slice_border": "วาดกรอบพาเนล (เส้นตัด)",

    "scale_label": "สเกล (ซม.):",
    "scale_x_label": "กว้าง X (ซม.):",
    "scale_y_label": "สูง Y (ซม.):",
    "offset_x_label": "ออฟเซ็ต X (ซม.):",
    "offset_y_label": "ออฟเซ็ต Y (ซม.):",
    "rotation_label": "การหมุน (°):",
    "anchor_label": "จุดยึด:",

    "logging_mode_label": "โหมด log:",
    "log_file_label": "ไฟล์ log:",
    "logging_level_label": "ระดับ log:",

    "button_load": "โหลด",
    "button_save_settings": "บันทึกการตั้งค่าปัจจุบัน",
    "button_generate_pdf": "สร้าง PDF",
    "button_refresh_preview": "รีเฟรชพรีวิว",
    "button_refresh_layout": "รีเฟรชเลย์เอาต์",

    "hwid_frame_title": "ฮาร์ดแวร์ไอดี (HWID)",
    "copy_hwid": "คัดลอก HWID",
    "license_frame_title": "เปิดใช้งานใบอนุญาต",
    "enter_license_key": "กรอกคีย์ใบอนุญาต:",
    "activate": "เปิดใช้งาน",
    "status_trial": "โหมดทดลอง",
    "license_active": "ใบอนุญาตใช้งานอยู่",

    # User Messages
    "msg_no_profile_name": "ไม่มีชื่อ",
    "msg_enter_profile_name": "กรอกชื่อโปรไฟล์เพื่อบันทึก",
    "msg_profile_saved": "บันทึกโปรไฟล์แล้ว",
    "profile_saved_title": "บันทึกโปรไฟล์แล้ว",
    "msg_profile_saved_detail": "บันทึกโปรไฟล์ '{0}' แล้ว",
    "profile_saved": "บันทึกโปรไฟล์ '{profile}' แล้ว",
    "profile_saved_and_applied": "โปรไฟล์ '{profile}' ถูกบันทึกและนำไปใช้แล้ว",
    "msg_no_profile": "ไม่มีโปรไฟล์",
    "warning_no_profile": "ไม่มีโปรไฟล์",
    "msg_select_profile": "เลือกโปรไฟล์จากรายการเพื่อโหลด",
    "select_profile": "เลือกโปรไฟล์จากรายการเพื่อโหลด",
    "profile_loaded_title": "โหลดโปรไฟล์แล้ว",
    "profile_loaded": "โหลดโปรไฟล์ '{profile}' แล้ว",
    "warning_no_profile_delete": "ไม่มีโปรไฟล์",
    "warning_no_profile_delete_message": "เลือกโปรไฟล์จากรายการเพื่อลบ",
    "profile_not_found": "ไม่พบโปรไฟล์ '{profile}'",
    "profile_not_exist": "โปรไฟล์ '{profile}' ไม่มีอยู่",
    "confirm_delete_title": "ยืนยันการลบ",
    "confirm_delete_profile": "คุณแน่ใจหรือไม่ว่าจะลบโปรไฟล์ '{profile}'?",
    "profile_deleted_title": "ลบโปรไฟล์แล้ว",
    "profile_deleted": "ลบโปรไฟล์ '{profile}' แล้ว",

    "msg_no_input_file": "ไม่มีไฟล์นำเข้า",
    "msg_unsupported_format": "รูปแบบไม่รองรับ",
    "select_file_title": "เลือกไฟล์นำเข้า",
    "supported_files": "ไฟล์ที่รองรับ",
    "all_files": "ไฟล์ทั้งหมด",
    "select_dir_title": "เลือกโฟลเดอร์เอาต์พุต",
    "select_log_dir_title": "เลือกโฟลเดอร์ log",
    "error_output_dir_title": "ข้อผิดพลาดโฟลเดอร์เอาต์พุต",
    "error_output_dir": "โฟลเดอร์เอาต์พุตที่เลือกไม่ถูกต้องหรือไม่มีอยู่:\n{directory}",
    "error_input_file_title": "ข้อผิดพลาดไฟล์นำเข้า",
    "error_input_file": "ไฟล์นำเข้าที่เลือกไม่ถูกต้องหรือไม่มีอยู่:\n{file}",
    "save_file_error_title": "ข้อผิดพลาดการบันทึกไฟล์",
    "save_file_error": "ไม่สามารถบันทึกไฟล์ได้: {error}",

    "msg_pdf_processing_error": "ประมวลผลไฟล์ PDF ล้มเหลว",
    "msg_thumbnail_error": "เกิดข้อผิดพลาดในการโหลดภาพขนาดย่อ",
    "msg_no_pdf_output": "ยังไม่มีเอาต์พุต PDF",
    "no_pdf_pages": "ไฟล์ PDF ไม่มีหน้า",
    "unsupported_output": "ชนิดเอาต์พุตนี้ไม่รองรับพรีวิว",
    "pdf_generated_title": "สร้างเสร็จ",
    "pdf_generated": "สร้างไฟล์ PDF สำเร็จแล้วที่โฟลเดอร์:\n{directory}",
    "pdf_generation_error_title": "ข้อผิดพลาดการสร้าง",
    "pdf_generation_error": "เกิดข้อผิดพลาดระหว่างสร้าง PDF โปรดตรวจสอบ log",
    "critical_pdf_error_title": "ข้อผิดพลาดร้ายแรงในการสร้าง PDF",
    "critical_pdf_error": "เกิดข้อผิดพลาดร้ายแรงระหว่างสร้าง PDF:\n{error}\nโปรดตรวจสอบ log.",

    "settings_saved_title": "บันทึกการตั้งค่าแล้ว",
    "settings_saved": "บันทึกการตั้งค่าไปยังไฟล์:\n{filepath}",
    "settings_save_error_title": "ข้อผิดพลาดการบันทึกการตั้งค่า",
    "settings_save_error": "ไม่สามารถบันทึกการตั้งค่าได้: {error}",
    "conversion_error_title": "ข้อผิดพลาดการแปลงค่า",
    "conversion_error": "เกิดข้อผิดพลาดขณะแปลงค่าจาก GUI: {error}",
    "update_gui_error_title": "ข้อผิดพลาดการอัปเดตอินเทอร์เฟซ",
    "update_gui_error": "เกิดข้อผิดพลาดระหว่างอัปเดตอินเทอร์เฟซ: {error}",

    "hwid_copied_to_clipboard": "คัดลอก HWID ไปยังคลิปบอร์ดแล้ว",
    "computer_hwid": "HWID ของคอมพิวเตอร์",
    "public_key_load_error": "ข้อผิดพลาดในการโหลด public key: {error}",
    "invalid_license_format": "รูปแบบคีย์ใบอนุญาตไม่ถูกต้อง: {error}",
    "activation_success": "เปิดใช้งานใบอนุญาตสำเร็จ",
    "activation_error": "ข้อผิดพลาดในการเปิดใช้งานใบอนุญาต: {error}",
    "log_trial_mode_active": "เปิดใช้งานโหมดทดลองอยู่",
    "log_trial_mode_inactive": "ปิดใช้งานโหมดทดลอง",

    "init_error_title": "ข้อผิดพลาดการเริ่มต้น",
    "init_error": "เกิดข้อผิดพลาดในการสร้างไดเรกทอรี: {error}",
    "poppler_path_info": "ข้อมูลเส้นทาง Poppler",
    "ttkthemes_not_installed": "คำเตือน: ไม่ได้ติดตั้ง 'ttkthemes' จะใช้สไตล์มาตรฐานของ Tkinter",

    # Logs (English intentionally)
    "log_configured": "Logging configured: level={0}, mode={1}, file={2}",
    "log_no_handlers": "Warning: No logging handlers configured (mode: {0}).",
    "log_critical_error": "Critical logging configuration error: {0}",
    "log_basic_config": "Basic logging configuration used due to an error.",
    "log_dir_create_error": "Critical error: Cannot create logs directory {0}: {1}",

    "error_critical_init": "CRITICAL ERROR during initialization: {0}",
    "logger_init_error": "Directory initialization error: {error}",
    "directory_created": "Created directory: {0}",
    "directory_creation_error": "Failed to create directory {0}: {1}",
    "sample_file_copied": "Sample file copied to {0}",
    "sample_file_copy_error": "Error copying sample file: {0}",
    "log_created_output_dir": "Output directory created: {0}",
    "log_cannot_create_output_dir": "Cannot create output directory {0}: {1}",

    "log_graphic_settings_error": "Failed to load graphic settings during initialization: {0}",
    "log_loading_pdf": "Loading PDF file: {0}",
    "log_loading_bitmap": "Loading bitmap file: {0}",
    "log_invalid_dpi": "Invalid DPI read ({0}). Using default {1} DPI.",
    "log_image_dimensions": "Image dimensions: {0}x{1}px, Mode: {2}, DPI: {3:.1f} -> {4:.3f}x{5:.3f}pt",
    "log_image_processing_color": "Processing image with original color mode: {0}",
    "log_unusual_color_mode": "Unusual image color mode: '{0}'. ReportLab/Pillow may not handle it correctly.",
    "log_draw_image_error": "Error during ReportLab drawImage for mode {0}: {1}",
    "log_unsupported_format": "Unsupported input file format: {0}",
    "log_input_file_not_found": "Input file not found: {0}",
    "log_load_process_error": "Error while loading or processing file {0}: {1}",
    "log_input_file_not_exists": "Input file does not exist or path is empty: '{0}'",
    "log_cannot_load_or_empty_pdf": "Failed to load input file or PDF is empty/corrupted.",
    "log_pdf_dimensions_info": "  PDF dimensions: {0:.1f}mm x {1:.1f}mm",
    "log_invalid_pdf_dimensions": "Invalid PDF page dimensions: {0}x{1} pt.",

    "log_extra_margin": "Extra margin set to {0:.3f} pt",
    "log_invalid_rows_cols": "Invalid number of rows ({0}) or columns ({1}).",
    "error_invalid_rows_cols": "Rows and columns must be positive integers.",
    "log_invalid_overlap_white_stripe": "Invalid overlap ({0}) or white stripe ({1}) values. They must be numbers.",
    "error_invalid_overlap_white_stripe": "Overlap and white stripe must be numeric values (mm).",
    "log_stripe_usage": "Set use_white_stripe={0}, white_stripe={1:.3f} mm",
    "log_effective_overlap": "Base overlap (graphics): {0:.3f} mm, White stripe: {1:.3f} mm, Effective overlap: {2:.3f} mm",
    "log_computed_dimensions": "Computed dimensions: PDF: {0:.3f}mm x {1:.3f}mm. Panel: {2:.3f}pt ({3:.3f}mm) x {4:.3f}pt ({5:.3f}mm). Core: {6:.3f}pt x {7:.3f}pt. Effective overlap: {8:.3f}mm",
    "log_invalid_dimensions": "Computed panel ({0:.3f}x{1:.3f}) or core ({2:.3f}x{3:.3f}) dimensions are invalid for overlap={4}, stripe={5}, r={6}, c={7}, W={8}mm, H={9}mm",
    "error_invalid_slice_dimensions": "Computed panel/core dimensions are invalid or negative.",

    "log_generating_slice_info": "Generating panel info: {0}",
    "log_no_slices_info_generated": "Failed to generate panels info.",
    "log_applying_rotated_order": "Applying order for 180-degree rotation: {0}",
    "log_applying_standard_order": "Applying order for 0-degree rotation (standard): {0}",
    "log_unknown_bryt_order": "Unknown panels order: '{0}'. Using default.",
    "log_final_slices_order": "  Final panels order ({0}): [{1}]",

    "log_invalid_dimensions_overlay": "Attempt to create an overlay with invalid dimensions: {0}. Skipping.",
    "log_empty_overlay": "Created an empty or nearly empty overlay PDF. Skipping.",
    "log_overlay_error": "Overlay PDF creation error: {0}",
    "log_merge_error": "Attempt to merge overlay without pages. Skipping.",
    "log_merge_page_error": "Error while merging overlay PDF: {0}",
    "log_fallback_draw_rotating_elements": "Could not get rows/cols for _draw_rotating_elements, used 1x1.",
    "log_overlay_created_for_slice": "Created stripes/marks overlay for panel {0}",
    "log_overlay_creation_failed_for_slice": "Failed to create stripes/marks overlay for {0}",
    "log_merging_rotated_overlay": "Merging ROTATED stripes/marks overlay for {0} with T={1}",
    "log_merging_nonrotated_overlay": "Merging NON-rotated stripes/marks overlay for {0}",
    "log_merging_all_codes_overlay": "Merging overlay of all codes (without rotation)",
    "log_merging_separation_lines_overlay": "Merging overlay of separation lines (without rotation)",
    "log_merging_code_overlay_for_slice": "Code overlay for {0} merged without rotation.",
    "log_merging_separation_overlay_for_slice": "Separation lines overlay for {0} merged without rotation.",

    "log_drawing_top_stripe": "[Canvas Draw] Drawing top stripe for {0}: x={1:.3f}, y={2:.3f}, w={3:.3f}, h={4:.3f}",
    "log_drawing_right_stripe": "[Canvas Draw] Drawing right stripe for {0}: x={1:.3f}, y={2:.3f}, w={3:.3f}, h={4:.3f}",
    "log_drawing_corner_stripe": "[Canvas Draw] Filling and stroking corner for {0} @ ({1:.3f}, {2:.3f})",
    "log_drawing_registration_mark": "Drawing centered cross at ({0:.3f}, {1:.3f})",
    "log_drawing_reg_lines_for_slice": "Drawing registration lines for {0} in area from ({1:.3f},{2:.3f})",
    "log_drawing_right_vertical_line": "  Drawing right vertical line: x={0:.3f}, y={1:.3f} -> {2:.3f}",
    "log_drawing_top_horizontal_line": "  Drawing top horizontal line: y={0:.3f}, x={1:.3f} -> {2:.3f}",
    "log_drawing_separation_line": "Drawing separation line (white on black): ({0}) @ ({1:.3f}, {2:.3f}), len={3:.3f}",
    "log_drawing_reg_marks_for_slice": "Drawing crosses for {0} [{1},{2}] / [{3},{4}] in area from ({5:.1f},{6:.1f})",
    "log_coord_calculation": "  Calculated centers: TL({0:.1f},{1:.1f}), TR({2:.1f},{3:.1f}), BL({4:.1f},{5:.1f}), BR({6:.1f},{7:.1f})",
    "log_drawing_tl": "    Drawing TL @ ({0:.1f}, {1:.1f})",
    "log_drawing_tr": "    Drawing TR @ ({0:.1f}, {1:.1f})",
    "log_drawing_bl": "    Drawing BL @ ({0:.1f}, {1:.1f})",
    "log_drawing_br": "    Drawing BR @ ({0:.1f}, {1:.1f})",
    "log_omitting_mark": "    Omitted {0} according to rule for position [{1},{2}]",
    "log_trial_common_sheet": "Applying TRIAL watermark text on common sheet",
    "log_trial_watermark_added": "TRIAL watermark has been added",
    "error_drawing_trial_text": "Error while drawing watermark: {error}",

    "log_drawing_separation_lines_for_page": "Drawing separation lines for page (layout={0}, total_slices={1}, slice_index={2})",
    "log_vertical_line_between_slices": "  Vertical line between panels {0}-{1} @ x={2:.1f}",
    "log_vertical_line_start": "  Vertical line start @ x={0:.1f}",
    "log_vertical_line_end": "  Vertical line end @ x={0:.1f}",
    "log_horizontal_line_between_slices": "  Horizontal line between panels {0}-{1} @ y={2:.1f}",
    "log_horizontal_line_start": "  Horizontal line start @ y={0:.1f}",
    "log_horizontal_line_end": "  Horizontal line end @ y={0:.1f}",
    "log_sep_line_start_separate": "  (Separate_files) Vertical/Horizontal line start @ {0:.1f}",
    "log_sep_line_end_separate": "  (Separate_files) Vertical/Horizontal line end @ {0:.1f}",

    "log_generate_barcode_data": "Generating barcode data: {0}",
    "log_barcode_data_shortened": "Barcode data shortened to {0} characters.",
    "log_barcode_data_error": "Barcode data generation error: {0}",
    "log_compose_barcode_payload": "Composing barcode payload ({0}): {1}",
    "log_barcode_payload_shortened": "Payload shortened to {0} characters for format {1}",
    "log_barcode_payload_error": "Error while composing payload: {0}",
    "log_unknown_anchor_fallback": "Unknown anchor '{0}', using bottom-left",
    "log_used_default_code_settings": "Used 'default' settings for code {0}/{1}.",
    "log_no_layout_key_fallback": "No layout '{0}' for {1}/{2}. Used the first available: '{3}'.",
    "log_code_settings_error": "Not found or error while retrieving code settings ({0}/{1}/{2}): {3}. Using defaults.",
    "log_drawing_barcode": "Drawing {0} at ({1:.3f}, {2:.3f}) [base ({3:.3f}, {4:.3f}) + offset ({5:.3f}, {6:.3f})], rotation: {7}°",
    "error_generate_qr_svg": "Failed to generate QR code SVG.",
    "error_invalid_scale_for_qr": "Invalid scale for QR: {0}mm",
    "error_invalid_qr_scale_factor": "Invalid scale factor for QR: {0}",
    "error_generate_barcode_svg": "Failed to generate barcode SVG.",
    "error_invalid_scale_for_barcode": "Invalid scale for Barcode: {0}x{1}mm",
    "error_invalid_barcode_scale_factor": "Invalid scale factor for Barcode: ({0:.4f}, {1:.4f})",
    "log_barcode_scale_qr": "  {0}: scale config={1:.3f}mm, SVG width={2:.3f}pt, sf={3:.4f}",
    "log_barcode_scale_code128": "  {0}: scale config=({1:.3f}mm, {2:.3f}mm), SVG size=({3:.3f}pt, {4:.3f}pt), sf=({5:.4f}, {6:.4f})",
    "log_barcode_drawing_error": "Error while drawing code '{0}': {1}",
    "log_prepared_barcode_info": "Prepared code info for {0} ({1}, anchor={2}): base absolute position ({3:.1f}, {4:.1f})",
    "log_barcode_info_prep_error": "Error preparing code data for {0}: {1}",
    "log_drawing_barcodes_count": "Drawing {0} barcodes/QR codes...",
    "log_missing_barcode_info_key": "Missing key in barcode info while drawing: {0}. Info: {1}",
    "log_error_drawing_barcode_in_draw_all": "Error while drawing code '{0}' in _draw_all_barcodes: {1}",

    "log_start_splitting_process": "--- Starting split process for: {0} ---",
    "log_split_settings": "  Settings: {0}x{1} panels, Overlap={2}mm, White stripe={3}mm (+overlap: {4})",
    "log_output_dir_info": "  Output: {0} / {1} to '{2}'",
    "log_lines_marks_barcodes_info": "  Lines: Separation={0}, Start={1}, End={2} | Marks: {3} ({4}), Codes: {5} ({6})",
    "log_bryt_order_info": "  Order: {0}, Panels rotation: {1}°",
    "log_invalid_dimensions_in_slice_info": "Invalid dimensions in slice_info for {0}: {1}x{2}",
    "log_content_transform": "Content transformation T_content for {0}: {1}",
    "log_merged_content_for_slice": "Merged content for panel {0} on new_page",
    "log_slice_reader_created": "Created complete slice (PdfReader) for panel {0}",
    "log_slice_reader_creation_error": "Error creating complete slice for panel {0}: {1}",
    "log_used_get_transform": "Used _get_transform (translation only): x={0:.1f}, y={1:.1f}",
    "log_start_split_separate_files": "--- Starting: SEPARATE FILES (Rotation handled in create_slice_reader) ---",
    "log_creating_file_for_slice": "Creating file for panel {0}: {1}",
    "log_invalid_page_size_for_slice": "Invalid page size ({0}x{1}) for {2}. Skipping.",
    "log_blank_page_creation_error": "Error creating page for {0} (size {1}x{2}): {3}. Skipping.",
    "log_transform_for_slice": "Transform T (translation only) for {0}: {1}",
    "log_merging_complete_slice": "Merging complete panel {0} with transform: {1}",
    "log_skipped_slice_merging": "Skipped merging complete panel for {0}.",
    "log_file_saved": "File saved: {0}",
    "log_file_save_error": "File save error {0}: {1}",
    "log_finished_split_separate_files": "--- Finished: SEPARATE FILES (Saved {0}/{1}) ---",
    "log_no_slices_split_horizontal": "No panels to process in split_horizontal.",
    "log_start_split_horizontal": "--- Starting: COMMON SHEET - HORIZONTAL (Rotation handled in create_slice_reader) ---",
    "log_page_dimensions": "Page dimensions: {0:.1f}mm x {1:.1f}mm ({2} panels)",
    "log_page_creation_error": "Error creating result page ({0}x{1}): {2}. Aborting.",
    "log_slice_at_position": "Panel {0} [{1}/{2}] @ ({3:.1f}, {4:.1f})",
    "log_transform_t_only": "Transform T (translation only) for {0}: {1}",
    "log_merging_complete_bryt": "Merging complete panel {0} with transform: {1}",
    "log_skipped_merging_bryt": "Skipped merging complete panel for {0}.",
    "log_file_result_saved": "Result file saved: {0}",
    "log_file_result_save_error": "Result file save error {0}: {1}",
    "log_finished_split_horizontal": "--- Finished: COMMON SHEET - HORIZONTAL ---",
    "log_no_slices_split_vertical": "No panels to process in split_vertical.",
    "log_start_split_vertical": "--- Starting: COMMON SHEET - VERTICAL (Rotation handled in create_slice_reader) ---",
    "log_finished_split_vertical": "--- Finished: COMMON SHEET - VERTICAL ---",
    "log_unknown_layout": "Unknown layout for common sheet: '{0}'.",
    "log_unknown_output_type": "Unknown output type: '{0}'.",
    "log_finished_splitting_success": "--- Finished split process for: {0} - SUCCESS ---",
    "log_finished_splitting_errors": "--- Finished split process for: {0} - ERRORS OCCURRED ---",
    "log_value_error_in_splitting": "Input data or calculation error: {0}",
    "log_finished_splitting_critical_error": "--- Finished split process for: {0} - CRITICAL ERROR ---",
    "log_unexpected_error_in_splitting": "Unexpected error while splitting file {0}: {1}",

    "log_script_mode_test": "splitter.py launched as main script (test mode).",
    "log_loaded_config": "Configuration loaded.",
    "log_error_loading_config": "Failed to load configuration: {0}",
    "log_created_example_pdf": "Created sample PDF file: {0}",
    "log_cannot_create_example_pdf": "Failed to create sample PDF: {0}",
    "log_start_test_split": "Starting test split of file: {0} to {1}",
    "log_test_split_success": "Test split completed successfully.",
    "log_test_split_errors": "Test split finished with errors.",

    "log_qr_empty_data": "Attempt to generate QR code for empty data.",
    "log_qr_generated": "QR code SVG generated for: {0}...",
    "log_qr_error": "QR code generation error for data '{0}': {1}",
    "log_barcode_empty_data": "Attempt to generate barcode for empty data.",
    "log_barcode_generated": "Barcode SVG generated for: {0}...",
    "log_barcode_error": "Barcode generation error for data '{0}': {1}",
    "log_basic_handler_configured": "Basic handler configured for logger in barcode_qr.py",
    "log_basic_handler_error": "Failed to configure basic logger handler in barcode_qr: {0}",

    "loading_profiles_from": "Loading profiles from",
    "profiles_file": "Profiles file",
    "does_not_contain_dict": "does not contain a dictionary. Creating a new one",
    "not_found_creating_new": "not found. Creating a new empty one",
    "json_profiles_read_error": "Error reading JSON profiles file",
    "file_will_be_overwritten": "File will be overwritten on save",
    "json_decode_error_in_profiles": "JSON decode error in profiles file",
    "cannot_load_profiles_file": "Cannot load profiles file",
    "unexpected_profiles_read_error": "Unexpected error reading profiles",
    "saving_profiles_to": "Saving profiles to",
    "cannot_save_profiles_file": "Cannot save profiles file",
    "profiles_save_error": "Error saving profiles to file",
    "logger_profile_saved": "Profile saved: {profile}",
    "logger_profile_not_found": "Profile not found to load: {profile}",
    "logger_profile_loaded": "Profile loaded: {profile}",
    "logger_profile_delete_not_exist": "Attempt to delete non-existent profile: {profile}",
    "logger_profile_deleted": "Profile deleted: {profile}",
    "logger_start_save_settings": "Started saving settings from GUI.",
    "logger_invalid_value": "Invalid value for '{key}'. Set to 0.0.",
    "logger_end_save_settings": "Finished saving settings from GUI.",
    "logger_conversion_error": "Value conversion error from GUI: {error}",
    "conversion_failed": "Conversion of GUI values failed",
    "logger_unexpected_save_error": "Unexpected error saving settings: {error}",
    "logger_settings_saved": "Settings saved to file: {file}",

    "public_key_load_error_log": "Public key loading error",
    "license_key_decode_error": "License key decoding error",
    "license_activation_error": "License activation error",

    "ui_created": "User interface has been created.",
    "error_tab_home": "Error creating 'Home' tab UI",
    "error_tab_settings": "Error creating 'Settings' tab UI",
    "error_tab_help": "Error creating 'Help' tab UI",
    "error_creating_license_ui": "Error creating 'License' tab UI",
    "error_loading_ui": "Error loading interface: {error}",
    "error_creating_home_ui": "Error creating 'Home' tab UI",
    "error_creating_settings_ui": "Error creating 'Settings' tab UI",
    "error_creating_help_ui": "Error creating 'Help' tab UI",
    "logger_update_gui": "Started updating GUI from configuration.",
    "logger_end_update_gui": "Finished updating GUI from configuration.",
    "logger_update_gui_error": "Unexpected error while updating GUI: {error}",
    "logger_invalid_output_dir": "Invalid or non-existent output directory: {directory}",
    "logger_invalid_input_file": "Invalid or non-existent input file: {file}",
    "logger_start_pdf": "Started PDF generation process.",
    "logger_pdf_save_error": "PDF generation aborted - failed to save current settings.",
    "logger_pdf_success": "PDF generation completed successfully.",
    "logger_pdf_exception": "Exception during main PDF generation process.",
    "icon_set_error": "Failed to set application icon: {error}",
    "accent_button_style_error": "Failed to set style for accent button: {error}",
    "logger_file_save_error": "File save error {file}: {error}",

    "thumbnail_error_log": "Thumbnail generation error",
    "output_preview_update_called": "Output preview update called",
    "output_preview_canvas_missing": "Output preview canvas missing",
    "pdf_found_in_output_dir": "PDF found in output directory",
    "preparing_thumbnail": "Preparing thumbnail",
    "thumbnail_generated_successfully": "Thumbnail generated successfully",
    "thumbnail_generation_error": "Thumbnail generation error for",
    "no_pdf_for_common_sheet": "No PDF file for common sheet preview",
    "no_pdf_for_separate_files": "No generated separate PDF files for preview",
    "cannot_load_thumbnail": "Cannot load thumbnail from",

    "missing_gui_var_created": "Created missing GUI variable for key: {key}",
    "missing_gui_structure_created": "Created missing GUI structure for: {code_type}/{output_type}/{layout}",
    "missing_gui_var_detailed_created": "Created missing GUI variable for: {code_type}/{output_type}/{layout}/{param}",

    "help_text": """
Billboard Splitter — คู่มือผู้ใช้

วัตถุประสงค์:
แอปฯ แบ่งแบบดีไซน์บิลบอร์ดเป็นพาเนลพร้อมพิมพ์โดยอัตโนมัติ
โปรแกรมสมมติสเกล 1:10 ให้กรอกค่าซ้อนทับ/แถบสีขาวตามสเกล 1:1

ประเภทเอาต์พุต:
• แผ่นรวม: พาเนลทั้งหมดอยู่ใน PDF เดียว
• ไฟล์แยก: แต่ละพาเนลเป็น PDF แยก

ความสามารถเพิ่มเติม:
• เลย์เอาต์แนวตั้ง/แนวนอน
• หมุนพาเนล 180°
• เครื่องหมายกำหนดตำแหน่ง (กากบาท/เส้น)
• เพิ่มคิวอาร์/บาร์โค้ด (ปรับสเกล/ออฟเซ็ต/ตำแหน่งได้)
• บันทึก/โหลด/ลบการตั้งค่าเป็นโปรไฟล์

ขั้นตอนพื้นฐาน:
1) ที่ 'หน้าแรก' เลือกไฟล์ PDF/JPG/TIFF
2) ตั้งค่าแถว/คอลัมน์ ซ้อนทับ และแถบสีขาว
3) เลือกเลย์เอาต์ (ตั้ง/นอน) และเอาต์พุต (รวม/แยก)
4) เปิดใช้เครื่องหมาย/โค้ด และปรับละเอียดที่ 'การตั้งค่า'
5) (ไม่บังคับ) บันทึกโปรไฟล์ แล้วกด 'สร้าง PDF'

การแก้ไขปัญหา:
• ตรวจสอบ log ในโฟลเดอร์ 'logs'
• ตรวจสอบความถูกต้องของเส้นทาง/โฟลเดอร์
• ฝ่ายสนับสนุน: tech@printworks.pl (จ.–ศ. 8–16)
"""
}
