# lang_nl.py
"""
Taaldocument: Nederlands (nl).
Conventie: de domeinterm "bryt" wordt vertaald als "paneel".
"""

LANG = {
    "barcode_font_size_label": "Lettergrootte van barcodebeschrijving [pt]:",
    # ========================== 
    #  Applicatie - Algemeen
    # ========================== 
    "app_title": "Billboard Splitter v1.8",
    "error": "Fout",
    "no_file": "Geen bestand",
    "language": "Taal",
    "language_switch": "Taal wisselen",
    "choose_language": "Kies taal:",
    "apply_language": "Toepassen",
    "language_changed": "De taal is gewijzigd. Sommige wijzigingen worden zichtbaar na het opnieuw opstarten van de applicatie.",

    # ======================================== 
    #  Gebruikersinterface (GUI) Elementen
    # ======================================== 

    # --- Hoofdtabbladen ---
    "tab_home": " Start ",
    "tab_settings": " Instellingen ",
    "tab_help": " Help ",
    "tab_license": " Licentie ",

    # --- Algemene Knoppen ---
    "button_browse": "Bladeren...",
    "browse_folder": "Map bladeren...",
    "button_save": "Opslaan",
    "button_delete": "Verwijderen",
    "button_close": "Sluiten",
    "save_all_settings": "Alle instellingen opslaan",

    # --- Veldlabels (Starttabblad) ---
    "label_rows": "Verticale splitsing (rijen):",
    "label_columns": "Horizontale splitsing (kolommen):",
    "label_overlap": "Overlap [mm]:",
    "label_white_stripe": "Witte strook [mm]:",
    "label_add_white_stripe": "Witte strook toevoegen aan effectieve overlap",
    "label_layout": "Uitvoer lay-out:",
    "label_output_type": "Uitvoertype:",
    "label_enable_reg_marks": "Registratiemarkeringen inschakelen:",
    "label_enable_codes": "Codes inschakelen:",
    "label_enable_sep_lines": "Scheidingslijnen inschakelen (tussen panelen)",
    "label_enable_start_line": "Start/bovenlijn van vel inschakelen",
    "label_enable_end_line": "Eind/onderlijn van vel inschakelen",
    "label_bryt_order": "Paneelvolgorde:",
    "label_slice_rotation": "Paneelrotatie:",
    "label_create_order_folder": "Map met ordernummer aanmaken",

    # --- Secties/Frames (Starttabblad) ---
    "section_input_file": " Invoerbestand ",
    "section_scale_and_dimensions": " Schaal en uitvoerafmetingen ",
    "label_original_size": "Oorspronkelijke grootte:",
    "label_scale_non_uniform": "Niet-uniform schalen",
    "label_scale": "Schaal: 1:",
    "label_scale_x": "Schaal X: 1:",
    "label_scale_y": "Schaal Y: 1:",
    "label_output_dimensions": "Afmetingen uitvoerbestand:",
    "label_width_cm": "Breedte [cm]:",
    "label_height_cm": "Hoogte [cm]:",
    "section_split_settings": " Splitsingsinstellingen ",
    "section_profiles": " Instellingenprofielen ",
    "section_save_location": " Opslaglocatie ",
    "section_input_preview": " Voorbeeld invoerbestand ",
    "section_output_preview": " Voorbeeld uitvoerbestand ",

    # --- Optiewaarden (Combobox, Radiobutton etc.) ---
    "layout_vertical": "Verticaal",
    "layout_horizontal": "Horizontaal",
    "output_common_sheet": "Gezamenlijk vel",
    "output_separate_files": "Afzonderlijke bestanden",
    "output_both": "Gezamenlijk vel en afzonderlijke bestanden",
    "output_common": "Gezamenlijk vel",
    "output_separate": "Afzonderlijke bestanden",
    "reg_mark_cross": "Kruis",
    "reg_mark_line": "Lijn",
    "code_qr": "QR-code",
    "code_barcode": "Streepjescode",
    "bryt_order_1": "A1-An, B1-Bn, .. Standaard, van boven",
    "bryt_order_2": "A1-An, Bn-B1, .. Slang per rij, van boven",
    "bryt_order_3": "A1..B1, A2..B2, .. Per kolom, van boven",
    "bryt_order_4": "A1-A2..B2-B1.. Slang per kolom, van boven",
    "bryt_order_5": "N1-Nn, (N-1)1-(N-1)n, .. Standaard, van onderen",
    "bryt_order_6": "N1-Nn, (N-1)n-(N-1)1, .. Slang per rij, van onderen",
    "logging_console": "console",
    "logging_file": "bestand",
    "logging_both": "beide",

    # --- Secties/Frames (Instellingentabblad) ---
    "section_processing_mode": " Snijbewerkingen ",
    "processing_mode_ram": "RAM (in geheugen)",
    "processing_mode_hdd": "HDD (op schijf)",
    "graphic_settings": "Grafische instellingen",
    "code_settings": "QR / Streepjescode-instellingen",
    "logging_settings": "Logboekinstellingen",
    "barcode_text_position_label": "Positie streepjescodetekst:",
    "barcode_text_bottom": "onder",
    "barcode_text_side": "naast",
    "barcode_text_none": "geen",

    # --- Veldlabels (Instellingentabblad - Grafisch) ---
    "extra_margin_label": "Marge rond panelen [mm]:",
    "margin_top_label": "Bovenmarge [mm]:",
    "margin_bottom_label": "Ondermarge [mm]:",
    "margin_left_label": "Linkermarge [mm]:",
    "margin_right_label": "Rechtermarge [mm]:",
    "reg_mark_width_label": "Registratiemerk - Breedte [mm]:",
    "reg_mark_height_label": "Registratiemerk - Hoogte [mm]:",
    "reg_mark_white_line_width_label": "Registratiemerk - Dikte witte lijn [mm]:",
    "reg_mark_black_line_width_label": "Registratiemerk - Dikte zwarte lijn [mm]:",
    "sep_line_black_width_label": "Scheidingslijn - Dikte zwarte lijn [mm]:",
    "sep_line_white_width_label": "Scheidingslijn - Dikte witte lijn [mm]:",
    "slice_gap_label": "Ruimte tussen panelen [mm]:",
    "label_draw_slice_border": "Rand rond paneel tekenen (snijlijn)",

    # --- Veldlabels (Instellingentabblad - Codes) ---
    "scale_label": "Grootte [mm]:",
    "scale_x_label": "Breedte X [mm]:",
    "scale_y_label": "Hoogte Y [mm]:",
    "offset_x_label": "Offset X [mm]:",
    "offset_y_label": "Offset Y [mm]:",
    "rotation_label": "Rotatie (°):",
    "anchor_label": "Hoek:",

    # --- Veldlabels (Instellingentabblad - Logboek) ---
    "logging_mode_label": "Logboekmodus:",
    "log_file_label": "Logbestand:",
    "logging_level_label": "Logboekniveau:",

    # --- Knoppen / Acties (Starttabblad) ---
    "button_load": "Laden",
    "button_save_settings": "Huidige instellingen opslaan",
    "button_generate_pdf": "Genereer PDF",
    "button_refresh_preview": "Voorbeeld vernieuwen",
    "button_refresh_layout": "Lay-out vernieuwen",

    # --- Licentie (GUI) ---
    "hwid_frame_title": "Unieke hardware-identificatie (HWID)",
    "copy_hwid": "Kopieer HWID",
    "license_frame_title": "Licentieactivering",
    "enter_license_key": "Voer de licentiesleutel in:",
    "activate": "Activeren",
    "status_trial": "Proefmodus",
    "license_active": "Licentie actief",

    # ================================================ 
    #  Gebruikersberichten (Vensters, Statusbalk)
    # ================================================ 

    # --- Profielen ---
    "msg_no_profile_name": "Geen naam",
    "msg_enter_profile_name": "Voer een profielnaam in om op te slaan.",
    "msg_profile_saved": "Profiel opgeslagen",
    "profile_saved_title": "Profiel opgeslagen",
    "msg_profile_saved_detail": "Profiel '{0}' is opgeslagen.",
    "profile_saved": "Profile '{profile}' has been saved.",
    "profile_saved_and_applied": "Profiel '{profile}' is opgeslagen en toegepast.",
    "msg_no_profile": "Geen profiel",
    "warning_no_profile": "Geen profiel",
    "msg_select_profile": "Selecteer een profielnaam uit de lijst om te laden.",
    "select_profile": "Selecteer een profielnaam uit de lijst om te laden.",
    "profile_loaded_title": "Profiel geladen",
    "profile_loaded": "Profiel '{profile}' is geladen.",
    "warning_no_profile_delete": "Geen profiel",
    "warning_no_profile_delete_message": "Selecteer een profiel uit de lijst om te verwijderen.",
    "profile_not_found": "Profiel '{profile}' niet gevonden.",
    "profile_not_exist": "Profiel '{profile}' bestaat niet.",
    "confirm_delete_title": "Verwijdering bevestigen",
    "confirm_delete_profile": "Weet u zeker dat u profiel '{profile}' wilt verwijderen?",
    "profile_deleted_title": "Profiel verwijderd",
    "profile_deleted": "Profiel '{profile}' is verwijderd.",

    # --- Bestanden / Mappen ---
    "msg_no_input_file": "Geen invoerbestand",
    "msg_unsupported_format": "Niet-ondersteund formaat",
    "select_file_title": "Selecteer invoerbestand",
    "supported_files": "Ondersteunde bestanden",
    "all_files": "Alle bestanden",
    "select_dir_title": "Selecteer uitvoermap",
    "select_log_dir_title": "Selecteer map voor logbestanden",
    "error_output_dir_title": "Fout in uitvoermap",
    "error_output_dir": "De opgegeven uitvoermap is ongeldig of bestaat niet:\n{directory}",
    "error_input_file_title": "Fout in invoerbestand",
    "error_input_file": "Het opgegeven invoerbestand is ongeldig of bestaat niet:\n{file}",
    "save_file_error_title": "Fout bij opslaan van bestand",
    "save_file_error": "Kon bestand niet opslaan: {error}",

    # --- PDF-verwerking / Voorbeeld ---
    "msg_pdf_processing_error": "Kon PDF-bestand niet verwerken",
    "msg_thumbnail_error": "Fout bij laden van miniatuur",
    "msg_no_pdf_output": "Geen PDF-uitvoer",
    "no_pdf_pages": "Geen pagina's in PDF-bestand",
    "unsupported_output": "Niet-ondersteund uitvoertype voor voorbeeld",
    "pdf_generated_title": "Generatie voltooid",
    "pdf_generated": "PDF-bestand(en) zijn succesvol gegenereerd in de map:\n{directory}",
    "pdf_generation_error_title": "Generatiefout",
    "pdf_generation_error": "Er zijn fouten opgetreden bij het genereren van de PDF. Controleer de logboeken voor meer informatie.",
    "critical_pdf_error_title": "Kritieke PDF-generatiefout",
    "critical_pdf_error": "Er is een kritieke fout opgetreden bij het genereren van de PDF:\n{error}\nControleer de logboeken.",

    # --- Instellingen ---
    "settings_saved_title": "Instellingen opgeslagen",
    "settings_saved": "Instellingen zijn opgeslagen in het bestand:\n{filepath}",
    "settings_save_error_title": "Fout bij opslaan van instellingen",
    "settings_save_error": "Kon instellingen niet opslaan: {error}",
    "conversion_error_title": "Conversiefout",
    "conversion_error": "Fout bij het converteren van waarden uit de GUI: {error}",
    "update_gui_error_title": "GUI-updatefout",
    "update_gui_error": "Er is een fout opgetreden bij het bijwerken van de interface: {error}",

    # --- Licentie ---
    "hwid_copied_to_clipboard": "HWID is naar het klembord gekopieerd",
    "computer_hwid": "Computer HWID",
    "public_key_load_error": "Fout bij laden van openbare sleutel: {error}",
    "invalid_license_format": "Ongeldig licentiesleutelformaat: {error}",
    "activation_success": "Licentie is succesvol geactiveerd.",
    "activation_error": "Licentieactivering mislukt: {error}",
    "log_trial_mode_active": "Proefmodus is actief",
    "log_trial_mode_inactive": "Proefmodus is inactief",

    # --- Initialisatie ---
    "init_error_title": "Initialisatiefout",
    "init_error": "Fout bij het initialiseren van mappen: {error}",
    "poppler_path_info": "Poppler-padinformatie",
    "ttkthemes_not_installed": "Waarschuwing: De ttkthemes-bibliotheek is niet geïnstalleerd. De standaard Tkinter-stijl wordt gebruikt.",

    # ===================================== 
    #  Logboeken (Loggerberichten)
    # ===================================== 

    # --- Algemene Logging / Configuratie ---
    "log_configured": "Logboek geconfigureerd: niveau={0}, modus={1}, bestand={2}",
    "log_no_handlers": "Waarschuwing: Geen logboekhandlers geconfigureerd (modus: {0}).",
    "log_critical_error": "Kritieke logboekconfiguratiefout: {0}",
    "log_basic_config": "Basis logboekconfiguratie gebruikt vanwege een fout.",
    "log_dir_create_error": "Kritieke fout: Kan logboekmap {0} niet aanmaken: {1}",

    # --- Logboeken - Initialisatie / Mappen (`init_directories.py`) ---
    "error_critical_init": "KRITIEKE FOUT tijdens initialisatie: {0}",
    "logger_init_error": "Fout bij initialisatie van mappen: {error}",
    "directory_created": "Map aangemaakt: {0}",
    "directory_creation_error": "Kon map {0} niet aanmaken: {1}",
    "sample_file_copied": "Voorbeeldbestand gekopieerd naar {0}",
    "sample_file_copy_error": "Fout bij kopiëren van voorbeeldbestand: {0}",
    "log_created_output_dir": "Uitvoermap aangemaakt: {0}",
    "log_cannot_create_output_dir": "Kan uitvoermap {0} niet aanmaken: {1}",

    # --- Logboeken - Splitter (`splitter.py`) ---
    #   Splitter - Initialisatie en Laden
    "log_graphic_settings_error": "Kon grafische instellingen niet laden tijdens initialisatie: {0}",
    "log_loading_pdf": "PDF-bestand laden: {0}",
    "log_loading_bitmap": "Bitmap-bestand laden: {0}",
    "log_invalid_dpi": "Ongeldige DPI gelezen ({0}). Standaard {1} DPI wordt gebruikt.",
    "log_image_dimensions": "Afbeeldingsafmetingen: {0}x{1}px, Modus: {2}, DPI: {3:.1f} -> {4:.3f}x{5:.3f}pt",
    "log_image_processing_color": "Afbeelding verwerken met originele kleurmodus: {0}",
    "log_unusual_color_mode": "Ongebruikelijke afbeeldingskleurmodus: '{0}'. ReportLab/Pillow kan dit mogelijk niet correct verwerken.",
    "log_draw_image_error": "Fout tijdens ReportLab drawImage voor modus {0}: {1}",
    "log_unsupported_format": "Niet-ondersteund invoerbestandsformaat: {0}",
    "log_input_file_not_found": "Invoerbestand niet gevonden: {0}",
    "log_load_process_error": "Fout bij het laden of verwerken van bestand {0}: {1}",
    "log_input_file_not_exists": "Invoerbestand bestaat niet of pad is leeg: '{0}'",
    "log_cannot_load_or_empty_pdf": "Kon invoerbestand niet laden of PDF is leeg/beschadigd.",
    "log_pdf_dimensions_info": "  PDF-afmetingen: {0:.1f}mm x {1:.1f}mm",
    "log_invalid_pdf_dimensions": "Ongeldige PDF-pagina-afmetingen: {0}x{1} pt.",

    #   Splitter - Dimensieberekeningen
    "log_extra_margin": "Extra marge ingesteld op {0:.3f} pt",
    "log_invalid_rows_cols": "Ongeldig aantal rijen ({0}) of kolommen ({1}).",
    "error_invalid_rows_cols": "Rijen en kolommen moeten positieve gehele getallen zijn.",
    "log_invalid_overlap_white_stripe": "Ongeldige waarden voor overlap ({0}) of witte strook ({1}). Moeten getallen zijn.",
    "error_invalid_overlap_white_stripe": "Overlap en witte strook moeten numerieke waarden zijn (mm).",
    "log_stripe_usage": "use_white_stripe={0} ingesteld, white_stripe={1:.3f} mm",
    "log_effective_overlap": "Basisoverlap (grafisch): {0:.3f} mm, Witte strook: {1:.3f} mm, Effectieve overlap: {2:.3f} mm",
    "log_computed_dimensions": "Berekende afmetingen: PDF: {0:.3f}mm x {1:.3f}mm. Paneel: {2:.3f}pt ({3:.3f}mm) x {4:.3f}pt ({5:.3f}mm). Kern: {6:.3f}pt x {7:.3f}pt. Effectieve overlap: {8:.3f}mm",
    "log_invalid_dimensions": "Berekende paneel- ({0:.3f}x{1:.3f}) of kernafmetingen ({2:.3f}x{3:.3f}) zijn ongeldig voor overlap={4}, strook={5}, r={6}, k={7}, B={8}mm, H={9}mm",
    "error_invalid_slice_dimensions": "Berekende paneel/kern-afmetingen zijn ongeldig of negatief.",

    #   Splitter - Genereren van Paneelinformatie en Volgorde
    "log_generating_slice_info": "Paneelinformatie genereren: {0}",
    "log_no_slices_info_generated": "Kon paneelinformatie niet genereren.",
    "log_applying_rotated_order": "Volgorde toepassen voor 180-graden rotatie: {0}",
    "log_applying_standard_order": "Volgorde toepassen voor 0-graden rotatie (standaard): {0}",
    "log_unknown_bryt_order": "Onbekende paneelvolgorde: '{0}'. Standaard wordt gebruikt.",
    "log_final_slices_order": "  Definitieve paneelvolgorde ({0}): [{1}]",

    #   Splitter - Maken van Overlays en Samenvoegen
    "log_invalid_dimensions_overlay": "Poging om een overlay te maken met ongeldige afmetingen: {0}. Overgeslagen.",
    "log_empty_overlay": "Lege of bijna lege overlay-PDF gemaakt. Samenvoegen overgeslagen.",
    "log_overlay_error": "Fout bij maken van overlay-PDF: {0}",
    "log_merge_error": "Poging om overlay zonder pagina's samen te voegen. Overgeslagen.",
    "log_merge_page_error": "Fout bij het samenvoegen van overlay-PDF: {0}",
    "log_fallback_draw_rotating_elements": "Kon geen rijen/kolommen krijgen voor _draw_rotating_elements, 1x1 gebruikt.",
    "log_overlay_created_for_slice": "Stroken/markeringen-overlay gemaakt voor paneel {0}",
    "log_overlay_creation_failed_for_slice": "Kon stroken/markeringen-overlay niet maken voor {0}",
    "log_merging_rotated_overlay": "GEROTEERDE stroken/markeringen-overlay samenvoegen voor {0} met T={1}",
    "log_merging_nonrotated_overlay": "NIET-GEROTEERDE stroken/markeringen-overlay samenvoegen voor {0}",
    "log_merging_all_codes_overlay": "Overlay van alle codes samenvoegen (zonder rotatie)",
    "log_merging_separation_lines_overlay": "Overlay van scheidingslijnen samenvoegen (zonder rotatie)",
    "log_merging_code_overlay_for_slice": "Code-overlay voor {0} samengevoegd zonder rotatie.",
    "log_merging_separation_overlay_for_slice": "Scheidingslijnen-overlay voor {0} samengevoegd zonder rotatie.",

    #   Splitter - Tekenen van Grafische Elementen (Stroken, Markeringen, Lijnen)
    "log_drawing_top_stripe": "[Canvas Draw] Bovenste strook tekenen voor {0}: x={1:.3f}, y={2:.3f}, w={3:.3f}, h={4:.3f}",
    "log_drawing_right_stripe": "[Canvas Draw] Rechter strook tekenen voor {0}: x={1:.3f}, y={2:.3f}, w={3:.3f}, h={4:.3f}",
    "log_drawing_corner_stripe": "[Canvas Draw] Hoek vullen en omlijnen voor {0} @ ({1:.3f}, {2:.3f})",
    "log_drawing_registration_mark": "Gecentreerd kruis tekenen op ({0:.3f}, {1:.3f})",
    "log_drawing_reg_lines_for_slice": "Registratielijnen tekenen voor {0} in gebied vanaf ({1:.3f},{2:.3f})",
    "log_drawing_right_vertical_line": "  Rechter verticale lijn tekenen: x={0:.3f}, y={1:.3f} -> {2:.3f}",
    "log_drawing_top_horizontal_line": "  Bovenste horizontale lijn tekenen: y={0:.3f}, x={1:.3f} -> {2:.3f}",
    "log_drawing_separation_line": "Scheidingslijn tekenen (wit op zwart): ({0}) @ ({1:.3f}, {2:.3f}), len={3:.3f}",
    "log_drawing_reg_marks_for_slice": "Kruisen tekenen voor {0} [{1},{2}] / [{3},{4}] in gebied vanaf ({5:.1f},{6:.1f})",
    "log_coord_calculation": "  Berekende centra: TL({0:.1f},{1:.1f}), TR({2:.1f},{3:.1f}), BL({4:.1f},{5:.1f}), BR({6:.1f},{7:.1f})",
    "log_drawing_tl": "    TL tekenen @ ({0:.1f}, {1:.1f})",
    "log_drawing_tr": "    TR tekenen @ ({0:.1f}, {1:.1f})",
    "log_drawing_bl": "    BL tekenen @ ({0:.1f}, {1:.1f})",
    "log_drawing_br": "    BR tekenen @ ({0:.1f}, {1:.1f})",
    "log_omitting_mark": "    {0} weggelaten volgens regel voor positie [{1},{2}]",
    "log_trial_common_sheet": "TRIAL-watermerktekst toepassen op gezamenlijk vel",

    # Watermerk
    "log_trial_watermark_added": "TRIAL-watermerk is toegevoegd",
    "error_drawing_trial_text": "Fout bij het tekenen van watermerk: {error}",

    #   Splitter - Tekenen van Scheidingslijnen (Hele Pagina)
    "log_drawing_separation_lines_for_page": "Scheidingslijnen tekenen voor pagina (layout={0}, total_slices={1}, slice_index={2})",
    "log_vertical_line_between_slices": "  Verticale lijn tussen panelen {0}-{1} @ x={2:.1f}",
    "log_vertical_line_start": "  Verticale lijn start @ x={0:.1f}",
    "log_vertical_line_end": "  Verticale lijn eind @ x={0:.1f}",
    "log_horizontal_line_between_slices": "  Horizontale lijn tussen panelen {0}-{1} @ y={2:.1f}",
    "log_horizontal_line_start": "  Horizontale lijn start @ y={0:.1f}",
    "log_horizontal_line_end": "  Horizontale lijn eind @ y={0:.1f}",
    "log_sep_line_start_separate": "  (Separate_files) Verticale/Horizontale lijn start @ {0:.1f}",
    "log_sep_line_end_separate": "  (Separate_files) Verticale/Horizontale lijn eind @ {0:.1f}",

    #   Splitter - Genereren van Streepjescodes / QR
    "log_generate_barcode_data": "Streepjescodegegevens genereren: {0}",
    "log_barcode_data_shortened": "Streepjescodegegevens ingekort tot {0} tekens.",
    "log_barcode_data_error": "Fout bij genereren van streepjescodegegevens: {0}",
    "log_compose_barcode_payload": "Streepjescode-payload samenstellen ({0}): {1}",
    "log_barcode_payload_shortened": "Payload ingekort tot {0} tekens voor formaat {1}",
    "log_barcode_payload_error": "Fout bij het samenstellen van payload: {0}",
    "log_unknown_anchor_fallback": "Onbekend anker '{0}', linksonder wordt gebruikt",
    "log_used_default_code_settings": "'default'-instellingen gebruikt voor code {0}/{1}.",
    "log_no_layout_key_fallback": "Geen lay-out '{0}' voor {1}/{2}. Eerste beschikbare gebruikt: '{3}'.",
    "log_code_settings_error": "Niet gevonden of fout bij ophalen van code-instellingen ({0}/{1}/{2}): {3}. Standaardwaarden worden gebruikt.",
    "log_drawing_barcode": "{0} tekenen op ({1:.3f}, {2:.3f}) [basis ({3:.3f}, {4:.3f}) + offset ({5:.3f}, {6:.3f})], rotatie: {7}°",
    "error_generate_qr_svg": "Kon QR-code SVG niet genereren.",
    "error_invalid_scale_for_qr": "Ongeldige schaal voor QR: {0}mm",
    "error_invalid_qr_scale_factor": "Ongeldige schaalfactor voor QR: {0}",
    "error_generate_barcode_svg": "Kon streepjescode SVG niet genereren.",
    "error_invalid_scale_for_barcode": "Ongeldige schaal voor Streepjescode: {0}x{1}mm",
    "error_invalid_barcode_scale_factor": "Ongeldige schaalfactor voor Streepjescode: ({0:.4f}, {1:.4f})",
    "log_barcode_scale_qr": "  {0}: schaal config={1:.3f}mm, SVG breedte={2:.3f}pt, sf={3:.4f}",
    "log_barcode_scale_code128": "  {0}: schaal config=({1:.3f}mm, {2:.3f}mm), SVG grootte=({3:.3f}pt, {4:.3f}pt), sf=({5:.4f}, {6:.4f})",
    "log_barcode_drawing_error": "Fout bij het tekenen van code '{0}': {1}",
    "log_prepared_barcode_info": "Code-info voorbereid voor {0} ({1}, anker={2}): basis absolute positie ({3:.1f}, {4:.1f})",
    "log_barcode_info_prep_error": "Fout bij voorbereiden van codegegevens voor {0}: {1}",
    "log_drawing_barcodes_count": "{0} streepjescodes/QR-codes tekenen...",
    "log_missing_barcode_info_key": "Sleutel ontbreekt in code-info tijdens tekenen: {0}. Info: {1}",
    "log_error_drawing_barcode_in_draw_all": "Fout bij het tekenen van code '{0}' in _draw_all_barcodes: {1}",

    #   Splitter - Splitsingsproces (split_* methoden)
    "log_start_splitting_process": "--- Splitsingsproces starten voor: {0} ---",
    "log_split_settings": "  Instellingen: {0}x{1} panelen, Overlap={2}mm, Witte strook={3}mm (+overlap: {4})",
    "log_output_dir_info": "  Uitvoer: {0} / {1} naar '{2}'",
    "log_lines_marks_barcodes_info": "  Lijnen: Scheiding={0}, Start={1}, Eind={2} | Markeringen: {3} ({4}), Codes: {5} ({6})",
    "log_bryt_order_info": "  Volgorde: {0}, Paneelrotatie: {1}°",
    "log_invalid_dimensions_in_slice_info": "Ongeldige afmetingen in slice_info voor {0}: {1}x{2}",
    "log_content_transform": "Inhoudstransformatie T_content voor {0}: {1}",
    "log_merged_content_for_slice": "Inhoud samengevoegd voor paneel {0} op new_page",
    "log_slice_reader_created": "Volledige slice (PdfReader) gemaakt voor paneel {0}",
    "log_slice_reader_creation_error": "Fout bij maken van volledige slice voor paneel {0}: {1}",
    "log_used_get_transform": "_get_transform gebruikt (alleen translatie): x={0:.1f}, y={1:.1f}",
    "log_start_split_separate_files": "--- Starten: AFZONDERLIJKE BESTANDEN (Rotatie afgehandeld in create_slice_reader) ---",
    "log_creating_file_for_slice": "Bestand maken voor paneel {0}: {1}",
    "log_invalid_page_size_for_slice": "Ongeldige paginagrootte ({0}x{1}) voor {2}. Overgeslagen.",
    "log_blank_page_creation_error": "Fout bij maken van pagina voor {0} (grootte {1}x{2}): {3}. Overgeslagen.",
    "log_transform_for_slice": "Transformatie T (alleen translatie) voor {0}: {1}",
    "log_merging_complete_slice": "Volledig paneel {0} samenvoegen met transformatie: {1}",
    "log_skipped_slice_merging": "Samenvoegen van volledig paneel voor {0} overgeslagen.",
    "log_file_saved": "Bestand opgeslagen: {0}",
    "log_file_save_error": "Fout bij opslaan van bestand {0}: {1}",
    "log_finished_split_separate_files": "--- Voltooid: AFZONDERLIJKE BESTANDEN (Opgeslagen {0}/{1}) ---",
    "log_no_slices_split_horizontal": "Geen panelen te verwerken in split_horizontal.",
    "log_start_split_horizontal": "--- Starten: GEZAMENLIJK VEL - HORIZONTAAL (Rotatie afgehandeld in create_slice_reader) ---",
    "log_page_dimensions": "Paginadimensions: {0:.1f}mm x {1:.1f}mm ({2} panelen)",
    "log_page_creation_error": "Fout bij maken van resultaatpagina ({0}x{1}): {2}. Afgebroken.",
    "log_slice_at_position": "Paneel {0} [{1}/{2}] @ ({3:.1f}, {4:.1f})",
    "log_transform_t_only": "Transformatie T (alleen translatie) voor {0}: {1}",
    "log_merging_complete_bryt": "Volledig paneel {0} samenvoegen met transformatie: {1}",
    "log_skipped_merging_bryt": "Samenvoegen van volledig paneel voor {0} overgeslagen.",
    "log_file_result_saved": "Resultaatbestand opgeslagen: {0}",
    "log_file_result_save_error": "Fout bij opslaan van resultaatbestand {0}: {1}",
    "log_finished_split_horizontal": "--- Voltooid: GEZAMENLIJK VEL - HORIZONTAAL ---",
    "log_no_slices_split_vertical": "Geen panelen te verwerken in split_vertical.",
    "log_start_split_vertical": "--- Starten: GEZAMENLIJK VEL - VERTICAAL (Rotatie afgehandeld in create_slice_reader) ---",
    "log_finished_split_vertical": "--- Voltooid: GEZAMENLIJK VEL - VERTICAAL ---",
    "log_unknown_layout": "Onbekende lay-out voor gezamenlijk vel: '{0}'.",
    "log_unknown_output_type": "Onbekend uitvoertype: '{0}'.",
    "log_finished_splitting_success": "--- Splitsingsproces voltooid voor: {0} - SUCCES ---",
    "log_finished_splitting_errors": "--- Splitsingsproces voltooid voor: {0} - FOUTEN OPGETREDEN ---",
    "log_value_error_in_splitting": "Invoergegevens- of berekeningsfout: {0}",
    "log_finished_splitting_critical_error": "--- Splitsingsproces voltooid voor: {0} - KRITIEKE FOUT ---",
    "log_unexpected_error_in_splitting": "Onverwachte fout bij het splitsen van bestand {0}: {1}",

    #   Splitter - Testmodus (__main__)
    "log_script_mode_test": "splitter.py gestart als hoofdscript (testmodus).",
    "log_loaded_config": "Configuratie geladen.",
    "log_error_loading_config": "Kon configuratie niet laden: {0}",
    "log_created_example_pdf": "Voorbeeld-PDF-bestand gemaakt: {0}",
    "log_cannot_create_example_pdf": "Kon voorbeeld-PDF niet maken: {0}",
    "log_start_test_split": "Testsplitsing van bestand starten: {0} naar {1}",
    "log_test_split_success": "Testsplitsing succesvol voltooid.",
    "log_test_split_errors": "Testsplitsing voltooid met fouten.",

    # --- Logboeken - QR/Streepjescode (`barcode_qr.py`) ---
    "log_qr_empty_data": "Poging om QR-code te genereren voor lege gegevens.",
    "log_qr_generated": "QR-code SVG gegenereerd voor: {0}...",
    "log_qr_error": "Fout bij genereren van QR-code voor gegevens '{0}': {1}",
    "log_barcode_empty_data": "Poging om streepjescode te genereren voor lege gegevens.",
    "log_barcode_generated": "Streepjescode SVG gegenereerd voor: {0}...",
    "log_barcode_error": "Fout bij genereren van streepjescode voor gegevens '{0}': {1}",
    "log_basic_handler_configured": "Basishandler geconfigureerd voor logger in barcode_qr.py",
    "log_basic_handler_error": "Kon basishandler voor logger niet configureren in barcode_qr: {0}",

    # --- Logboeken - Config/Profielen (`main_config_manager.py`) ---
    "loading_profiles_from": "Profielen laden van",
    "profiles_file": "Profielbestand",
    "does_not_contain_dict": "bevat geen woordenboek. Een nieuwe wordt aangemaakt",
    "not_found_creating_new": "niet gevonden. Een nieuwe lege wordt aangemaakt",
    "json_profiles_read_error": "Fout bij lezen van JSON-profielbestand",
    "file_will_be_overwritten": "Bestand wordt overschreven bij opslaan",
    "json_decode_error_in_profiles": "JSON-decodeerfout in profielbestand",
    "cannot_load_profiles_file": "Kan profielbestand niet laden",
    "unexpected_profiles_read_error": "Onverwachte fout bij lezen van profielen",
    "saving_profiles_to": "Profielen opslaan naar",
    "cannot_save_profiles_file": "Kan profielbestand niet opslaan",
    "profiles_save_error": "Fout bij opslaan van profielen naar bestand",
    "logger_profile_saved": "Profiel opgeslagen: {profile}",
    "logger_profile_not_found": "Profiel niet gevonden om te laden: {profile}",
    "logger_profile_loaded": "Profiel geladen: {profile}",
    "logger_profile_delete_not_exist": "Poging om niet-bestaand profiel te verwijderen: {profile}",
    "logger_profile_deleted": "Profiel verwijderd: {profile}",
    "logger_start_save_settings": "Instellingen opslaan vanuit GUI gestart.",
    "logger_invalid_value": "Ongeldige waarde voor '{key}'. Ingesteld op 0.0.",
    "logger_end_save_settings": "Instellingen opslaan vanuit GUI voltooid.",
    "logger_conversion_error": "Waardeconversiefout vanuit GUI: {error}",
    "conversion_failed": "Conversie van GUI-waarden mislukt",
    "logger_unexpected_save_error": "Onverwachte fout bij opslaan van instellingen: {error}",
    "logger_settings_saved": "Instellingen opgeslagen in bestand: {file}",

    # --- Logboeken - Licenties (`main_license.py`) ---
    "public_key_load_error_log": "Fout bij laden van openbare sleutel",
    "license_key_decode_error": "Fout bij decoderen van licentiesleutel",
    "license_activation_error": "Licentieactiveringsfout",

    # --- Logboeken - Hoofdmodule (`main.py`) ---
    "ui_created": "Gebruikersinterface is gemaakt.",
    "error_tab_home": "Fout bij maken van 'Start'-tabblad UI",
    "error_tab_settings": "Fout bij maken van 'Instellingen'-tabblad UI",
    "error_tab_help": "Fout bij maken van 'Help'-tabblad UI",
    "error_creating_license_ui": "Fout bij maken van 'Licentie'-tabblad UI",
    "error_loading_ui": "Fout bij laden van interface: {error}",
    "error_creating_home_ui": "Fout bij maken van 'Start'-tabblad UI",
    "error_creating_settings_ui": "Fout bij maken van 'Instellingen'-tabblad UI",
    "error_creating_help_ui": "Fout bij maken van 'Help'-tabblad UI",
    "logger_update_gui": "GUI bijwerken vanuit configuratie gestart.",
    "logger_end_update_gui": "GUI bijwerken vanuit configuratie voltooid.",
    "logger_update_gui_error": "Onverwachte fout bij het bijwerken van de GUI: {error}",
    "logger_invalid_output_dir": "Ongeldige of niet-bestaande uitvoermap: {directory}",
    "logger_invalid_input_file": "Ongeldig of niet-bestaand invoerbestand: {file}",
    "logger_start_pdf": "PDF-generatieproces gestart.",
    "logger_pdf_save_error": "PDF-generatie afgebroken - kon huidige instellingen niet opslaan.",
    "logger_pdf_success": "PDF-generatie succesvol voltooid.",
    "logger_pdf_exception": "Uitzondering tijdens hoofd-PDF-generatieproces.",
    "icon_set_error": "Kon applicatiepictogram niet instellen: {error}",
    "accent_button_style_error": "Kon stijl voor accentknop niet instellen: {error}",
    "logger_file_save_error": "Fout bij opslaan van bestand {file}: {error}",

    #   Logboeken - Voorbeeld (`main.py` - update_preview, update_output_preview)
    "thumbnail_error_log": "Fout bij genereren van miniatuur",
    "output_preview_update_called": "Uitvoervoorbeeld-update aangeroepen",
    "output_preview_canvas_missing": "Uitvoervoorbeeld-canvas ontbreekt",
    "pdf_found_in_output_dir": "PDF gevonden in uitvoermap",
    "preparing_thumbnail": "Miniatuur voorbereiden",
    "thumbnail_generated_successfully": "Miniatuur succesvol gegenereerd",
    "thumbnail_generation_error": "Fout bij genereren van miniatuur voor",
    "no_pdf_for_common_sheet": "Geen PDF-bestand voor voorbeeld van gezamenlijk vel",
    "no_pdf_for_separate_files": "Geen gegenereerde afzonderlijke PDF-bestanden voor voorbeeld",
    "cannot_load_thumbnail": "Kan miniatuur niet laden van",

    #   Logboeken - Ontwikkelaar / GUI-intern (`main.py`)
    "missing_gui_var_created": "Ontbrekende GUI-variabele gemaakt voor sleutel: {key}",
    "missing_gui_structure_created": "Ontbrekende GUI-structuur gemaakt voor: {code_type}/{output_type}/{layout}",
    "missing_gui_var_detailed_created": "Ontbrekende GUI-variabele gemaakt voor: {code_type}/{output_type}/{layout}/{param}",

    # Extra sleutels voor main_ui_help.py
    "help_text": "\n    Billboard Splitter – Gebruikershandleiding\n\n\n    Doel van het programma:\n\n    Billboard Splitter wordt gebruikt om billboardprojecten automatisch in printklare panelen te snijden.\n    Het programma is voorbereid om te werken met bestanden die op schaal 1:10 zijn ontworpen.\n\n    Waarden in de secties: Overlap, Witte strook, Instellingen worden ingevoerd op schaal 1:1.\n    Het programma maakt het mogelijk om de gesneden panelen op PDF-vellen te rangschikken, afhankelijk van de gekozen lay-out:\n\n    • Gezamenlijk vel: Alle panelen worden op één document geplaatst.\n\n    • Afzonderlijke bestanden: Elk paneel wordt opgeslagen in een afzonderlijk PDF-bestand.\n\n\n    Daarnaast maakt het programma het mogelijk om:\n\n    • Een lay-out te kiezen – verticaal of horizontaal (dienovereenkomstig: in de verticale lay-out verschijnen scheidingslijnen aan de boven- en onderkant,\n      en in de horizontale lay-out aan de linker- en rechterkant).\n\n    • Panelen 180° te draaien (het hele project omdraaien).\n\n    • Registratiemarkeringen toe te voegen (bijv. kruisjes of lijnen) om nauwkeurige positionering tijdens het lijmen te vergemakkelijken.\n\n    • QR-codes of streepjescodes toe te voegen – gegenereerd op basis van invoergegevens om te helpen\n      bij het identificeren van individuele panelen.\n\n    • Instellingen op te slaan als profielen die kunnen worden geladen, gewijzigd en verwijderd, waardoor het gemakkelijk is om\n      te schakelen tussen verschillende projectconfiguraties.\n\n\n    Belangrijkste stappen om het programma te gebruiken:\n\n\n    1. Kies invoerbestand:\n\n    • Kies in het tabblad 'Start' een PDF-, JPG- of TIFF-bestand met het billboardontwerp.\n\n    • Als u geen eigen pad instelt, stelt het programma standaard een voorbeeldbestand in.\n\n\n    2. Snij-instellingen:\n\n    • Geef het aantal rijen en kolommen op waarin het project wordt verdeeld.\n\n    • Stel de overlapgrootte in.\n\n    • Geef optioneel de breedte van de witte strook op die aan de effectieve overlap wordt toegevoegd.\n\n\n    3. Selecteer uitvoerlay-out:\n\n    • Verticaal: Alle panelen worden verticaal op een PDF-vel gerangschikt.\n\n    • Horizontaal: Alle panelen worden horizontaal op een PDF-vel gerangschikt.\n\n\n    4. Selecteer uitvoertype:\n\n    • Gezamenlijk vel: Alle panelen worden op één gezamenlijk PDF-vel gerangschikt.\n\n    • Afzonderlijke bestanden: Elk paneel wordt opgeslagen in een afzonderlijk PDF-bestand.\n\n    • In het tabblad 'Start' kunt u registratiemarkeringen in- en configureren – kies tussen kruis en lijn.\n\n    • Schakel optioneel een QR-code of streepjescode in die wordt gegenereerd op basis van projectgegevens.\n\n    • Codeparameters (schalen, offset, rotatie, positie) kunnen fijn worden afgesteld in het tabblad 'Instellingen'.\n\n\n    5. Instellingen beheren:\n\n    • In het tabblad 'Instellingen' kunt u grafische parameters (marges, lijndiktes, tussenruimtes) en\n      code-instellingen nauwkeurig wijzigen.\n\n    • Sla de huidige instellingen op als een profiel zodat u ze later gemakkelijk kunt laden of wijzigen.\n\n    • Instellingenprofielen (opgeslagen in het bestand profiles.json) maken het mogelijk om snel te schakelen tussen verschillende\n\n      projectconfiguraties.\n\n\n    6. PDF genereren:\n\n    • Nadat alle parameters zijn geconfigureerd, klikt u op 'Genereer PDF'.\n\n    • Resultaatbestanden worden opgeslagen in de map 'output' of een andere aangegeven map, en logboeken (met dagelijkse rotatie) in de map 'logs'\n      of een andere aangegeven map.\n\n\n    Bij problemen:\n\n    • Controleer de logboeken in de map 'logs'. Elke dag wordt een apart logbestand met de datum in de naam gegenereerd.\n\n    • Zorg ervoor dat alle vereiste mappen zijn ingesteld.\n\n    • Technische ondersteuning: tech@printworks.pl (werkdagen, 8-16)\n\n    "
}