# lang_sv.py
"""
Språkfil: Svenska (sv).
Konvention: domäntermen "bryt" översätts till "panel".
"""

LANG = {
    "barcode_font_size_label": "Teckenstorlek för streckkodsbeskrivning [pt]:",
    # ==========================
    #  Applikation - Allmänt
    # ==========================
    "app_title": "Billboard Splitter v1.8",
    "error": "Fel",
    "no_file": "Ingen fil",
    "language": "Språk",
    "language_switch": "Språkbyte",
    "choose_language": "Välj språk:",
    "apply_language": "Verkställ",
    "language_changed": "Språket har ändrats. Vissa ändringar kommer att synas efter omstart av programmet.",

    # ========================================
    #  Användargränssnitt (GUI) Element
    # ========================================

    # --- Huvudflikar ---
    "tab_home": " Hem ",
    "tab_settings": " Inställningar ",
    "tab_help": " Hjälp ",
    "tab_license": " Licens ",

    # --- Allmänna Knappar ---
    "button_browse": "Bläddra...",
    "browse_folder": "Bläddra mapp...",
    "button_save": "Spara",
    "button_delete": "Ta bort",
    "button_close": "Stäng",
    "save_all_settings": "Spara alla inställningar",

    # --- Fältetiketter (Hem-fliken) ---
    "label_rows": "Vertikal delning (rader):",
    "label_columns": "Horisontell delning (kolumner):",
    "label_overlap": "Överlappning [mm]:",
    "label_white_stripe": "Vit rand [mm]:",
    "label_add_white_stripe": "Lägg till vit rand till effektiv överlappning",
    "label_layout": "Utdata layout:",
    "label_output_type": "Utdata typ:",
    "label_enable_reg_marks": "Aktivera registreringsmärken:",
    "label_enable_codes": "Aktivera koder:",
    "label_enable_sep_lines": "Aktivera separationslinjer (mellan paneler)",
    "label_enable_start_line": "Aktivera start/topplinje på arket",
    "label_enable_end_line": "Aktivera slut/bottenlinje på arket",
    "label_bryt_order": "Panelordning:",
    "label_slice_rotation": "Panelrotation:",
    "label_create_order_folder": "Skapa mapp med ordernummer",

    # --- Sektioner/Ramar (Hem-fliken) ---
    "section_input_file": " Indatafil ",
    "section_scale_and_dimensions": " Skala och utdatamått ",
    "label_original_size": "Ursprunglig storlek:",
    "label_scale_non_uniform": "Skala oproportionerligt",
    "label_scale": "Skala: 1:",
    "label_scale_x": "Skala X: 1:",
    "label_scale_y": "Skala Y: 1:",
    "label_output_dimensions": "Utdatamått för fil:",
    "label_width_cm": "Bredd [cm]:",
    "label_height_cm": "Höjd [cm]:",
    "section_split_settings": " Delningsinställningar ",
    "section_profiles": " Inställningsprofiler ",
    "section_save_location": " Spara plats ",
    "section_input_preview": " Förhandsgranskning av indatafil ",
    "section_output_preview": " Förhandsgranskning av utdatafil ",

    # --- Alternativvärden (Combobox, Radiobutton etc.) ---
    "layout_vertical": "Vertikal",
    "layout_horizontal": "Horisontell",
    "output_common_sheet": "Gemensamt ark",
    "output_separate_files": "Separata filer",
    "output_both": "Gemensamt ark och separata filer",
    "output_common": "Gemensamt ark",
    "output_separate": "Separata filer",
    "reg_mark_cross": "Kors",
    "reg_mark_line": "Linje",
    "code_qr": "QR-kod",
    "code_barcode": "Streckkod",
    "bryt_order_1": "A1-An, B1-Bn, .. Standard, från toppen",
    "bryt_order_2": "A1-An, Bn-B1, .. Orm per rad, från toppen",
    "bryt_order_3": "A1..B1, A2..B2, .. Per kolumn, från toppen",
    "bryt_order_4": "A1-A2..B2-B1.. Orm per kolumn, från toppen",
    "bryt_order_5": "N1-Nn, (N-1)1-(N-1)n, .. Standard, från botten",
    "bryt_order_6": "N1-Nn, (N-1)n-(N-1)1, .. Orm per rad, från botten",
    "logging_console": "konsol",
    "logging_file": "fil",
    "logging_both": "båda",

    # --- Sektioner/Ramar (Inställningar-fliken) ---
    "section_processing_mode": " Skärningsoperationer ",
    "processing_mode_ram": "RAM (i minnet)",
    "processing_mode_hdd": "HDD (på disk)",
    "graphic_settings": "Grafiska inställningar",
    "code_settings": "QR / Streckkodsinställningar",
    "logging_settings": "Loggningsinställningar",
    "barcode_text_position_label": "Streckkodstext position:",
    "barcode_text_bottom": "under",
    "barcode_text_side": "bredvid",
    "barcode_text_none": "ingen",

    # --- Fältetiketter (Inställningar-fliken - Grafik) ---
    "extra_margin_label": "Marginal runt paneler [mm]:",
    "margin_top_label": "Toppmarginal [mm]:",
    "margin_bottom_label": "Bottenmarginal [mm]:",
    "margin_left_label": "Vänstermarginal [mm]:",
    "margin_right_label": "Högermarginal [mm]:",
    "reg_mark_width_label": "Registreringsmärke - Bredd [mm]:",
    "reg_mark_height_label": "Registreringsmärke - Höjd [mm]:",
    "reg_mark_white_line_width_label": "Registreringsmärke - Vit linjetjocklek [mm]:",
    "reg_mark_black_line_width_label": "Registreringsmärke - Svart linjetjocklek [mm]:",
    "sep_line_black_width_label": "Separationslinje - Svart linjetjocklek [mm]:",
    "sep_line_white_width_label": "Separationslinje - Vit linjetjocklek [mm]:",
    "slice_gap_label": "Mellanrum mellan paneler [mm]:",
    "label_draw_slice_border": "Rita kantlinje runt panel (skärlinje)",

    # --- Fältetiketter (Inställningar-fliken - Koder) ---
    "scale_label": "Storlek [mm]:",
    "scale_x_label": "Bredd X [mm]:",
    "scale_y_label": "Höjd Y [mm]:",
    "offset_x_label": "Förskjutning X [mm]:",
    "offset_y_label": "Förskjutning Y [mm]:",
    "rotation_label": "Rotation (°):",
    "anchor_label": "Hörn:",

    # --- Fältetiketter (Inställningar-fliken - Loggning) ---
    "logging_mode_label": "Loggningsläge:",
    "log_file_label": "Loggfil:",
    "logging_level_label": "Loggningsnivå:",

    # --- Knappar / Åtgärder (Hem-fliken) ---
    "button_load": "Ladda",
    "button_save_settings": "Spara nuvarande inställningar",
    "button_generate_pdf": "Generera PDF",
    "button_refresh_preview": "Uppdatera förhandsgranskning",
    "button_refresh_layout": "Uppdatera layout",

    # --- Licens (GUI) ---
    "hwid_frame_title": "Unik maskinvaruidentifierare (HWID)",
    "copy_hwid": "Kopiera HWID",
    "license_frame_title": "Licensaktivering",
    "enter_license_key": "Ange licensnyckeln:",
    "activate": "Aktivera",
    "status_trial": "Testläge",
    "license_active": "Licens aktiv",

    # ================================================
    #  Användarmeddelanden (Fönster, Statusfält)
    # ================================================

    # --- Profiler ---
    "msg_no_profile_name": "Inget namn",
    "msg_enter_profile_name": "Ange ett profilnamn för att spara.",
    "msg_profile_saved": "Profil sparad",
    "profile_saved_title": "Profil sparad",
    "msg_profile_saved_detail": "Profilen '{0}' har sparats.",
    "profile_saved": "Profile '{profile}' has been saved.",
    "profile_saved_and_applied": "Profilen '{profile}' har sparats och tillämpats.",
    "msg_no_profile": "Ingen profil",
    "warning_no_profile": "Ingen profil",
    "msg_select_profile": "Välj ett profilnamn från listan för att ladda.",
    "select_profile": "Välj ett profilnamn från listan för att ladda.",
    "profile_loaded_title": "Profil laddad",
    "profile_loaded": "Profilen '{profile}' har laddats.",
    "warning_no_profile_delete": "Ingen profil",
    "warning_no_profile_delete_message": "Välj en profil från listan för att ta bort.",
    "profile_not_found": "Profilen '{profile}' hittades inte.",
    "profile_not_exist": "Profilen '{profile}' finns inte.",
    "confirm_delete_title": "Bekräfta borttagning",
    "confirm_delete_profile": "Är du säker på att du vill ta bort profilen '{profile}'?",
    "profile_deleted_title": "Profil borttagen",
    "profile_deleted": "Profilen '{profile}' har tagits bort.",

    # --- Filer / Kataloger ---
    "msg_no_input_file": "Ingen indatafil",
    "msg_unsupported_format": "Formatet stöds inte",
    "select_file_title": "Välj indatafil",
    "supported_files": "Filer som stöds",
    "all_files": "Alla filer",
    "select_dir_title": "Välj utdatakatalog",
    "select_log_dir_title": "Välj katalog för loggfiler",
    "error_output_dir_title": "Fel i utdatakatalog",
    "error_output_dir": "Den angivna utdatakatalogen är ogiltig eller finns inte:\n{directory}",
    "error_input_file_title": "Fel i indatafil",
    "error_input_file": "Den angivna indatafilen är ogiltig eller finns inte:\n{file}",
    "save_file_error_title": "Fel vid sparande av fil",
    "save_file_error": "Kunde inte spara filen: {error}",

    # --- PDF-bearbetning / Förhandsgranskning ---
    "msg_pdf_processing_error": "Kunde inte bearbeta PDF-filen",
    "msg_thumbnail_error": "Fel vid laddning av miniatyrbild",
    "msg_no_pdf_output": "Ingen PDF-utdata",
    "no_pdf_pages": "Inga sidor i PDF-filen",
    "unsupported_output": "Utdatatyp stöds inte för förhandsgranskning",
    "pdf_generated_title": "Generering slutförd",
    "pdf_generated": "PDF-fil(er) har genererats i katalogen:\n{directory}",
    "pdf_generation_error_title": "Genereringsfel",
    "pdf_generation_error": "Fel uppstod vid generering av PDF. Kontrollera loggarna för mer information.",
    "critical_pdf_error_title": "Kritiskt PDF-genereringsfel",
    "critical_pdf_error": "Ett kritiskt fel uppstod vid generering av PDF:\n{error}\nKontrollera loggarna.",

    # --- Inställningar ---
    "settings_saved_title": "Inställningar sparade",
    "settings_saved": "Inställningarna har sparats i filen:\n{filepath}",
    "settings_save_error_title": "Fel vid sparande av inställningar",
    "settings_save_error": "Kunde inte spara inställningarna: {error}",
    "conversion_error_title": "Konverteringsfel",
    "conversion_error": "Fel vid konvertering av värden från GUI: {error}",
    "update_gui_error_title": "GUI-uppdateringsfel",
    "update_gui_error": "Ett fel uppstod vid uppdatering av gränssnittet: {error}",

    # --- Licens ---
    "hwid_copied_to_clipboard": "HWID har kopierats till urklipp",
    "computer_hwid": "Datorns HWID",
    "public_key_load_error": "Fel vid laddning av offentlig nyckel: {error}",
    "invalid_license_format": "Ogiltigt licensnyckelformat: {error}",
    "activation_success": "Licensen har aktiverats.",
    "activation_error": "Fel vid licensaktivering: {error}",
    "log_trial_mode_active": "Testläge är aktivt",
    "log_trial_mode_inactive": "Testläge är inaktivt",

    # --- Initialisering ---
    "init_error_title": "Initialiseringsfel",
    "init_error": "Fel vid initialisering av kataloger: {error}",
    "poppler_path_info": "Poppler-sökvägsinformation",
    "ttkthemes_not_installed": "Varning: Biblioteket ttkthemes är inte installerat. Använder standard Tkinter-stil.",

    # =====================================
    #  Loggar (Loggermeddelanden)
    # =====================================

    # --- Allmän loggning / Konfiguration ---
    "log_configured": "Loggning konfigurerad: nivå={0}, läge={1}, fil={2}",
    "log_no_handlers": "Varning: Inga logghanterare konfigurerade (läge: {0}).",
    "log_critical_error": "Kritiskt loggkonfigurationsfel: {0}",
    "log_basic_config": "Grundläggande loggkonfiguration användes på grund av ett fel.",
    "log_dir_create_error": "Kritiskt fel: Kan inte skapa loggkatalog {0}: {1}",

    # --- Loggar - Initialisering / Kataloger (`init_directories.py`) ---
    "error_critical_init": "KRITISKT FEL under initialisering: {0}",
    "logger_init_error": "Kataloginitialiseringsfel: {error}",
    "directory_created": "Katalog skapad: {0}",
    "directory_creation_error": "Kunde inte skapa katalog {0}: {1}",
    "sample_file_copied": "Exempelfil kopierad till {0}",
    "sample_file_copy_error": "Fel vid kopiering av exempelfil: {0}",
    "log_created_output_dir": "Utdatakatalog skapad: {0}",
    "log_cannot_create_output_dir": "Kan inte skapa utdatakatalog {0}: {1}",

    # --- Loggar - Splitter (`splitter.py`) ---
    #   Splitter - Initialisering och Laddning
    "log_graphic_settings_error": "Kunde inte ladda grafiska inställningar under initialisering: {0}",
    "log_loading_pdf": "Laddar PDF-fil: {0}",
    "log_loading_bitmap": "Laddar bitmap-fil: {0}",
    "log_invalid_dpi": "Ogiltig DPI läst ({0}). Använder standard {1} DPI.",
    "log_image_dimensions": "Bildens dimensioner: {0}x{1}px, Läge: {2}, DPI: {3:.1f} -> {4:.3f}x{5:.3f}pt",
    "log_image_processing_color": "Bearbetar bild med originalfärgläge: {0}",
    "log_unusual_color_mode": "Ovanligt bildfärgläge: '{0}'. ReportLab/Pillow kanske inte hanterar det korrekt.",
    "log_draw_image_error": "Fel under ReportLab drawImage för läge {0}: {1}",
    "log_unsupported_format": "Indatafilformat stöds inte: {0}",
    "log_input_file_not_found": "Indatafil hittades inte: {0}",
    "log_load_process_error": "Fel vid laddning eller bearbetning av fil {0}: {1}",
    "log_input_file_not_exists": "Indatafil finns inte eller sökvägen är tom: '{0}'",
    "log_cannot_load_or_empty_pdf": "Kunde inte ladda indatafil eller PDF är tom/skadad.",
    "log_pdf_dimensions_info": "  PDF-dimensioner: {0:.1f}mm x {1:.1f}mm",
    "log_invalid_pdf_dimensions": "Ogiltiga PDF-siddimensioner: {0}x{1} pt.",

    #   Splitter - Dimensionsberäkningar
    "log_extra_margin": "Extra marginal satt till {0:.3f} pt",
    "log_invalid_rows_cols": "Ogiltigt antal rader ({0}) eller kolumner ({1}).",
    "error_invalid_rows_cols": "Rader och kolumner måste vara positiva heltal.",
    "log_invalid_overlap_white_stripe": "Ogiltiga värden för överlappning ({0}) eller vit rand ({1}). Måste vara siffror.",
    "error_invalid_overlap_white_stripe": "Överlappning och vit rand måste vara numeriska värden (mm).",
    "log_stripe_usage": "Satt use_white_stripe={0}, white_stripe={1:.3f} mm",
    "log_effective_overlap": "Basöverlappning (grafik): {0:.3f} mm, Vit rand: {1:.3f} mm, Effektiv överlappning: {2:.3f} mm",
    "log_computed_dimensions": "Beräknade dimensioner: PDF: {0:.3f}mm x {1:.3f}mm. Panel: {2:.3f}pt ({3:.3f}mm) x {4:.3f}pt ({5:.3f}mm). Kärna: {6:.3f}pt x {7:.3f}pt. Effektiv överlappning: {8:.3f}mm",
    "log_invalid_dimensions": "Beräknade panel- ({0:.3f}x{1:.3f}) eller kärndimensioner ({2:.3f}x{3:.3f}) är ogiltiga för överlappning={4}, rand={5}, r={6}, k={7}, B={8}mm, H={9}mm",
    "error_invalid_slice_dimensions": "Beräknade panel/kärn-dimensioner är ogiltiga eller negativa.",

    #   Splitter - Generering av Panelinfo och Ordning
    "log_generating_slice_info": "Genererar panelinfo: {0}",
    "log_no_slices_info_generated": "Kunde inte generera panelinfo.",
    "log_applying_rotated_order": "Tillämpar ordning för 180-graders rotation: {0}",
    "log_applying_standard_order": "Tillämpar ordning för 0-graders rotation (standard): {0}",
    "log_unknown_bryt_order": "Okänd panelordning: '{0}'. Använder standard.",
    "log_final_slices_order": "  Slutlig panelordning ({0}): [{1}]",

    #   Splitter - Skapa Överlägg och Sammanfoga
    "log_invalid_dimensions_overlay": "Försök att skapa ett överlägg med ogiltiga dimensioner: {0}. Hoppar över.",
    "log_empty_overlay": "Skapade en tom eller nästan tom överläggs-PDF. Hoppar över sammanfogning.",
    "log_overlay_error": "Fel vid skapande av överläggs-PDF: {0}",
    "log_merge_error": "Försök att sammanfoga överlägg utan sidor. Hoppar över.",
    "log_merge_page_error": "Fel vid sammanfogning av överläggs-PDF: {0}",
    "log_fallback_draw_rotating_elements": "Kunde inte hämta rader/kolumner för _draw_rotating_elements, använde 1x1.",
    "log_overlay_created_for_slice": "Skapade ränder/märken-överlägg för panel {0}",
    "log_overlay_creation_failed_for_slice": "Kunde inte skapa ränder/märken-överlägg för {0}",
    "log_merging_rotated_overlay": "Sammanfogar ROTERAT ränder/märken-överlägg för {0} med T={1}",
    "log_merging_nonrotated_overlay": "Sammanfogar ICKE-roterat ränder/märken-överlägg för {0}",
    "log_merging_all_codes_overlay": "Sammanfogar överlägg av alla koder (utan rotation)",
    "log_merging_separation_lines_overlay": "Sammanfogar överlägg av separationslinjer (utan rotation)",
    "log_merging_code_overlay_for_slice": "Kodöverlägg för {0} sammanfogat utan rotation.",
    "log_merging_separation_overlay_for_slice": "Separationslinjer-överlägg för {0} sammanfogat utan rotation.",

    #   Splitter - Rita Grafiska Element (Ränder, Märken, Linjer)
    "log_drawing_top_stripe": "[Canvas Draw] Ritar topprand för {0}: x={1:.3f}, y={2:.3f}, w={3:.3f}, h={4:.3f}",
    "log_drawing_right_stripe": "[Canvas Draw] Ritar höger rand för {0}: x={1:.3f}, y={2:.3f}, w={3:.3f}, h={4:.3f}",
    "log_drawing_corner_stripe": "[Canvas Draw] Fyller och stryker hörn för {0} @ ({1:.3f}, {2:.3f})",
    "log_drawing_registration_mark": "Ritar centrerat kors vid ({0:.3f}, {1:.3f})",
    "log_drawing_reg_lines_for_slice": "Ritar registreringslinjer för {0} i område från ({1:.3f},{2:.3f})",
    "log_drawing_right_vertical_line": "  Ritar höger vertikal linje: x={0:.3f}, y={1:.3f} -> {2:.3f}",
    "log_drawing_top_horizontal_line": "  Ritar övre horisontell linje: y={0:.3f}, x={1:.3f} -> {2:.3f}",
    "log_drawing_separation_line": "Ritar separationslinje (vit på svart): ({0}) @ ({1:.3f}, {2:.3f}), längd={3:.3f}",
    "log_drawing_reg_marks_for_slice": "Ritar kors för {0} [{1},{2}] / [{3},{4}] i område från ({5:.1f},{6:.1f})",
    "log_coord_calculation": "  Beräknade centra: TL({0:.1f},{1:.1f}), TR({2:.1f},{3:.1f}), BL({4:.1f},{5:.1f}), BR({6:.1f},{7:.1f})",
    "log_drawing_tl": "    Ritar TL @ ({0:.1f}, {1:.1f})",
    "log_drawing_tr": "    Ritar TR @ ({0:.1f}, {1:.1f})",
    "log_drawing_bl": "    Ritar BL @ ({0:.1f}, {1:.1f})",
    "log_drawing_br": "    Ritar BR @ ({0:.1f}, {1:.1f})",
    "log_omitting_mark": "    Uteslöt {0} enligt regel för position [{1},{2}]",
    "log_trial_common_sheet": "Tillämpar TRIAL-vattenstämpeltext på gemensamt ark",

    # Vattenstämpel
    "log_trial_watermark_added": "TRIAL-vattenstämpel har lagts till",
    "error_drawing_trial_text": "Fel vid ritning av vattenstämpel: {error}",

    #   Splitter - Rita Separationslinjer (Hela Sidan)
    "log_drawing_separation_lines_for_page": "Ritar separationslinjer för sida (layout={0}, total_slices={1}, slice_index={2})",
    "log_vertical_line_between_slices": "  Vertikal linje mellan paneler {0}-{1} @ x={2:.1f}",
    "log_vertical_line_start": "  Vertikal linje start @ x={0:.1f}",
    "log_vertical_line_end": "  Vertikal linje slut @ x={0:.1f}",
    "log_horizontal_line_between_slices": "  Horisontell linje mellan paneler {0}-{1} @ y={2:.1f}",
    "log_horizontal_line_start": "  Horisontell linje start @ y={0:.1f}",
    "log_horizontal_line_end": "  Horisontell linje slut @ y={0:.1f}",
    "log_sep_line_start_separate": "  (Separate_files) Vertikal/Horisontell linje start @ {0:.1f}",
    "log_sep_line_end_separate": "  (Separate_files) Vertikal/Horisontell linje slut @ {0:.1f}",

    #   Splitter - Generera Streckkoder / QR
    "log_generate_barcode_data": "Genererar streckkodsdata: {0}",
    "log_barcode_data_shortened": "Streckkodsdata förkortad till {0} tecken.",
    "log_barcode_data_error": "Fel vid generering av streckkodsdata: {0}",
    "log_compose_barcode_payload": "Sammansätter streckkods-payload ({0}): {1}",
    "log_barcode_payload_shortened": "Payload förkortad till {0} tecken för format {1}",
    "log_barcode_payload_error": "Fel vid sammansättning av payload: {0}",
    "log_unknown_anchor_fallback": "Okänt ankare '{0}', använder nedre vänstra",
    "log_used_default_code_settings": "Använde 'default'-inställningar för kod {0}/{1}.",
    "log_no_layout_key_fallback": "Ingen layout '{0}' för {1}/{2}. Använde den första tillgängliga: '{3}'.",
    "log_code_settings_error": "Hittades inte eller fel vid hämtning av kodinställningar ({0}/{1}/{2}): {3}. Använder standardvärden.",
    "log_drawing_barcode": "Ritar {0} vid ({1:.3f}, {2:.3f}) [bas ({3:.3f}, {4:.3f}) + offset ({5:.3f}, {6:.3f})], rotation: {7}°",
    "error_generate_qr_svg": "Kunde inte generera QR-kod SVG.",
    "error_invalid_scale_for_qr": "Ogiltig skala för QR: {0}mm",
    "error_invalid_qr_scale_factor": "Ogiltig skalfaktor för QR: {0}",
    "error_generate_barcode_svg": "Kunde inte generera streckkods-SVG.",
    "error_invalid_scale_for_barcode": "Ogiltig skala för Streckkod: {0}x{1}mm",
    "error_invalid_barcode_scale_factor": "Ogiltig skalfaktor för Streckkod: ({0:.4f}, {1:.4f})",
    "log_barcode_scale_qr": "  {0}: skalakonfig={1:.3f}mm, SVG-bredd={2:.3f}pt, sf={3:.4f}",
    "log_barcode_scale_code128": "  {0}: skalakonfig=({1:.3f}mm, {2:.3f}mm), SVG-storlek=({3:.3f}pt, {4:.3f}pt), sf=({5:.4f}, {6:.4f})",
    "log_barcode_drawing_error": "Fel vid ritning av kod '{0}': {1}",
    "log_prepared_barcode_info": "Förberedd kodinfo för {0} ({1}, ankare={2}): bas absolut position ({3:.1f}, {4:.1f})",
    "log_barcode_info_prep_error": "Fel vid förberedelse av koddata för {0}: {1}",
    "log_drawing_barcodes_count": "Ritar {0} streckkoder/QR-koder...",
    "log_missing_barcode_info_key": "Saknad nyckel i kodinfo vid ritning: {0}. Info: {1}",
    "log_error_drawing_barcode_in_draw_all": "Fel vid ritning av kod '{0}' i _draw_all_barcodes: {1}",

    #   Splitter - Delningsprocess (split_* metoder)
    "log_start_splitting_process": "--- Startar delningsprocess för: {0} ---",
    "log_split_settings": "  Inställningar: {0}x{1} paneler, Överlappning={2}mm, Vit rand={3}mm (+överlappning: {4})",
    "log_output_dir_info": "  Utdata: {0} / {1} till '{2}'",
    "log_lines_marks_barcodes_info": "  Linjer: Separation={0}, Start={1}, Slut={2} | Märken: {3} ({4}), Koder: {5} ({6})",
    "log_bryt_order_info": "  Ordning: {0}, Panelrotation: {1}°",
    "log_invalid_dimensions_in_slice_info": "Ogiltiga dimensioner i slice_info för {0}: {1}x{2}",
    "log_content_transform": "Innehållstransformation T_content för {0}: {1}",
    "log_merged_content_for_slice": "Sammanfogat innehåll för panel {0} på ny_sida",
    "log_slice_reader_created": "Skapade komplett del (PdfReader) för panel {0}",
    "log_slice_reader_creation_error": "Fel vid skapande av komplett del för panel {0}: {1}",
    "log_used_get_transform": "Använde _get_transform (endast translation): x={0:.1f}, y={1:.1f}",
    "log_start_split_separate_files": "--- Startar: SEPARATA FILER (Rotation hanteras i create_slice_reader) ---",
    "log_creating_file_for_slice": "Skapar fil för panel {0}: {1}",
    "log_invalid_page_size_for_slice": "Ogiltig sidstorlek ({0}x{1}) för {2}. Hoppar över.",
    "log_blank_page_creation_error": "Fel vid skapande av sida för {0} (storlek {1}x{2}): {3}. Hoppar över.",
    "log_transform_for_slice": "Transform T (endast translation) för {0}: {1}",
    "log_merging_complete_slice": "Sammanfogar komplett panel {0} med transform: {1}",
    "log_skipped_slice_merging": "Hoppade över sammanfogning av komplett panel för {0}.",
    "log_file_saved": "Fil sparad: {0}",
    "log_file_save_error": "Fel vid sparande av fil {0}: {1}",
    "log_finished_split_separate_files": "--- Färdig: SEPARATA FILER (Sparade {0}/{1}) ---",
    "log_no_slices_split_horizontal": "Inga paneler att bearbeta i split_horizontal.",
    "log_start_split_horizontal": "--- Startar: GEMENSAMT ARK - HORISONTAL (Rotation hanteras i create_slice_reader) ---",
    "log_page_dimensions": "Siddimensioner: {0:.1f}mm x {1:.1f}mm ({2} paneler)",
    "log_page_creation_error": "Fel vid skapande av resultatsida ({0}x{1}): {2}. Avbryter.",
    "log_slice_at_position": "Panel {0} [{1}/{2}] @ ({3:.1f}, {4:.1f})",
    "log_transform_t_only": "Transform T (endast translation) för {0}: {1}",
    "log_merging_complete_bryt": "Sammanfogar komplett panel {0} med transform: {1}",
    "log_skipped_merging_bryt": "Hoppade över sammanfogning av komplett panel för {0}.",
    "log_file_result_saved": "Resultatfil sparad: {0}",
    "log_file_result_save_error": "Fel vid sparande av resultatfil {0}: {1}",
    "log_finished_split_horizontal": "--- Färdig: GEMENSAMT ARK - HORISONTAL ---",
    "log_no_slices_split_vertical": "Inga paneler att bearbeta i split_vertical.",
    "log_start_split_vertical": "--- Startar: GEMENSAMT ARK - VERTIKAL (Rotation hanteras i create_slice_reader) ---",
    "log_finished_split_vertical": "--- Färdig: GEMENSAMT ARK - VERTIKAL ---",
    "log_unknown_layout": "Okänd layout för gemensamt ark: '{0}'.",
    "log_unknown_output_type": "Okänd utdatatyp: '{0}'.",
    "log_finished_splitting_success": "--- Avslutade delningsprocess för: {0} - LYCKADES ---",
    "log_finished_splitting_errors": "--- Avslutade delningsprocess för: {0} - FEL UPPSTOD ---",
    "log_value_error_in_splitting": "Indata- eller beräkningsfel: {0}",
    "log_finished_splitting_critical_error": "--- Avslutade delningsprocess för: {0} - KRITISKT FEL ---",
    "log_unexpected_error_in_splitting": "Oväntat fel vid delning av fil {0}: {1}",

    #   Splitter - Testläge (__main__)
    "log_script_mode_test": "splitter.py startades som huvudskript (testläge).",
    "log_loaded_config": "Konfiguration laddad.",
    "log_error_loading_config": "Kunde inte ladda konfiguration: {0}",
    "log_created_example_pdf": "Skapade exempel-PDF-fil: {0}",
    "log_cannot_create_example_pdf": "Kunde inte skapa exempel-PDF: {0}",
    "log_start_test_split": "Startar testdelning av fil: {0} till {1}",
    "log_test_split_success": "Testdelning slutfördes framgångsrikt.",
    "log_test_split_errors": "Testdelning avslutades med fel.",

    # --- Loggar - QR/Streckkod (`barcode_qr.py`) ---
    "log_qr_empty_data": "Försök att generera QR-kod för tom data.",
    "log_qr_generated": "QR-kod SVG genererad för: {0}...",
    "log_qr_error": "Fel vid generering av QR-kod för data '{0}': {1}",
    "log_barcode_empty_data": "Försök att generera streckkod för tom data.",
    "log_barcode_generated": "Streckkods-SVG genererad för: {0}...",
    "log_barcode_error": "Fel vid generering av streckkod för data '{0}': {1}",
    "log_basic_handler_configured": "Grundläggande hanterare konfigurerad för logger i barcode_qr.py",
    "log_basic_handler_error": "Kunde inte konfigurera grundläggande logghanterare i barcode_qr: {0}",

    # --- Loggar - Konfig/Profiler (`main_config_manager.py`) ---
    "loading_profiles_from": "Laddar profiler från",
    "profiles_file": "Profilfil",
    "does_not_contain_dict": "innehåller inte en ordbok. Skapar en ny",
    "not_found_creating_new": "hittades inte. Skapar en ny tom",
    "json_profiles_read_error": "Fel vid läsning av JSON-profilfil",
    "file_will_be_overwritten": "Filen kommer att skrivas över vid sparande",
    "json_decode_error_in_profiles": "JSON-avkodningsfel i profilfil",
    "cannot_load_profiles_file": "Kan inte ladda profilfil",
    "unexpected_profiles_read_error": "Oväntat fel vid läsning av profiler",
    "saving_profiles_to": "Sparar profiler till",
    "cannot_save_profiles_file": "Kan inte spara profilfil",
    "profiles_save_error": "Fel vid sparande av profiler till fil",
    "logger_profile_saved": "Profil sparad: {profile}",
    "logger_profile_not_found": "Profilen hittades inte för att ladda: {profile}",
    "logger_profile_loaded": "Profil laddad: {profile}",
    "logger_profile_delete_not_exist": "Försök att ta bort en profil som inte finns: {profile}",
    "logger_profile_deleted": "Profil borttagen: {profile}",
    "logger_start_save_settings": "Började spara inställningar från GUI.",
    "logger_invalid_value": "Ogiltigt värde för '{key}'. Satt till 0.0.",
    "logger_end_save_settings": "Slutförde sparande av inställningar från GUI.",
    "logger_conversion_error": "Värdekonverteringsfel från GUI: {error}",
    "conversion_failed": "Konvertering av GUI-värden misslyckades",
    "logger_unexpected_save_error": "Oväntat fel vid sparande av inställningar: {error}",
    "logger_settings_saved": "Inställningar sparade i fil: {file}",

    # --- Loggar - Licensiering (`main_license.py`) ---
    "public_key_load_error_log": "Fel vid laddning av offentlig nyckel",
    "license_key_decode_error": "Fel vid avkodning av licensnyckel",
    "license_activation_error": "Licensaktiveringsfel",

    # --- Loggar - Huvudmodul (`main.py`) ---
    "ui_created": "Användargränssnitt har skapats.",
    "error_tab_home": "Fel vid skapande av 'Hem'-flikens UI",
    "error_tab_settings": "Fel vid skapande av 'Inställningar'-flikens UI",
    "error_tab_help": "Fel vid skapande av 'Hjälp'-flikens UI",
    "error_creating_license_ui": "Fel vid skapande av 'Licens'-flikens UI",
    "error_loading_ui": "Fel vid laddning av gränssnitt: {error}",
    "error_creating_home_ui": "Fel vid skapande av 'Hem'-flikens UI",
    "error_creating_settings_ui": "Fel vid skapande av 'Inställningar'-flikens UI",
    "error_creating_help_ui": "Fel vid skapande av 'Hjälp'-flikens UI",
    "logger_update_gui": "Började uppdatera GUI från konfiguration.",
    "logger_end_update_gui": "Slutförde uppdatering av GUI från konfiguration.",
    "logger_update_gui_error": "Oväntat fel vid uppdatering av GUI: {error}",
    "logger_invalid_output_dir": "Ogiltig eller obefintlig utdatakatalog: {directory}",
    "logger_invalid_input_file": "Ogiltig eller obefintlig indatafil: {file}",
    "logger_start_pdf": "Startade PDF-genereringsprocess.",
    "logger_pdf_save_error": "PDF-generering avbruten - kunde inte spara nuvarande inställningar.",
    "logger_pdf_success": "PDF-generering slutfördes framgångsrikt.",
    "logger_pdf_exception": "Undantag under huvud-PDF-genereringsprocess.",
    "icon_set_error": "Kunde inte ställa in programikon: {error}",
    "accent_button_style_error": "Kunde inte ställa in stil för accentknapp: {error}",
    "logger_file_save_error": "Fel vid sparande av fil {file}: {error}",

    #   Loggar - Förhandsgranskning (`main.py` - update_preview, update_output_preview)
    "thumbnail_error_log": "Fel vid generering av miniatyrbild",
    "output_preview_update_called": "Uppdatering av utdataförhandsgranskning anropad",
    "output_preview_canvas_missing": "Canvas för utdataförhandsgranskning saknas",
    "pdf_found_in_output_dir": "PDF hittad i utdatakatalog",
    "preparing_thumbnail": "Förbereder miniatyrbild",
    "thumbnail_generated_successfully": "Miniatyrbild genererad framgångsrikt",
    "thumbnail_generation_error": "Fel vid generering av miniatyrbild för",
    "no_pdf_for_common_sheet": "Ingen PDF-fil för förhandsgranskning av gemensamt ark",
    "no_pdf_for_separate_files": "Inga genererade separata PDF-filer för förhandsgranskning",
    "cannot_load_thumbnail": "Kan inte ladda miniatyrbild från",

    #   Loggar - Utvecklare / GUI internt (`main.py`)
    "missing_gui_var_created": "Skapade saknad GUI-variabel för nyckel: {key}",
    "missing_gui_structure_created": "Skapade saknad GUI-struktur för: {code_type}/{output_type}/{layout}",
    "missing_gui_var_detailed_created": "Skapade saknad GUI-variabel för: {code_type}/{output_type}/{layout}/{param}",

    # Ytterligare nycklar för main_ui_help.py
    "help_text": "\n    Billboard Splitter – Användarhandbok\n\n\n    Programmets syfte:\n\n    Billboard Splitter används för att automatiskt skära billboard-projekt i tryckfärdiga paneler.\n    Programmet är förberett för att arbeta med filer designade i skala 1:10.\n\n    Värden i avsnitten: Överlappning, Vit rand, Inställningar anges i skala 1:1.\n    Programmet gör det möjligt att arrangera de skurna panelerna på PDF-ark beroende på vald layout:\n\n    • Gemensamt ark: Alla paneler placeras på ett dokument.\n\n    • Separata filer: Varje panel sparas i en separat PDF-fil.\n\n\n    Dessutom tillåter programmet:\n\n    • Att välja en layout – vertikal eller horisontell (följaktligen: i den vertikala layouten visas separationslinjer upptill och nedtill,\n      och i den horisontella layouten på vänster och höger sida).\n\n    • Att rotera paneler 180° (vänder hela projektet).\n\n    • Att lägga till registreringsmärken (t.ex. kors eller linjer) för att underlätta exakt positionering vid limning.\n\n    • Att lägga till QR-koder eller streckkoder – genererade baserat på indata för att hjälpa\n      till att identifiera enskilda paneler.\n\n    • Att spara inställningar som profiler som kan laddas, ändras och tas bort, vilket gör det enkelt att\n      växla mellan olika projektkonfigurationer.\n\n\n    Huvudsteg för att använda programmet:\n\n\n    1. Välj indatafil:\n\n    • I fliken 'Hem', välj en PDF-, JPG- eller TIFF-fil som innehåller billboard-designen.\n\n    • Om du inte anger din egen sökväg, ställer programmet in en exempelfil som standard.\n\n\n    2. Skärinställningar:\n\n    • Ange antalet rader och kolumner som projektet ska delas in i.\n\n    • Ställ in överlappningsstorleken.\n\n    • Ange eventuellt bredden på den vita randen som ska läggas till den effektiva överlappningen.\n\n\n    3. Välj utdata-layout:\n\n    • Vertikal: Alla paneler kommer att arrangeras vertikalt på ett PDF-ark.\n\n    • Horisontell: Alla paneler kommer att arrangeras horisontellt på ett PDF-ark.\n\n\n    4. Välj utdatatyp:\n\n    • Gemensamt ark: Alla paneler kommer att arrangeras på ett gemensamt PDF-ark.\n\n    • Separata filer: Varje panel kommer att sparas i en separat PDF-fil.\n\n    • I fliken 'Hem' kan du aktivera och konfigurera registreringsmärken – välj mellan kors och linje.\n\n    • Aktivera eventuellt en QR-kod eller en streckkod som kommer att genereras från projektdata.\n\n    • Kodparametrar (skalning, förskjutning, rotation, position) kan finjusteras i fliken 'Inställningar'.\n\n\n    5. Hantera inställningar:\n\n    • I fliken 'Inställningar' kan du exakt ändra grafiska parametrar (marginaler, linjetjocklekar, mellanrum) och\n      kodinställningar.\n\n    • Spara de nuvarande inställningarna som en profil så att du enkelt kan ladda eller ändra dem senare.\n\n    • Inställningsprofiler (sparade i filen profiles.json) tillåter snabb växling mellan olika\n\n      projektkonfigurationer.\n\n\n    6. Generera PDF:\n\n    • När alla parametrar är konfigurerade, klicka på 'Generera PDF'.\n\n    • Resultatfiler sparas i 'output'-katalogen eller en annan angiven katalog, och loggar (med daglig rotation) i 'logs'-katalogen\n      eller en annan angiven katalog.\n\n\n    Om problem uppstår:\n\n    • Kontrollera loggarna i 'logs'-mappen. Varje dag genereras en separat loggfil med datumet i namnet.\n\n    • Se till att alla nödvändiga mappar är inställda.\n\n    • Teknisk support: tech@printworks.pl (vardagar, 8-16)\n\n    "
}