# lang_fil.py
# -*- coding: utf-8 -*-
"""
Filipino (Philippines) translations — LTR.
"""

LANG = {
    "barcode_font_size_label": "Laki ng font ng paglalarawan ng barcode [pt]:",
    "__meta__": {
        "language_name_native": "Filipino (Pilipinas)",
        "language_name_en": "Filipino (Philippines)",
        "locale": "fil-PH",
        "direction": "ltr",
        "font_hint": "Noto Sans, Noto Serif"
    },

    # Application - General
    "app_title": "Billboard Splitter v1.8",
    "error": "Error",
    "no_file": "Walang file",
    "language": "Wika",
    "language_switch": "Palitan ang wika",
    "choose_language": "Pumili ng wika:",
    "apply_language": "Ilapat",
    "language_changed": "Napalitan na ang wika. Ilan sa mga pagbabago ay lalabas pag na-restart ang app.",

    # GUI Elements
    "tab_home": " Home ",
    "tab_settings": " Settings ",
    "tab_help": " Tulong ",
    "tab_license": " Lisensya ",

    "button_browse": "Mag-browse…",
    "browse_folder": "Piliin ang folder…",
    "button_save": "I-save",
    "button_delete": "Tanggalin",
    "button_close": "Isara",
    "save_all_settings": "I-save ang lahat ng settings",

    "label_rows": "Patayong hati (rows):",
    "label_columns": "Pahalang na hati (columns):",
    "label_overlap": "Overlap [mm]:",
    "label_white_stripe": "Puting guhit [mm]:",
    "label_add_white_stripe": "Isama ang puting guhit sa epektibong overlap",
    "label_layout": "Layout:",
    "label_output_type": "Uri ng output:",
    "label_enable_reg_marks": "I-enable ang registration marks:",
    "label_enable_codes": "I-enable ang mga code:",
    "label_enable_sep_lines": "I-enable ang linya ng pagitan (sa pagitan ng panel)",
    "label_enable_start_line": "I-enable ang itaas/starting line ng sheet",
    "label_enable_end_line": "I-enable ang ibaba/ending line ng sheet",
    "label_bryt_order": "Ayos ng panel:",
    "label_slice_rotation": "Pag-ikot ng panel:",
    "label_create_order_folder": "Gumawa ng folder gamit ang order number",

    "section_input_file": " Input file ",
    "section_scale_and_dimensions": " Sukat at mga sukat ng output ",
    "label_original_size": "Orihinal na sukat:",
    "label_scale_non_uniform": "Hindi proporsyonal na pag-scale",
    "label_scale": "Sukat: 1:",
    "label_scale_x": "Sukat X: 1:",
    "label_scale_y": "Sukat Y: 1:",
    "label_output_dimensions": "Mga sukat ng output file:",
    "label_width_cm": "Lapad [cm]:",
    "label_height_cm": "Taas [cm]:",
    "section_split_settings": " Mga setting ng paghahati ",
    "section_profiles": " Mga profile ",
    "section_save_location": " Lokasyon ng save ",
    "section_input_preview": " Preview ng input ",
    "section_output_preview": " Preview ng output ",

    "layout_vertical": "Patayo",
    "layout_horizontal": "Pahalang",
    "output_common_sheet": "Karaniwang sheet",
    "output_separate_files": "Hiwa-hiwalay na files",
    "output_both": "Sheet + hiwalay na files",
    "output_common": "Karaniwang sheet",
    "output_separate": "Hiniwalay na files",
    "reg_mark_cross": "Krus",
    "reg_mark_line": "Linya",
    "code_qr": "QR code",
    "code_barcode": "Barcode",
    "bryt_order_1": "A1–An, B1–Bn … Standard, mula sa itaas",
    "bryt_order_2": "A1–An, Bn–B1 … Alon (ayon sa row), mula sa itaas",
    "bryt_order_3": "A1..B1, A2..B2 … Ayon sa column, mula sa itaas",
    "bryt_order_4": "A1–A2..B2–B1 … Alon (ayon sa column), mula sa itaas",
    "bryt_order_5": "N1–Nn, (N-1)1–(N-1)n … Standard, mula sa ibaba",
    "bryt_order_6": "N1–Nn, (N-1)n–(N-1)1 … Alon (row), mula sa ibaba",
    "logging_console": "Console",
    "logging_file": "File",
    "logging_both": "Pareho",

    "section_processing_mode": " Mga gawain sa pagputol ",
    "processing_mode_ram": "RAM (memory)",
    "processing_mode_hdd": "HDD (disk)",
    "graphic_settings": "Mga setting ng grapiko",
    "code_settings": "Mga setting ng QR / barcode",
    "logging_settings": "Mga setting ng log",
    "barcode_text_position_label": "Posisyon ng text sa barcode:",
    "barcode_text_bottom": "Ibaba",
    "barcode_text_side": "Gilid",
    "barcode_text_none": "Wala",

    "extra_margin_label": "Margin sa paligid ng panel [mm]:",
    "margin_top_label": "Margin sa itaas [mm]:",
    "margin_bottom_label": "Margin sa ibaba [mm]:",
    "margin_left_label": "Margin sa kaliwa [mm]:",
    "margin_right_label": "Margin sa kanan [mm]:",
    "reg_mark_width_label": "Registration mark — Lapad [mm]:",
    "reg_mark_height_label": "Registration mark — Taas [mm]:",
    "reg_mark_white_line_width_label": "Registration mark — Kapal ng puting linya [mm]:",
    "reg_mark_black_line_width_label": "Registration mark — Kapal ng itim na linya [mm]:",
    "sep_line_black_width_label": "Linyang pagitan — Kapal ng itim na linya [mm]:",
    "sep_line_white_width_label": "Linyang pagitan — Kapal ng puting linya [mm]:",
    "slice_gap_label": "Agwat sa pagitan ng mga panel [mm]:",
    "label_draw_slice_border": "Guhitan ang border ng panel (cut line)",

    "scale_label": "Scale [mm]:",
    "scale_x_label": "Lapad X [mm]:",
    "scale_y_label": "Taas Y [mm]:",
    "offset_x_label": "Offset X [mm]:",
    "offset_y_label": "Offset Y [mm]:",
    "rotation_label": "Ikot (°):",
    "anchor_label": "Angkla:",

    "logging_mode_label": "Log mode:",
    "log_file_label": "Log file:",
    "logging_level_label": "Antas ng log:",

    "button_load": "I-load",
    "button_save_settings": "I-save ang kasalukuyang settings",
    "button_generate_pdf": "Gumawa ng PDF",
    "button_refresh_preview": "I-refresh ang preview",
    "button_refresh_layout": "I-refresh ang layout",

    "hwid_frame_title": "Hardware ID (HWID)",
    "copy_hwid": "Kopyahin ang HWID",
    "license_frame_title": "Pag-activate ng lisensya",
    "enter_license_key": "Ilagay ang license key:",
    "activate": "I-activate",
    "status_trial": "Trial mode",
    "license_active": "Aktibo ang lisensya",

    # User Messages
    "msg_no_profile_name": "Walang pangalan",
    "msg_enter_profile_name": "Maglagay ng pangalan ng profile para i-save.",
    "msg_profile_saved": "Nai-save ang profile",
    "profile_saved_title": "Profile nai-save",
    "msg_profile_saved_detail": "Nai-save ang profile na '{0}'.",
    "profile_saved": "Profile '{profile}' has been saved.",
    "profile_saved_and_applied": "Ang profile na '{profile}' ay na-save at nailapat na.",
    "msg_no_profile": "Walang profile",
    "warning_no_profile": "Walang profile",
    "msg_select_profile": "Pumili ng profile mula sa listahan para i-load.",
    "select_profile": "Pumili ng profile mula sa listahan para i-load.",
    "profile_loaded_title": "Na-load ang profile",
    "profile_loaded": "Na-load ang profile na '{profile}'.",
    "warning_no_profile_delete": "Walang profile",
    "warning_no_profile_delete_message": "Pumili ng profile sa listahan para burahin.",
    "profile_not_found": "Hindi makita ang profile na '{profile}'.",
    "profile_not_exist": "Walang umiiral na profile na '{profile}'.",
    "confirm_delete_title": "Kumpirmahin ang pagbura",
    "confirm_delete_profile": "Sigurado ka bang buburahin ang profile na '{profile}'?",
    "profile_deleted_title": "Nabura ang profile",
    "profile_deleted": "Nabura ang profile na '{profile}'.",

    "msg_no_input_file": "Walang input file",
    "msg_unsupported_format": "Hindi suportadong format",
    "select_file_title": "Piliin ang input file",
    "supported_files": "Suportadong files",
    "all_files": "Lahat ng files",
    "select_dir_title": "Piliin ang output folder",
    "select_log_dir_title": "Piliin ang log folder",
    "error_output_dir_title": "Error sa output folder",
    "error_output_dir": "Ang napiling output folder ay mali o walang umiiral:\n{directory}",
    "error_input_file_title": "Error sa input file",
    "error_input_file": "Ang napiling input file ay mali o walang umiiral:\n{file}",
    "save_file_error_title": "Error sa pag-save ng file",
    "save_file_error": "Hindi mai-save ang file: {error}",

    "msg_pdf_processing_error": "Nabigo ang pagproseso ng PDF",
    "msg_thumbnail_error": "Error sa pag-load ng thumbnail",
    "msg_no_pdf_output": "Walang nalikhang PDF output",
    "no_pdf_pages": "Walang pahina ang PDF file",
    "unsupported_output": "Hindi suportado ang preview para sa ganitong uri ng output",
    "pdf_generated_title": "Tapos na ang paglikha",
    "pdf_generated": "Matagumpay na nalikha ang mga PDF file sa folder:\n{directory}",
    "pdf_generation_error_title": "Error sa paglikha",
    "pdf_generation_error": "Nagkaproblema habang gumagawa ng PDF. Tingnan ang log para sa detalye.",
    "critical_pdf_error_title": "Kritikal na error sa paglikha ng PDF",
    "critical_pdf_error": "May kritikal na error habang gumagawa ng PDF:\n{error}\nPakisuri ang log.",

    "settings_saved_title": "Nai-save ang settings",
    "settings_saved": "Nai-save ang settings sa file:\n{filepath}",
    "settings_save_error_title": "Error sa pag-save ng settings",
    "settings_save_error": "Hindi mai-save ang settings: {error}",
    "conversion_error_title": "Error sa conversion",
    "conversion_error": "Error sa pag-convert ng mga value mula sa GUI: {error}",
    "update_gui_error_title": "Error sa pag-update ng interface",
    "update_gui_error": "Nagkaroon ng error habang ina-update ang interface: {error}",

    "hwid_copied_to_clipboard": "Nakopya ang HWID sa clipboard",
    "computer_hwid": "HWID ng computer",
    "public_key_load_error": "Error sa pag-load ng public key: {error}",
    "invalid_license_format": "Di-wastong format ng license key: {error}",
    "activation_success": "Matagumpay na na-activate ang lisensya.",
    "activation_error": "Error sa pag-activate ng lisensya: {error}",
    "log_trial_mode_active": "Naka-activate ang trial mode",
    "log_trial_mode_inactive": "Hindi naka-activate ang trial mode",

    "init_error_title": "Error sa inisyalisa",
    "init_error": "Error sa paglikha ng directory: {error}",
    "poppler_path_info": "Impormasyon sa Poppler path",
    "ttkthemes_not_installed": "Babala: 'ttkthemes' ay hindi naka-install. Gagamitin ang default na Tkinter style.",

    # Logs (English intentionally)
    "log_configured": "Logging configured: level={0}, mode={1}, file={2}",
    "log_no_handlers": "Warning: No logging handlers configured (mode: {0}).",
    "log_critical_error": "Critical logging configuration error: {0}",
    "log_basic_config": "Basic logging configuration used due to an error.",
    "log_dir_create_error": "Critical error: Cannot create logs directory {0}: {1}",

    "error_critical_init": "CRITICAL ERROR during initialization: {0}",
    "logger_init_error": "Directory initialization error: {error}",
    "directory_created": "Created directory: {0}",
    "directory_creation_error": "Failed to create directory {0}: {1}",
    "sample_file_copied": "Sample file copied to {0}",
    "sample_file_copy_error": "Error copying sample file: {0}",
    "log_created_output_dir": "Output directory created: {0}",
    "log_cannot_create_output_dir": "Cannot create output directory {0}: {1}",

    "log_graphic_settings_error": "Failed to load graphic settings during initialization: {0}",
    "log_loading_pdf": "Loading PDF file: {0}",
    "log_loading_bitmap": "Loading bitmap file: {0}",
    "log_invalid_dpi": "Invalid DPI read ({0}). Using default {1} DPI.",
    "log_image_dimensions": "Image dimensions: {0}x{1}px, Mode: {2}, DPI: {3:.1f} -> {4:.3f}x{5:.3f}pt",
    "log_image_processing_color": "Processing image with original color mode: {0}",
    "log_unusual_color_mode": "Unusual image color mode: '{0}'. ReportLab/Pillow may not handle it correctly.",
    "log_draw_image_error": "Error during ReportLab drawImage for mode {0}: {1}",
    "log_unsupported_format": "Unsupported input file format: {0}",
    "log_input_file_not_found": "Input file not found: {0}",
    "log_load_process_error": "Error while loading or processing file {0}: {1}",
    "log_input_file_not_exists": "Input file does not exist or path is empty: '{0}'",
    "log_cannot_load_or_empty_pdf": "Failed to load input file or PDF is empty/corrupted.",
    "log_pdf_dimensions_info": "  PDF dimensions: {0:.1f}mm x {1:.1f}mm",
    "log_invalid_pdf_dimensions": "Invalid PDF page dimensions: {0}x{1} pt.",

    "log_extra_margin": "Extra margin set to {0:.3f} pt",
    "log_invalid_rows_cols": "Invalid number of rows ({0}) or columns ({1}).",
    "error_invalid_rows_cols": "Rows and columns must be positive integers.",
    "log_invalid_overlap_white_stripe": "Invalid overlap ({0}) or white stripe ({1}) values. They must be numbers.",
    "error_invalid_overlap_white_stripe": "Overlap and white stripe must be numeric values (mm).",
    "log_stripe_usage": "Set use_white_stripe={0}, white_stripe={1:.3f} mm",
    "log_effective_overlap": "Base overlap (graphics): {0:.3f} mm, White stripe: {1:.3f} mm, Effective overlap: {2:.3f} mm",
    "log_computed_dimensions": "Computed dimensions: PDF: {0:.3f}mm x {1:.3f}mm. Panel: {2:.3f}pt ({3:.3f}mm) x {4:.3f}pt ({5:.3f}mm). Core: {6:.3f}pt x {7:.3f}pt. Effective overlap: {8:.3f}mm",
    "log_invalid_dimensions": "Computed panel ({0:.3f}x{1:.3f}) or core ({2:.3f}x{3:.3f}) dimensions are invalid for overlap={4}, stripe={5}, r={6}, c={7}, W={8}mm, H={9}mm",
    "error_invalid_slice_dimensions": "Computed panel/core dimensions are invalid or negative.",

    "log_generating_slice_info": "Generating panel info: {0}",
    "log_no_slices_info_generated": "Failed to generate panels info.",
    "log_applying_rotated_order": "Applying order for 180-degree rotation: {0}",
    "log_applying_standard_order": "Applying order for 0-degree rotation (standard): {0}",
    "log_unknown_bryt_order": "Unknown panels order: '{0}'. Using default.",
    "log_final_slices_order": "  Final panels order ({0}): [{1}]",

    "log_invalid_dimensions_overlay": "Attempt to create an overlay with invalid dimensions: {0}. Skipping.",
    "log_empty_overlay": "Created an empty or nearly empty overlay PDF. Skipping.",
    "log_overlay_error": "Overlay PDF creation error: {0}",
    "log_merge_error": "Attempt to merge overlay without pages. Skipping.",
    "log_merge_page_error": "Error while merging overlay PDF: {0}",
    "log_fallback_draw_rotating_elements": "Could not get rows/cols for _draw_rotating_elements, used 1x1.",
    "log_overlay_created_for_slice": "Created stripes/marks overlay for panel {0}",
    "log_overlay_creation_failed_for_slice": "Failed to create stripes/marks overlay for {0}",
    "log_merging_rotated_overlay": "Merging ROTATED stripes/marks overlay for {0} with T={1}",
    "log_merging_nonrotated_overlay": "Merging NON-rotated stripes/marks overlay for {0}",
    "log_merging_all_codes_overlay": "Merging overlay of all codes (without rotation)",
    "log_merging_separation_lines_overlay": "Merging overlay of separation lines (without rotation)",
    "log_merging_code_overlay_for_slice": "Code overlay for {0} merged without rotation.",
    "log_merging_separation_overlay_for_slice": "Separation lines overlay for {0} merged without rotation.",

    "log_drawing_top_stripe": "[Canvas Draw] Drawing top stripe for {0}: x={1:.3f}, y={2:.3f}, w={3:.3f}, h={4:.3f}",
    "log_drawing_right_stripe": "[Canvas Draw] Drawing right stripe for {0}: x={1:.3f}, y={2:.3f}, w={3:.3f}, h={4:.3f}",
    "log_drawing_corner_stripe": "[Canvas Draw] Filling and stroking corner for {0} @ ({1:.3f}, {2:.3f})",
    "log_drawing_registration_mark": "Drawing centered cross at ({0:.3f}, {1:.3f})",
    "log_drawing_reg_lines_for_slice": "Drawing registration lines for {0} in area from ({1:.3f},{2:.3f})",
    "log_drawing_right_vertical_line": "  Drawing right vertical line: x={0:.3f}, y={1:.3f} -> {2:.3f}",
    "log_drawing_top_horizontal_line": "  Drawing top horizontal line: y={0:.3f}, x={1:.3f} -> {2:.3f}",
    "log_drawing_separation_line": "Drawing separation line (white on black): ({0}) @ ({1:.3f}, {2:.3f}), len={3:.3f}",
    "log_drawing_reg_marks_for_slice": "Drawing crosses for {0} [{1},{2}] / [{3},{4}] in area from ({5:.1f},{6:.1f})",
    "log_coord_calculation": "  Calculated centers: TL({0:.1f},{1:.1f}), TR({2:.1f},{3:.1f}), BL({4:.1f},{5:.1f}), BR({6:.1f},{7:.1f})",
    "log_drawing_tl": "    Drawing TL @ ({0:.1f}, {1:.1f})",
    "log_drawing_tr": "    Drawing TR @ ({0:.1f}, {1:.1f})",
    "log_drawing_bl": "    Drawing BL @ ({0:.1f}, {1:.1f})",
    "log_drawing_br": "    Drawing BR @ ({0:.1f}, {1:.1f})",
    "log_omitting_mark": "    Omitted {0} according to rule for position [{1},{2}]",
    "log_trial_common_sheet": "Applying TRIAL watermark text on common sheet",
    "log_trial_watermark_added": "TRIAL watermark has been added",
    "error_drawing_trial_text": "Error while drawing watermark: {error}",

    "log_drawing_separation_lines_for_page": "Drawing separation lines for page (layout={0}, total_slices={1}, slice_index={2})",
    "log_vertical_line_between_slices": "  Vertical line between panels {0}-{1} @ x={2:.1f}",
    "log_vertical_line_start": "  Vertical line start @ x={0:.1f}",
    "log_vertical_line_end": "  Vertical line end @ x={0:.1f}",
    "log_horizontal_line_between_slices": "  Horizontal line between panels {0}-{1} @ y={2:.1f}",
    "log_horizontal_line_start": "  Horizontal line start @ y={0:.1f}",
    "log_horizontal_line_end": "  Horizontal line end @ y={0:.1f}",
    "log_sep_line_start_separate": "  (Separate_files) Vertical/Horizontal line start @ {0:.1f}",
    "log_sep_line_end_separate": "  (Separate_files) Vertical/Horizontal line end @ {0:.1f}",

    "log_generate_barcode_data": "Generating barcode data: {0}",
    "log_barcode_data_shortened": "Barcode data shortened to {0} characters.",
    "log_barcode_data_error": "Barcode data generation error: {0}",
    "log_compose_barcode_payload": "Composing barcode payload ({0}): {1}",
    "log_barcode_payload_shortened": "Payload shortened to {0} characters for format {1}",
    "log_barcode_payload_error": "Error while composing payload: {0}",
    "log_unknown_anchor_fallback": "Unknown anchor '{0}', using bottom-left",
    "log_used_default_code_settings": "Used 'default' settings for code {0}/{1}.",
    "log_no_layout_key_fallback": "No layout '{0}' for {1}/{2}. Used the first available: '{3}'.",
    "log_code_settings_error": "Not found or error while retrieving code settings ({0}/{1}/{2}): {3}. Using defaults.",
    "log_drawing_barcode": "Drawing {0} at ({1:.3f}, {2:.3f}) [base ({3:.3f}, {4:.3f}) + offset ({5:.3f}, {6:.3f})], rotation: {7}°",
    "error_generate_qr_svg": "Failed to generate QR code SVG.",
    "error_invalid_scale_for_qr": "Invalid scale for QR: {0}mm",
    "error_invalid_qr_scale_factor": "Invalid scale factor for QR: {0}",
    "error_generate_barcode_svg": "Failed to generate barcode SVG.",
    "error_invalid_scale_for_barcode": "Invalid scale for Barcode: {0}x{1}mm",
    "error_invalid_barcode_scale_factor": "Invalid scale factor for Barcode: ({0:.4f}, {1:.4f})",
    "log_barcode_scale_qr": "  {0}: scale config={1:.3f}mm, SVG width={2:.3f}pt, sf={3:.4f}",
    "log_barcode_scale_code128": "  {0}: scale config=({1:.3f}mm, {2:.3f}mm), SVG size=({3:.3f}pt, {4:.3f}pt), sf=({5:.4f}, {6:.4f})",
    "log_barcode_drawing_error": "Error while drawing code '{0}': {1}",
    "log_prepared_barcode_info": "Prepared code info for {0} ({1}, anchor={2}): base absolute position ({3:.1f}, {4:.1f})",
    "log_barcode_info_prep_error": "Error preparing code data for {0}: {1}",
    "log_drawing_barcodes_count": "Drawing {0} barcodes/QR codes...",
    "log_missing_barcode_info_key": "Missing key in barcode info while drawing: {0}. Info: {1}",
    "log_error_drawing_barcode_in_draw_all": "Error while drawing code '{0}' in _draw_all_barcodes: {1}",

    "log_start_splitting_process": "--- Starting split process for: {0} ---",
    "log_split_settings": "  Settings: {0}x{1} panels, Overlap={2}mm, White stripe={3}mm (+overlap: {4})",
    "log_output_dir_info": "  Output: {0} / {1} to '{2}'",
    "log_lines_marks_barcodes_info": "  Lines: Separation={0}, Start={1}, End={2} | Marks: {3} ({4}), Codes: {5} ({6})",
    "log_bryt_order_info": "  Order: {0}, Panels rotation: {1}°",
    "log_invalid_dimensions_in_slice_info": "Invalid dimensions in slice_info for {0}: {1}x{2}",
    "log_content_transform": "Content transformation T_content for {0}: {1}",
    "log_merged_content_for_slice": "Merged content for panel {0} on new_page",
    "log_slice_reader_created": "Created complete slice (PdfReader) for panel {0}",
    "log_slice_reader_creation_error": "Error creating complete slice for panel {0}: {1}",
    "log_used_get_transform": "Used _get_transform (translation only): x={0:.1f}, y={1:.1f}",
    "log_start_split_separate_files": "--- Starting: SEPARATE FILES (Rotation handled in create_slice_reader) ---",
    "log_creating_file_for_slice": "Creating file for panel {0}: {1}",
    "log_invalid_page_size_for_slice": "Invalid page size ({0}x{1}) for {2}. Skipping.",
    "log_blank_page_creation_error": "Error creating page for {0} (size {1}x{2}): {3}. Skipping.",
    "log_transform_for_slice": "Transform T (translation only) for {0}: {1}",
    "log_merging_complete_slice": "Merging complete panel {0} with transform: {1}",
    "log_skipped_slice_merging": "Skipped merging complete panel for {0}.",
    "log_file_saved": "File saved: {0}",
    "log_file_save_error": "File save error {0}: {1}",
    "log_finished_split_separate_files": "--- Finished: SEPARATE FILES (Saved {0}/{1}) ---",
    "log_no_slices_split_horizontal": "No panels to process in split_horizontal.",
    "log_start_split_horizontal": "--- Starting: COMMON SHEET - HORIZONTAL (Rotation handled in create_slice_reader) ---",
    "log_page_dimensions": "Page dimensions: {0:.1f}mm x {1:.1f}mm ({2} panels)",
    "log_page_creation_error": "Error creating result page ({0}x{1}): {2}. Aborting.",
    "log_slice_at_position": "Panel {0} [{1}/{2}] @ ({3:.1f}, {4:.1f})",
    "log_transform_t_only": "Transform T (translation only) for {0}: {1}",
    "log_merging_complete_bryt": "Merging complete panel {0} with transform: {1}",
    "log_skipped_merging_bryt": "Skipped merging complete panel for {0}.",
    "log_file_result_saved": "Result file saved: {0}",
    "log_file_result_save_error": "Result file save error {0}: {1}",
    "log_finished_split_horizontal": "--- Finished: COMMON SHEET - HORIZONTAL ---",
    "log_no_slices_split_vertical": "No panels to process in split_vertical.",
    "log_start_split_vertical": "--- Starting: COMMON SHEET - VERTICAL (Rotation handled in create_slice_reader) ---",
    "log_finished_split_vertical": "--- Finished: COMMON SHEET - VERTICAL ---",
    "log_unknown_layout": "Unknown layout for common sheet: '{0}'.",
    "log_unknown_output_type": "Unknown output type: '{0}'.",
    "log_finished_splitting_success": "--- Finished split process for: {0} - SUCCESS ---",
    "log_finished_splitting_errors": "--- Finished split process for: {0} - ERRORS OCCURRED ---",
    "log_value_error_in_splitting": "Input data or calculation error: {0}",
    "log_finished_splitting_critical_error": "--- Finished split process for: {0} - CRITICAL ERROR ---",
    "log_unexpected_error_in_splitting": "Unexpected error while splitting file {0}: {1}",

    "log_script_mode_test": "splitter.py launched as main script (test mode).",
    "log_loaded_config": "Configuration loaded.",
    "log_error_loading_config": "Failed to load configuration: {0}",
    "log_created_example_pdf": "Created sample PDF file: {0}",
    "log_cannot_create_example_pdf": "Failed to create sample PDF: {0}",
    "log_start_test_split": "Starting test split of file: {0} to {1}",
    "log_test_split_success": "Test split completed successfully.",
    "log_test_split_errors": "Test split finished with errors.",

    "log_qr_empty_data": "Attempt to generate QR code for empty data.",
    "log_qr_generated": "QR code SVG generated for: {0}...",
    "log_qr_error": "QR code generation error for data '{0}': {1}",
    "log_barcode_empty_data": "Attempt to generate barcode for empty data.",
    "log_barcode_generated": "Barcode SVG generated for: {0}...",
    "log_barcode_error": "Barcode generation error for data '{0}': {1}",
    "log_basic_handler_configured": "Basic handler configured for logger in barcode_qr.py",
    "log_basic_handler_error": "Failed to configure basic logger handler in barcode_qr: {0}",

    "loading_profiles_from": "Loading profiles from",
    "profiles_file": "Profiles file",
    "does_not_contain_dict": "does not contain a dictionary. Creating a new one",
    "not_found_creating_new": "not found. Creating a new empty one",
    "json_profiles_read_error": "Error reading JSON profiles file",
    "file_will_be_overwritten": "File will be overwritten on save",
    "json_decode_error_in_profiles": "JSON decode error in profiles file",
    "cannot_load_profiles_file": "Cannot load profiles file",
    "unexpected_profiles_read_error": "Unexpected error reading profiles",
    "saving_profiles_to": "Saving profiles to",
    "cannot_save_profiles_file": "Cannot save profiles file",
    "profiles_save_error": "Error saving profiles to file",
    "logger_profile_saved": "Profile saved: {profile}",
    "logger_profile_not_found": "Profile not found to load: {profile}",
    "logger_profile_loaded": "Profile loaded: {profile}",
    "logger_profile_delete_not_exist": "Attempt to delete non-existent profile: {profile}",
    "logger_profile_deleted": "Profile deleted: {profile}",
    "logger_start_save_settings": "Started saving settings from GUI.",
    "logger_invalid_value": "Invalid value for '{key}'. Set to 0.0.",
    "logger_end_save_settings": "Finished saving settings from GUI.",
    "logger_conversion_error": "Value conversion error from GUI: {error}",
    "conversion_failed": "Conversion of GUI values failed",
    "logger_unexpected_save_error": "Unexpected error saving settings: {error}",
    "logger_settings_saved": "Settings saved to file: {file}",

    "public_key_load_error_log": "Public key loading error",
    "license_key_decode_error": "License key decoding error",
    "license_activation_error": "License activation error",

    "ui_created": "User interface has been created.",
    "error_tab_home": "Error creating 'Home' tab UI",
    "error_tab_settings": "Error creating 'Settings' tab UI",
    "error_tab_help": "Error creating 'Help' tab UI",
    "error_creating_license_ui": "Error creating 'License' tab UI",
    "error_loading_ui": "Error loading interface: {error}",
    "error_creating_home_ui": "Error creating 'Home' tab UI",
    "error_creating_settings_ui": "Error creating 'Settings' tab UI",
    "error_creating_help_ui": "Error creating 'Help' tab UI",
    "logger_update_gui": "Started updating GUI from configuration.",
    "logger_end_update_gui": "Finished updating GUI from configuration.",
    "logger_update_gui_error": "Unexpected error while updating GUI: {error}",
    "logger_invalid_output_dir": "Invalid or non-existent output directory: {directory}",
    "logger_invalid_input_file": "Invalid or non-existent input file: {file}",
    "logger_start_pdf": "Started PDF generation process.",
    "logger_pdf_save_error": "PDF generation aborted - failed to save current settings.",
    "logger_pdf_success": "PDF generation completed successfully.",
    "logger_pdf_exception": "Exception during main PDF generation process.",
    "icon_set_error": "Failed to set application icon: {error}",
    "accent_button_style_error": "Failed to set style for accent button: {error}",
    "logger_file_save_error": "File save error {file}: {error}",

    "thumbnail_error_log": "Thumbnail generation error",
    "output_preview_update_called": "Output preview update called",
    "output_preview_canvas_missing": "Output preview canvas missing",
    "pdf_found_in_output_dir": "PDF found in output directory",
    "preparing_thumbnail": "Preparing thumbnail",
    "thumbnail_generated_successfully": "Thumbnail generated successfully",
    "thumbnail_generation_error": "Thumbnail generation error for",
    "no_pdf_for_common_sheet": "No PDF file for common sheet preview",
    "no_pdf_for_separate_files": "No generated separate PDF files for preview",
    "cannot_load_thumbnail": "Cannot load thumbnail from",

    "missing_gui_var_created": "Created missing GUI variable for key: {key}",
    "missing_gui_structure_created": "Created missing GUI structure for: {code_type}/{output_type}/{layout}",
    "missing_gui_var_detailed_created": "Created missing GUI variable for: {code_type}/{output_type}/{layout}/{param}",

    "help_text": """
Billboard Splitter — Gabay ng gumagamit

Layunin:
Awtomatikong hinahati ng Billboard Splitter ang disenyo ng billboard sa mga panel na handang i-print.
Ipinapalagay ang sukat na 1:10. Ibigay ang mga halaga ng overlap at puting guhit ayon sa sukat na 1:1.

Mga uri ng output:
• Karaniwang sheet: lahat ng panel sa iisang PDF.
• Hiniwalay na files: bawat panel ay sariling PDF.

Dagdag na kakayahan:
• Patayo/pahalang na layout.
• 180° na pag-ikot ng panel.
• Registration marks (krus/linya).
• QR/Barcode (naaayos ang scale/offset/posisyon).
• I-save / i-load / i-delete ang mga setting bilang profile.

Pangunahing hakbang:
1) Sa 'Home', pumili ng PDF/JPG/TIFF.
2) Itakda ang rows/columns, overlap at puting guhit.
3) Piliin ang layout (patayo/pahalang) at output (sheet/hiwalay).
4) I-enable ang marks/code at iayos sa 'Settings'.
5) (Opsyonal) i-save ang profile at i-click ang 'Gumawa ng PDF'.

Pag-troubleshoot:
• Tingnan ang logs folder na 'logs'.
• Siguraduhing tama ang mga path/folder.
• Suporta: tech@printworks.pl (L–B, 8–16)
"""
}
