# lang_pt.py
"""
Ficheiro de língua: Português (pt).
Convenção: o termo de domínio "bryt" é traduzido como "painel".
"""

LANG = {
    "barcode_font_size_label": "Tamanho da fonte da descrição do código de barras [pt]:",
    # ========================== 
    #  Aplicação - Geral
    # ========================== 
    "app_title": "Billboard Splitter v1.8",
    "error": "Erro",
    "no_file": "Nenhum ficheiro",
    "language": "Idioma",
    "language_switch": "Mudar de idioma",
    "choose_language": "Escolha o idioma:",
    "apply_language": "Aplicar",
    "language_changed": "O idioma foi alterado. Algumas alterações serão visíveis após reiniciar a aplicação.",

    # ======================================== 
    #  Interface do Utilizador (GUI)
    # ======================================== 

    # --- Separadores Principais ---
    "tab_home": " Início ",
    "tab_settings": " Definições ",
    "tab_help": " Ajuda ",
    "tab_license": " Licença ",

    # --- Botões Gerais ---
    "button_browse": "Procurar...",
    "browse_folder": "Procurar pasta...",
    "button_save": "Guardar",
    "button_delete": "Eliminar",
    "button_close": "Fechar",
    "save_all_settings": "Guardar todas as definições",

    # --- Rótulos dos Campos (Separador Início) ---
    "label_rows": "Divisão vertical (linhas):",
    "label_columns": "Divisão horizontal (colunas):",
    "label_overlap": "Sobreposição [mm]:",
    "label_white_stripe": "Faixa branca [mm]:",
    "label_add_white_stripe": "Adicionar faixa branca à sobreposição efetiva",
    "label_layout": "Layout de saída:",
    "label_output_type": "Tipo de saída:",
    "label_enable_reg_marks": "Ativar marcas de registo:",
    "label_enable_codes": "Ativar códigos:",
    "label_enable_sep_lines": "Ativar linhas de separação (entre painéis)",
    "label_enable_start_line": "Ativar linha de início/topo da folha",
    "label_enable_end_line": "Ativar linha de fim/fundo da folha",
    "label_bryt_order": "Ordem dos painéis:",
    "label_slice_rotation": "Rotação dos painéis:",
    "label_create_order_folder": "Criar pasta com número de encomenda",

    # --- Secções/Molduras (Separador Início) ---
    "section_input_file": " Ficheiro de entrada ",
    "section_scale_and_dimensions": " Escala e dimensões de saída ",
    "label_original_size": "Tamanho original:",
    "label_scale_non_uniform": "Escalar não uniformemente",
    "label_scale": "Escala: 1:",
    "label_scale_x": "Escala X: 1:",
    "label_scale_y": "Escala Y: 1:",
    "label_output_dimensions": "Dimensões do arquivo de saída:",
    "label_width_cm": "Largura [cm]:",
    "label_height_cm": "Altura [cm]:",
    "section_split_settings": " Definições de divisão ",
    "section_profiles": " Perfis de definições ",
    "section_save_location": " Localização para guardar ",
    "section_input_preview": " Pré-visualização do ficheiro de entrada ",
    "section_output_preview": " Pré-visualização do ficheiro de saída ",

    # --- Valores das Opções (Combobox, Radiobutton etc.) ---
    "layout_vertical": "Vertical",
    "layout_horizontal": "Horizontal",
    "output_common_sheet": "Folha comum",
    "output_separate_files": "Ficheiros separados",
    "output_both": "Folha comum e ficheiros separados",
    "output_common": "Folha comum",
    "output_separate": "Ficheiros separados",
    "reg_mark_cross": "Cruz",
    "reg_mark_line": "Linha",
    "code_qr": "Código QR",
    "code_barcode": "Código de barras",
    "bryt_order_1": "A1-An, B1-Bn, .. Padrão, de cima",
    "bryt_order_2": "A1-An, Bn-B1, .. Cobra por linhas, de cima",
    "bryt_order_3": "A1..B1, A2..B2, .. Por colunas, de cima",
    "bryt_order_4": "A1-A2..B2-B1.. Cobra por colunas, de cima",
    "bryt_order_5": "N1-Nn, (N-1)1-(N-1)n, .. Padrão, de baixo",
    "bryt_order_6": "N1-Nn, (N-1)n-(N-1)1, .. Cobra por linhas, de baixo",
    "logging_console": "consola",
    "logging_file": "ficheiro",
    "logging_both": "ambos",

    # --- Secções/Molduras (Separador Definições) ---
    "section_processing_mode": " Operações de corte ",
    "processing_mode_ram": "RAM (na memória)",
    "processing_mode_hdd": "HDD (no disco)",
    "graphic_settings": "Definições gráficas",
    "code_settings": "Definições de QR / Código de barras",
    "logging_settings": "Definições de registo",
    "barcode_text_position_label": "Posição do texto do código de barras:",
    "barcode_text_bottom": "abaixo",
    "barcode_text_side": "ao lado",
    "barcode_text_none": "nenhum",

    # --- Rótulos dos Campos (Separador Definições - Gráficos) ---
    "extra_margin_label": "Margem à volta dos painéis [mm]:",
    "margin_top_label": "Margem superior [mm]:",
    "margin_bottom_label": "Margem inferior [mm]:",
    "margin_left_label": "Margem esquerda [mm]:",
    "margin_right_label": "Margem direita [mm]:",
    "reg_mark_width_label": "Marca de registo - Largura [mm]:",
    "reg_mark_height_label": "Marca de registo - Altura [mm]:",
    "reg_mark_white_line_width_label": "Marca de registo - Espessura da linha branca [mm]:",
    "reg_mark_black_line_width_label": "Marca de registo - Espessura da linha preta [mm]:",
    "sep_line_black_width_label": "Linha de separação - Espessura da linha preta [mm]:",
    "sep_line_white_width_label": "Linha de separação - Espessura da linha branca [mm]:",
    "slice_gap_label": "Espaço entre painéis [mm]:",
    "label_draw_slice_border": "Desenhar contorno à volta do painel (linha de corte)",

    # --- Rótulos dos Campos (Separador Definições - Códigos) ---
    "scale_label": "Tamanho [mm]:",
    "scale_x_label": "Largura X [mm]:",
    "scale_y_label": "Altura Y [mm]:",
    "offset_x_label": "Deslocamento X [mm]:",
    "offset_y_label": "Deslocamento Y [mm]:",
    "rotation_label": "Rotação (°):",
    "anchor_label": "Canto:",

    # --- Rótulos dos Campos (Separador Definições - Registo) ---
    "logging_mode_label": "Modo de registo:",
    "log_file_label": "Ficheiro de registo:",
    "logging_level_label": "Nível de registo:",

    # --- Botões / Ações (Separador Início) ---
    "button_load": "Carregar",
    "button_save_settings": "Guardar definições atuais",
    "button_generate_pdf": "Gerar PDF",
    "button_refresh_preview": "Atualizar pré-visualização",
    "button_refresh_layout": "Atualizar layout",

    # --- Licença (GUI) ---
    "hwid_frame_title": "Identificador de hardware único (HWID)",
    "copy_hwid": "Copiar HWID",
    "license_frame_title": "Ativação da licença",
    "enter_license_key": "Introduza a chave de licença:",
    "activate": "Ativar",
    "status_trial": "Modo de avaliação",
    "license_active": "Licença ativa",

    # ================================================ 
    #  Mensagens do Utilizador (Janelas, Barra de Estado)
    # ================================================ 

    # --- Perfis ---
    "msg_no_profile_name": "Sem nome",
    "msg_enter_profile_name": "Introduza um nome de perfil para guardar.",
    "msg_profile_saved": "Perfil guardado",
    "profile_saved_title": "Perfil guardado",
    "msg_profile_saved_detail": "O perfil '{0}' foi guardado.",
    "profile_saved": "Profile '{profile}' has been saved.",
    "profile_saved_and_applied": "O perfil '{profile}' foi salvo e aplicado.",
    "msg_no_profile": "Nenhum perfil",
    "warning_no_profile": "Nenhum perfil",
    "msg_select_profile": "Selecione um nome de perfil da lista para carregar.",
    "select_profile": "Selecione um nome de perfil da lista para carregar.",
    "profile_loaded_title": "Perfil carregado",
    "profile_loaded": "O perfil '{profile}' foi carregado.",
    "warning_no_profile_delete": "Nenhum perfil",
    "warning_no_profile_delete_message": "Selecione um perfil da lista para eliminar.",
    "profile_not_found": "O perfil '{profile}' não foi encontrado.",
    "profile_not_exist": "O perfil '{profile}' não existe.",
    "confirm_delete_title": "Confirmar eliminação",
    "confirm_delete_profile": "Tem a certeza de que quer eliminar o perfil '{profile}'?",
    "profile_deleted_title": "Perfil eliminado",
    "profile_deleted": "O perfil '{profile}' foi eliminado.",

    # --- Ficheiros / Diretórios ---
    "msg_no_input_file": "Nenhum ficheiro de entrada",
    "msg_unsupported_format": "Formato não suportado",
    "select_file_title": "Selecionar ficheiro de entrada",
    "supported_files": "Ficheiros suportados",
    "all_files": "Todos os ficheiros",
    "select_dir_title": "Selecionar diretório de saída",
    "select_log_dir_title": "Selecionar diretório para ficheiros de registo",
    "error_output_dir_title": "Erro no diretório de saída",
    "error_output_dir": "O diretório de saída especificado é inválido ou não existe:\n{directory}",
    "error_input_file_title": "Erro no ficheiro de entrada",
    "error_input_file": "O ficheiro de entrada especificado é inválido ou não existe:\n{file}",
    "save_file_error_title": "Erro ao guardar ficheiro",
    "save_file_error": "Falha ao guardar o ficheiro: {error}",

    # --- Processamento de PDF / Pré-visualização ---
    "msg_pdf_processing_error": "Falha ao processar o ficheiro PDF",
    "msg_thumbnail_error": "Erro ao carregar a miniatura",
    "msg_no_pdf_output": "Nenhuma saída de PDF",
    "no_pdf_pages": "Nenhuma página no ficheiro PDF",
    "unsupported_output": "Tipo de saída não suportado para pré-visualização",
    "pdf_generated_title": "Geração concluída",
    "pdf_generated": "Ficheiro(s) PDF gerado(s) com sucesso no diretório:\n{directory}",
    "pdf_generation_error_title": "Erro de geração",
    "pdf_generation_error": "Ocorreram erros ao gerar o PDF. Verifique os registos para mais informações.",
    "critical_pdf_error_title": "Erro crítico na geração de PDF",
    "critical_pdf_error": "Ocorreu um erro crítico ao gerar o PDF:\n{error}\nVerifique os registos.",

    # --- Definições ---
    "settings_saved_title": "Definições guardadas",
    "settings_saved": "As definições foram guardadas no ficheiro:\n{filepath}",
    "settings_save_error_title": "Erro ao guardar definições",
    "settings_save_error": "Falha ao guardar as definições: {error}",
    "conversion_error_title": "Erro de conversão",
    "conversion_error": "Erro ao converter valores da GUI: {error}",
    "update_gui_error_title": "Erro de atualização da GUI",
    "update_gui_error": "Ocorreu um erro ao atualizar a interface: {error}",

    # --- Licença ---
    "hwid_copied_to_clipboard": "O HWID foi copiado para a área de transferência",
    "computer_hwid": "HWID do computador",
    "public_key_load_error": "Erro ao carregar a chave pública: {error}",
    "invalid_license_format": "Formato de chave de licença inválido: {error}",
    "activation_success": "A licença foi ativada com sucesso.",
    "activation_error": "Erro na ativação da licença: {error}",
    "log_trial_mode_active": "Modo de avaliação ativo",
    "log_trial_mode_inactive": "Modo de avaliação inativo",

    # --- Inicialização ---
    "init_error_title": "Erro de inicialização",
    "init_error": "Erro ao inicializar os diretórios: {error}",
    "poppler_path_info": "Informação do caminho do Poppler",
    "ttkthemes_not_installed": "Aviso: A biblioteca ttkthemes não está instalada. A usar o estilo padrão do Tkinter.",

    # ===================================== 
    #  Registos (Mensagens do Logger)
    # ===================================== 

    # --- Registo Geral / Configuração ---
    "log_configured": "Registo configurado: nível={0}, modo={1}, ficheiro={2}",
    "log_no_handlers": "Aviso: Nenhum manipulador de registo configurado (modo: {0}).",
    "log_critical_error": "Erro crítico na configuração do registo: {0}",
    "log_basic_config": "Configuração de registo básica usada devido a um erro.",
    "log_dir_create_error": "Erro crítico: Não é possível criar o diretório de registos {0}: {1}",

    # --- Registos - Inicialização / Diretórios (`init_directories.py`) ---
    "error_critical_init": "ERRO CRÍTICO durante a inicialização: {0}",
    "logger_init_error": "Erro na inicialização de diretórios: {error}",
    "directory_created": "Diretório criado: {0}",
    "directory_creation_error": "Falha ao criar o diretório {0}: {1}",
    "sample_file_copied": "Ficheiro de exemplo copiado para {0}",
    "sample_file_copy_error": "Erro ao copiar o ficheiro de exemplo: {0}",
    "log_created_output_dir": "Diretório de saída criado: {0}",
    "log_cannot_create_output_dir": "Não é possível criar o diretório de saída {0}: {1}",

    # --- Registos - Divisor (`splitter.py`) ---
    #   Divisor - Inicialização e Carregamento
    "log_graphic_settings_error": "Falha ao carregar as definições gráficas durante a inicialização: {0}",
    "log_loading_pdf": "A carregar ficheiro PDF: {0}",
    "log_loading_bitmap": "A carregar ficheiro bitmap: {0}",
    "log_invalid_dpi": "DPI lido inválido ({0}). A usar {1} DPI por defeito.",
    "log_image_dimensions": "Dimensões da imagem: {0}x{1}px, Modo: {2}, DPI: {3:.1f} -> {4:.3f}x{5:.3f}pt",
    "log_image_processing_color": "A processar imagem com o modo de cor original: {0}",
    "log_unusual_color_mode": "Modo de cor de imagem invulgar: '{0}'. O ReportLab/Pillow pode não o manusear corretamente.",
    "log_draw_image_error": "Erro durante o ReportLab drawImage para o modo {0}: {1}",
    "log_unsupported_format": "Formato de ficheiro de entrada não suportado: {0}",
    "log_input_file_not_found": "Ficheiro de entrada não encontrado: {0}",
    "log_load_process_error": "Erro ao carregar ou processar o ficheiro {0}: {1}",
    "log_input_file_not_exists": "O ficheiro de entrada não existe ou o caminho está vazio: '{0}'",
    "log_cannot_load_or_empty_pdf": "Falha ao carregar o ficheiro de entrada ou o PDF está vazio/corrompido.",
    "log_pdf_dimensions_info": "  Dimensões do PDF: {0:.1f}mm x {1:.1f}mm",
    "log_invalid_pdf_dimensions": "Dimensões de página PDF inválidas: {0}x{1} pt.",

    #   Divisor - Cálculos de Dimensões
    "log_extra_margin": "Margem extra definida para {0:.3f} pt",
    "log_invalid_rows_cols": "Número de filas ({0}) ou colunas ({1}) inválido.",
    "error_invalid_rows_cols": "As filas e colunas devem ser números inteiros positivos.",
    "log_invalid_overlap_white_stripe": "Valores de sobreposição ({0}) ou faixa branca ({1}) inválidos. Devem ser números.",
    "error_invalid_overlap_white_stripe": "A sobreposição e a faixa branca devem ser valores numéricos (mm).",
    "log_stripe_usage": "Definir use_white_stripe={0}, white_stripe={1:.3f} mm",
    "log_effective_overlap": "Sobreposição base (gráficos): {0:.3f} mm, Faixa branca: {1:.3f} mm, Sobreposição efetiva: {2:.3f} mm",
    "log_computed_dimensions": "Dimensões calculadas: PDF: {0:.3f}mm x {1:.3f}mm. Painel: {2:.3f}pt ({3:.3f}mm) x {4:.3f}pt ({5:.3f}mm). Núcleo: {6:.3f}pt x {7:.3f}pt. Sobreposição efetiva: {8:.3f}mm",
    "log_invalid_dimensions": "As dimensões calculadas do painel ({0:.3f}x{1:.3f}) ou do núcleo ({2:.3f}x{3:.3f}) são inválidas para sobreposição={4}, faixa={5}, f={6}, c={7}, L={8}mm, A={9}mm",
    "error_invalid_slice_dimensions": "As dimensões calculadas do painel/núcleo são inválidas ou negativas.",

    #   Divisor - Geração de Informação de Painéis e Ordem
    "log_generating_slice_info": "A gerar informação do painel: {0}",
    "log_no_slices_info_generated": "Falha ao gerar a informação dos painéis.",
    "log_applying_rotated_order": "A aplicar ordem para rotação de 180 graus: {0}",
    "log_applying_standard_order": "A aplicar ordem para rotação de 0 graus (padrão): {0}",
    "log_unknown_bryt_order": "Ordem de painéis desconhecida: '{0}'. A usar o padrão.",
    "log_final_slices_order": "  Ordem final dos painéis ({0}): [{1}]",

    #   Divisor - Criação de Sobreposições e Fusão
    "log_invalid_dimensions_overlay": "Tentativa de criar uma sobreposição com dimensões inválidas: {0}. A ignorar.",
    "log_empty_overlay": "Criado um PDF de sobreposição vazio ou quase vazio. A ignorar a fusão.",
    "log_overlay_error": "Erro na criação do PDF de sobreposição: {0}",
    "log_merge_error": "Tentativa de fundir sobreposição sem páginas. A ignorar.",
    "log_merge_page_error": "Erro ao fundir o PDF de sobreposição: {0}",
    "log_fallback_draw_rotating_elements": "Não foi possível obter filas/colunas para _draw_rotating_elements, usou-se 1x1.",
    "log_overlay_created_for_slice": "Sobreposição de faixas/marcas criada para o painel {0}",
    "log_overlay_creation_failed_for_slice": "Falha ao criar a sobreposição de faixas/marcas para {0}",
    "log_merging_rotated_overlay": "A fundir sobreposição ROTACIONADA de faixas/marcas para {0} com T={1}",
    "log_merging_nonrotated_overlay": "A fundir sobreposição NÃO rotacionada de faixas/marcas para {0}",
    "log_merging_all_codes_overlay": "A fundir sobreposição de todos os códigos (sem rotação)",
    "log_merging_separation_lines_overlay": "A fundir sobreposição de linhas de separação (sem rotação)",
    "log_merging_code_overlay_for_slice": "Sobreposição de código para {0} fundida sem rotação.",
    "log_merging_separation_overlay_for_slice": "Sobreposição de linhas de separação para {0} fundida sem rotação.",

    #   Divisor - Desenho de Elementos Gráficos (Faixas, Marcas, Linhas)
    "log_drawing_top_stripe": "[Canvas Draw] A desenhar faixa superior para {0}: x={1:.3f}, y={2:.3f}, w={3:.3f}, h={4:.3f}",
    "log_drawing_right_stripe": "[Canvas Draw] A desenhar faixa direita para {0}: x={1:.3f}, y={2:.3f}, w={3:.3f}, h={4:.3f}",
    "log_drawing_corner_stripe": "[Canvas Draw] A preencher e traçar canto para {0} @ ({1:.3f}, {2:.3f})",
    "log_drawing_registration_mark": "A desenhar cruz centrada em ({0:.3f}, {1:.3f})",
    "log_drawing_reg_lines_for_slice": "A desenhar linhas de registo para {0} na área a partir de ({1:.3f},{2:.3f})",
    "log_drawing_right_vertical_line": "  A desenhar linha vertical direita: x={0:.3f}, y={1:.3f} -> {2:.3f}",
    "log_drawing_top_horizontal_line": "  A desenhar linha horizontal superior: y={0:.3f}, x={1:.3f} -> {2:.3f}",
    "log_drawing_separation_line": "A desenhar linha de separação (branco sobre preto): ({0}) @ ({1:.3f}, {2:.3f}), comp={3:.3f}",
    "log_drawing_reg_marks_for_slice": "A desenhar cruzes para {0} [{1},{2}] / [{3},{4}] na área a partir de ({5:.1f},{6:.1f})",
    "log_coord_calculation": "  Centros calculados: SE({0:.1f},{1:.1f}), SD({2:.1f},{3:.1f}), IE({4:.1f},{5:.1f}), ID({6:.1f},{7:.1f})",
    "log_drawing_tl": "    A desenhar SE @ ({0:.1f}, {1:.1f})",
    "log_drawing_tr": "    A desenhar SD @ ({0:.1f}, {1:.1f})",
    "log_drawing_bl": "    A desenhar IE @ ({0:.1f}, {1:.1f})",
    "log_drawing_br": "    A desenhar ID @ ({0:.1f}, {1:.1f})",
    "log_omitting_mark": "    {0} omitido de acordo com a regra para a posição [{1},{2}]",
    "log_trial_common_sheet": "A aplicar texto de marca de água TRIAL na folha comum",

    # Marca de água
    "log_trial_watermark_added": "A marca de água TRIAL foi adicionada",
    "error_drawing_trial_text": "Erro ao desenhar a marca de água: {error}",

    #   Divisor - Desenho de Linhas de Separação (Página Inteira)
    "log_drawing_separation_lines_for_page": "A desenhar linhas de separação para a página (layout={0}, total_divisões={1}, indice_divisão={2})",
    "log_vertical_line_between_slices": "  Linha vertical entre painéis {0}-{1} @ x={2:.1f}",
    "log_vertical_line_start": "  Início da linha vertical @ x={0:.1f}",
    "log_vertical_line_end": "  Fim da linha vertical @ x={0:.1f}",
    "log_horizontal_line_between_slices": "  Linha horizontal entre painéis {0}-{1} @ y={2:.1f}",
    "log_horizontal_line_start": "  Início da linha horizontal @ y={0:.1f}",
    "log_horizontal_line_end": "  Fim da linha horizontal @ y={0:.1f}",
    "log_sep_line_start_separate": "  (Ficheiros_separados) Início da linha vertical/horizontal @ {0:.1f}",
    "log_sep_line_end_separate": "  (Ficheiros_separados) Fim da linha vertical/horizontal @ {0:.1f}",

    #   Divisor - Geração de Códigos de Barras / QR
    "log_generate_barcode_data": "A gerar dados do código de barras: {0}",
    "log_barcode_data_shortened": "Dados do código de barras encurtados para {0} caracteres.",
    "log_barcode_data_error": "Erro na geração de dados do código de barras: {0}",
    "log_compose_barcode_payload": "A compor payload do código de barras ({0}): {1}",
    "log_barcode_payload_shortened": "Payload encurtado para {0} caracteres para o formato {1}",
    "log_barcode_payload_error": "Erro ao compor o payload: {0}",
    "log_unknown_anchor_fallback": "Âncora desconhecida '{0}', a usar canto inferior esquerdo",
    "log_used_default_code_settings": "Usadas definições 'default' para o código {0}/{1}.",
    "log_no_layout_key_fallback": "Nenhum layout '{0}' para {1}/{2}. Usado o primeiro disponível: '{3}'.",
    "log_code_settings_error": "Não encontrado ou erro ao recuperar as definições do código ({0}/{1}/{2}): {3}. A usar padrões.",
    "log_drawing_barcode": "A desenhar {0} em ({1:.3f}, {2:.3f}) [base ({3:.3f}, {4:.3f}) + deslocamento ({5:.3f}, {6:.3f})], rotação: {7}°",
    "error_generate_qr_svg": "Falha ao gerar o SVG do código QR.",
    "error_invalid_scale_for_qr": "Escala inválida para QR: {0}mm",
    "error_invalid_qr_scale_factor": "Fator de escala inválido para QR: {0}",
    "error_generate_barcode_svg": "Falha ao gerar o SVG do código de barras.",
    "error_invalid_scale_for_barcode": "Escala inválida para Código de Barras: {0}x{1}mm",
    "error_invalid_barcode_scale_factor": "Fator de escala inválido para Código de Barras: ({0:.4f}, {1:.4f})",
    "log_barcode_scale_qr": "  {0}: config de escala={1:.3f}mm, largura SVG={2:.3f}pt, fe={3:.4f}",
    "log_barcode_scale_code128": "  {0}: config de escala=({1:.3f}mm, {2:.3f}mm), tamanho SVG=({3:.3f}pt, {4:.3f}pt), fe=({5:.4f}, {6:.4f})",
    "log_barcode_drawing_error": "Erro ao desenhar o código '{0}': {1}",
    "log_prepared_barcode_info": "Informação de código preparada para {0} ({1}, âncora={2}): posição absoluta base ({3:.1f}, {4:.1f})",
    "log_barcode_info_prep_error": "Erro ao preparar os dados do código para {0}: {1}",
    "log_drawing_barcodes_count": "A desenhar {0} códigos de barras/QR...",
    "log_missing_barcode_info_key": "Chave em falta na informação do código de barras ao desenhar: {0}. Info: {1}",
    "log_error_drawing_barcode_in_draw_all": "Erro ao desenhar o código '{0}' em _draw_all_barcodes: {1}",

    #   Divisor - Processo de Divisão (métodos split_*)
    "log_start_splitting_process": "--- A iniciar processo de divisão para: {0} ---",
    "log_split_settings": "  Definições: {0}x{1} painéis, Sobreposição={2}mm, Faixa branca={3}mm (+sobreposição: {4})",
    "log_output_dir_info": "  Saída: {0} / {1} para '{2}'",
    "log_lines_marks_barcodes_info": "  Linhas: Separação={0}, Início={1}, Fim={2} | Marcas: {3} ({4}), Códigos: {5} ({6})",
    "log_bryt_order_info": "  Ordem: {0}, Rotação de painéis: {1}°",
    "log_invalid_dimensions_in_slice_info": "Dimensões inválidas em slice_info para {0}: {1}x{2}",
    "log_content_transform": "Transformação de conteúdo T_content para {0}: {1}",
    "log_merged_content_for_slice": "Conteúdo fundido para o painel {0} em nova_página",
    "log_slice_reader_created": "Divisão completa criada (PdfReader) para o painel {0}",
    "log_slice_reader_creation_error": "Erro ao criar a divisão completa para o painel {0}: {1}",
    "log_used_get_transform": "Usado _get_transform (apenas translação): x={0:.1f}, y={1:.1f}",
    "log_start_split_separate_files": "--- A iniciar: FICHEIROS SEPARADOS (Rotação tratada em create_slice_reader) ---",
    "log_creating_file_for_slice": "A criar ficheiro para o painel {0}: {1}",
    "log_invalid_page_size_for_slice": "Tamanho de página inválido ({0}x{1}) para {2}. A ignorar.",
    "log_blank_page_creation_error": "Erro ao criar a página para {0} (tamanho {1}x{2}): {3}. A ignorar.",
    "log_transform_for_slice": "Transformação T (apenas translação) para {0}: {1}",
    "log_merging_complete_slice": "A fundir painel completo {0} com transformação: {1}",
    "log_skipped_slice_merging": "Fusão do painel completo para {0} ignorada.",
    "log_file_saved": "Ficheiro guardado: {0}",
    "log_file_save_error": "Erro ao guardar o ficheiro {0}: {1}",
    "log_finished_split_separate_files": "--- Concluído: FICHEIROS SEPARADOS (Guardados {0}/{1}) ---",
    "log_no_slices_split_horizontal": "Nenhum painel para processar em split_horizontal.",
    "log_start_split_horizontal": "--- A iniciar: FOLHA COMUM - HORIZONTAL (Rotação tratada em create_slice_reader) ---",
    "log_page_dimensions": "Dimensões da página: {0:.1f}mm x {1:.1f}mm ({2} painéis)",
    "log_page_creation_error": "Erro ao criar a página de resultados ({0}x{1}): {2}. A abortar.",
    "log_slice_at_position": "Painel {0} [{1}/{2}] @ ({3:.1f}, {4:.1f})",
    "log_transform_t_only": "Transformação T (apenas translação) para {0}: {1}",
    "log_merging_complete_bryt": "A fundir painel completo {0} com transformação: {1}",
    "log_skipped_merging_bryt": "Fusão do painel completo para {0} ignorada.",
    "log_file_result_saved": "Ficheiro de resultado guardado: {0}",
    "log_file_result_save_error": "Erro ao guardar o ficheiro de resultado {0}: {1}",
    "log_finished_split_horizontal": "--- Concluído: FOLHA COMUM - HORIZONTAL ---",
    "log_no_slices_split_vertical": "Nenhum painel para processar em split_vertical.",
    "log_start_split_vertical": "--- A iniciar: FOLHA COMUM - VERTICAL (Rotação tratada em create_slice_reader) ---",
    "log_finished_split_vertical": "--- Concluído: FOLHA COMUM - VERTICAL ---",
    "log_unknown_layout": "Layout desconhecido para a folha comum: '{0}'.",
    "log_unknown_output_type": "Tipo de saída desconhecido: '{0}'.",
    "log_finished_splitting_success": "--- Processo de divisão concluído para: {0} - SUCESSO ---",
    "log_finished_splitting_errors": "--- Processo de divisão concluído para: {0} - OCORRERAM ERROS ---",
    "log_value_error_in_splitting": "Erro nos dados de entrada ou no cálculo: {0}",
    "log_finished_splitting_critical_error": "--- Processo de divisão concluído para: {0} - ERRO CRÍTICO ---",
    "log_unexpected_error_in_splitting": "Erro inesperado ao dividir o ficheiro {0}: {1}",

    #   Divisor - Modo de Teste (__main__)
    "log_script_mode_test": "splitter.py lançado como script principal (modo de teste).",
    "log_loaded_config": "Configuração carregada.",
    "log_error_loading_config": "Falha ao carregar a configuração: {0}",
    "log_created_example_pdf": "Ficheiro PDF de exemplo criado: {0}",
    "log_cannot_create_example_pdf": "Falha ao criar o PDF de exemplo: {0}",
    "log_start_test_split": "A iniciar divisão de teste do ficheiro: {0} para {1}",
    "log_test_split_success": "A divisão de teste foi concluída com sucesso.",
    "log_test_split_errors": "A divisão de teste terminou com erros.",

    # --- Registos - QR/Código de Barras (`barcode_qr.py`) ---
    "log_qr_empty_data": "Tentativa de gerar código QR para dados vazios.",
    "log_qr_generated": "SVG de código QR gerado para: {0}...",
    "log_qr_error": "Erro na geração do código QR para os dados '{0}': {1}",
    "log_barcode_empty_data": "Tentativa de gerar código de barras para dados vazios.",
    "log_barcode_generated": "SVG de código de barras gerado para: {0}...",
    "log_barcode_error": "Erro na geração do código de barras para os dados '{0}': {1}",
    "log_basic_handler_configured": "Manipulador básico configurado para o logger em barcode_qr.py",
    "log_basic_handler_error": "Falha ao configurar o manipulador de logger básico em barcode_qr: {0}",

    # --- Registos - Configuração/Perfis (`main_config_manager.py`) ---
    "loading_profiles_from": "A carregar perfis de",
    "profiles_file": "Ficheiro de perfis",
    "does_not_contain_dict": "não contém um dicionário. A criar um novo",
    "not_found_creating_new": "não encontrado. A criar um novo vazio",
    "json_profiles_read_error": "Erro ao ler o ficheiro JSON de perfis",
    "file_will_be_overwritten": "O ficheiro será sobrescrito ao guardar",
    "json_decode_error_in_profiles": "Erro de descodificação JSON no ficheiro de perfis",
    "cannot_load_profiles_file": "Não é possível carregar o ficheiro de perfis",
    "unexpected_profiles_read_error": "Erro inesperado ao ler os perfis",
    "saving_profiles_to": "A guardar perfis em",
    "cannot_save_profiles_file": "Não é possível guardar o ficheiro de perfis",
    "profiles_save_error": "Erro ao guardar os perfis no ficheiro",
    "logger_profile_saved": "Perfil guardado: {profile}",
    "logger_profile_not_found": "Perfil não encontrado para carregar: {profile}",
    "logger_profile_loaded": "Perfil carregado: {profile}",
    "logger_profile_delete_not_exist": "Tentativa de eliminar um perfil inexistente: {profile}",
    "logger_profile_deleted": "Perfil eliminado: {profile}",
    "logger_start_save_settings": "Iniciado o processo de guardar definições da GUI.",
    "logger_invalid_value": "Valor inválido para '{key}'. Definido para 0.0.",
    "logger_end_save_settings": "Concluído o processo de guardar definições da GUI.",
    "logger_conversion_error": "Erro de conversão de valor da GUI: {error}",
    "conversion_failed": "A conversão de valores da GUI falhou",
    "logger_unexpected_save_error": "Erro inesperado ao guardar as definições: {error}",
    "logger_settings_saved": "Definições guardadas no ficheiro: {file}",

    # --- Registos - Licenciamento (`main_license.py`) ---
    "public_key_load_error_log": "Erro ao carregar a chave pública",
    "license_key_decode_error": "Erro ao descodificar a chave de licença",
    "license_activation_error": "Erro de ativação da licença",

    # --- Registos - Módulo Principal (`main.py`) ---
    "ui_created": "A interface do utilizador foi criada.",
    "error_tab_home": "Erro ao criar a UI do separador 'Início'",
    "error_tab_settings": "Erro ao criar a UI do separador 'Definições'",
    "error_tab_help": "Erro ao criar a UI do separador 'Ajuda'",
    "error_creating_license_ui": "Erro ao criar a UI do separador 'Licença'",
    "error_loading_ui": "Erro ao carregar a interface: {error}",
    "error_creating_home_ui": "Erro ao criar a UI do separador 'Início'",
    "error_creating_settings_ui": "Erro ao criar a UI do separador 'Definições'",
    "error_creating_help_ui": "Erro ao criar a UI do separador 'Ajuda'",
    "logger_update_gui": "Iniciada a atualização da GUI a partir da configuração.",
    "logger_end_update_gui": "Concluída a atualização da GUI a partir da configuração.",
    "logger_update_gui_error": "Erro inesperado ao atualizar a GUI: {error}",
    "logger_invalid_output_dir": "Diretório de saída inválido ou inexistente: {directory}",
    "logger_invalid_input_file": "Ficheiro de entrada inválido ou inexistente: {file}",
    "logger_start_pdf": "Iniciado o processo de geração de PDF.",
    "logger_pdf_save_error": "Geração de PDF abortada - falha ao guardar as definições atuais.",
    "logger_pdf_success": "Geração de PDF concluída com sucesso.",
    "logger_pdf_exception": "Exceção durante o processo principal de geração de PDF.",
    "icon_set_error": "Falha ao definir o ícone da aplicação: {error}",
    "accent_button_style_error": "Falha ao definir o estilo para o botão de destaque: {error}",
    "logger_file_save_error": "Erro ao guardar o ficheiro {file}: {error}",

    #   Registos - Pré-visualização (`main.py` - update_preview, update_output_preview)
    "thumbnail_error_log": "Erro na geração de miniaturas",
    "output_preview_update_called": "Chamada de atualização da pré-visualização de saída",
    "output_preview_canvas_missing": "Falta a tela de pré-visualização de saída",
    "pdf_found_in_output_dir": "PDF encontrado no diretório de saída",
    "preparing_thumbnail": "A preparar miniatura",
    "thumbnail_generated_successfully": "Miniatura gerada com sucesso",
    "thumbnail_generation_error": "Erro na geração de miniaturas para",
    "no_pdf_for_common_sheet": "Nenhum ficheiro PDF para pré-visualização da folha comum",
    "no_pdf_for_separate_files": "Nenhum ficheiro PDF separado gerado para pré-visualização",
    "cannot_load_thumbnail": "Não é possível carregar a miniatura de",

    #   Registos - Desenvolvedor / Internos da GUI (`main.py`)
    "missing_gui_var_created": "Variável de GUI em falta criada para a chave: {key}",
    "missing_gui_structure_created": "Estrutura de GUI em falta criada para: {code_type}/{output_type}/{layout}",
    "missing_gui_var_detailed_created": "Variável de GUI em falta criada para: {code_type}/{output_type}/{layout}/{param}",

    # Chaves adicionais para main_ui_help.py
    "help_text": "\n    Billboard Splitter – Guia do Utilizador\n\n\n    Objetivo do programa:\n\n    O Billboard Splitter é usado para cortar automaticamente projetos de outdoors em painéis prontos para impressão.\n    O programa está preparado para trabalhar com ficheiros desenhados à escala 1:10.\n\n    Os valores nas secções: Sobreposição, Faixa branca, Definições são introduzidos à escala 1:1.\n    O programa permite organizar os painéis cortados em folhas PDF, dependendo do layout selecionado:\n\n    • Folha comum: Todos os painéis são colocados num único documento.\n\n    • Ficheiros separados: Cada painel é guardado num ficheiro PDF separado.\n\n\n    Adicionalmente, o programa permite:\n\n    • Escolher um layout – vertical ou horizontal (correspondentemente: no layout vertical as linhas de separação aparecem em cima e em baixo,\n      e no layout horizontal à esquerda e à direita).\n\n    • Rodar os painéis 180° (invertendo todo o projeto).\n\n    • Adicionar marcas de registo (p. ex., cruzes ou linhas) para facilitar o posicionamento preciso durante a colagem.\n\n    • Adicionar códigos QR ou códigos de barras – gerados com base nos dados de entrada para ajudar\n      a identificar os painéis individuais.\n\n    • Guardar as definições como perfis que podem ser carregados, modificados e eliminados, facilitando\n      a alternância entre diferentes configurações de projetos.\n\n\n    Passos principais para usar o programa:\n\n\n    1. Escolher ficheiro de entrada:\n\n    • No separador 'Início', escolha um ficheiro PDF, JPG ou TIFF que contenha o design do outdoor.\n\n    • Se não definir o seu próprio caminho, o programa define um ficheiro de exemplo por defeito.\n\n\n    2. Definições de corte:\n\n    • Especifique o número de filas e colunas em que o projeto será dividido.\n\n    • Defina o tamanho da sobreposição.\n\n    • Opcionalmente, especifique a largura da faixa branca que será adicionada à sobreposição efetiva.\n\n\n    3. Selecionar layout de saída:\n\n    • Vertical: Todos os painéis serão dispostos verticalmente numa folha PDF.\n\n    • Horizontal: Todos os painéis serão dispostos horizontalmente numa folha PDF.\n\n\n    4. Selecionar tipo de saída:\n\n    • Folha comum: Todos os painéis serão dispostos numa única folha PDF comum.\n\n    • Ficheiros separados: Cada painel será guardado num ficheiro PDF separado.\n\n    • No separador 'Início', pode ativar e configurar as marcas de registo – escolhendo entre cruz e linha.\n\n    • Opcionalmente, ative um código QR ou um código de barras que será gerado a partir dos dados do projeto.\n\n    • Os parâmetros do código (escala, deslocamento, rotação, posição) podem ser ajustados finamente no separador 'Definições'.\n\n\n    5. Gestão de definições:\n\n    • No separador 'Definições', pode modificar com precisão os parâmetros gráficos (margens, espessuras de linha, espaçamentos) e\n      as definições do código.\n\n    • Guarde as definições atuais como um perfil para poder carregá-las ou modificá-las facilmente mais tarde.\n\n    • Os perfis de definições (guardados no ficheiro profiles.json) permitem alternar rapidamente entre diferentes\n\n      configurações de projetos.\n\n\n    6. Geração de PDF:\n\n    • Após configurar todos os parâmetros, clique em 'Gerar PDF'.\n\n    • Os ficheiros resultantes serão guardados no diretório 'output' ou noutro indicado, e os registos (com rotação diária) no diretório 'logs'\n      ou noutro indicado.\n\n\n    Se surgirem problemas:\n\n    • Verifique os registos localizados na pasta 'logs'. Todos os dias é gerado um ficheiro de registo separado com a data no nome.\n\n    • Certifique-se de que todas as pastas necessárias estão configuradas.\n\n    • Suporte técnico: tech@printworks.pl (dias úteis, 8-16)\n\n    \"\""
}