# Generated by Django 4.2.27 on 2025-12-27 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyOEE",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("availability", models.FloatField(default=0.0)),
                ("performance", models.FloatField(default=0.0)),
                ("quality", models.FloatField(default=0.0)),
                ("oee", models.FloatField(default=0.0)),
                ("total_time_min", models.IntegerField(default=1440)),
                ("run_time_min", models.IntegerField(default=0)),
                ("total_parts", models.IntegerField(default=0)),
                ("good_parts", models.IntegerField(default=0)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_oee",
                        to="registry.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("machine", "date")},
            },
        ),
    ]
