# Generated by Django 5.2.10 on 2026-01-19 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oee", "0003_downtimeevent"),
        ("registry", "0003_shift"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("task_name", models.CharField(max_length=255)),
                ("print_area", models.FloatField(default=0.0, help_text="m2")),
                ("print_length", models.FloatField(default=0.0, help_text="m")),
                ("time_consuming_h", models.FloatField(default=0.0)),
                ("ink_consumption_ml", models.FloatField(default=0.0)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("finish_total_ratio", models.CharField(blank=True, max_length=50)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_jobs",
                        to="registry.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("machine", "timestamp", "task_name")},
            },
        ),
    ]
