#!/usr/bin/env python
import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

# Add project root to allow sibling imports
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))
sys.path.insert(0, str(project_root / 'scripts'))

from feniks.infra.logging import log
from feniks.core.models.types import Chunk, ApiEndpoint
from feniks_cli import load_ir_chunks

def normalize_path(url: str) -> str:
    """Converts a URL with dynamic parts into an OpenAPI path format."""
    # Replace AngularJS-style :param with {param}
    url = re.sub(r':([a-zA-Z0-9_]+)', r'{\1}', url)
    # Replace common dynamic parts captured as ${{...}} with {param}
    url = re.sub(r'\$\({{.*?}}\}', '{param}', url)
    return url

def get_path_params(path: str) -> list[str]:
    """Extracts parameter names from a normalized path."""
    return re.findall(r'\{([a-zA-Z0-9_]+)\}', path)

def build_openapi_spec(chunks: list[Chunk]) -> dict:
    """Builds an OpenAPI specification from a list of IR chunks."""
    
    paths = defaultdict(dict)

    for chunk in chunks:
        for endpoint in chunk.api_endpoints:
            if not endpoint.url:
                continue

            path_url = normalize_path(endpoint.url)
            method = endpoint.method.lower()

            # Operation Object
            operation = {
                "summary": f"Discovered in: {chunk.chunk_name}",
                "description": f"Found in `{chunk.file_path}` at lines {chunk.start_line}-{chunk.end_line}.\n\n```\n{chunk.text}\n```",
                "tags": [chunk.module or "uncategorized"],
                "parameters": [],
                "responses": {
                    "200": {"description": "Successful response"},
                    "default": {"description": "Error response"}
                }
            }

            # Path parameters
            path_params = get_path_params(path_url)
            for param_name in path_params:
                operation["parameters"].append({
                    "name": param_name,
                    "in": "path",
                    "required": True,
                    "schema": {"type": "string"}
                })

            # Query parameters
            for param_name in endpoint.paramKeys:
                if param_name not in path_params:
                    operation["parameters"].append({
                        "name": param_name,
                        "in": "query",
                        "schema": {"type": "string"}
                    })

            # Request Body
            if endpoint.dataKeys:
                operation["requestBody"] = {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {key: {"type": "string"} for key in endpoint.dataKeys}
                            }
                        }
                    }
                }
            
            paths[path_url][method] = operation

    spec = {
        "openapi": "3.0.3",
        "info": {
            "title": "Feniks Auto-Generated API",
            "version": "1.0.0",
            "description": "This API specification was automatically generated by the Feniks tool by analyzing the AngularJS source code."
        },
        "paths": paths
    }
    return spec

def main():
    parser = argparse.ArgumentParser(description="Generate an OpenAPI specification from Feniks IR.")
    parser.add_argument("--in", dest="input_path", type=Path, required=True, help="Path to the Feniks IR JSONL file (e.g., runs/latest/chunks.ir.jsonl).")
    parser.add_argument("--out", dest="output_path", type=Path, required=True, help="Path to write the OpenAPI JSON file.")
    args = parser.parse_args()

    log.info(f"Loading IR chunks from: {args.input_path}")
    if not args.input_path.exists():
        log.error(f"Input file not found: {args.input_path}")
        sys.exit(1)
        
    chunks = load_ir_chunks(args.input_path)
    
    log.info(f"Generating OpenAPI specification from {len(chunks)} chunks...")
    openapi_spec = build_openapi_spec(chunks)
    
    log.info(f"Writing OpenAPI specification to: {args.output_path}")
    args.output_path.parent.mkdir(parents=True, exist_ok=True)
    with args.output_path.open("w", encoding="utf-8") as f:
        json.dump(openapi_spec, f, indent=2, ensure_ascii=False)
        
    log.info("OpenAPI specification generated successfully.")

if __name__ == "__main__":
    main()