version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 99
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"

  - package-ecosystem: "pip"
    directory: "/apps/memory_api"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 99
    groups:
      app-security:
        patterns:
          - "*"
        update-types:
          - "security"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
