# Generated by Django 5.2.9 on 2025-12-27 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oee", "0001_initial"),
        ("registry", "0003_shift"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftOEE",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("availability", models.FloatField(default=0.0)),
                ("performance", models.FloatField(default=0.0)),
                ("quality", models.FloatField(default=0.0)),
                ("oee", models.FloatField(default=0.0)),
                ("total_time_min", models.IntegerField(default=480)),
                ("run_time_min", models.IntegerField(default=0)),
                ("total_parts", models.IntegerField(default=0)),
                ("good_parts", models.IntegerField(default=0)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_oee",
                        to="registry.machine",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="registry.shift"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "shift__start_time"],
                "unique_together": {("machine", "shift", "date")},
            },
        ),
    ]
