version: "3"
services:

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./proxy/data:/data
      - ./letsencrypt:/etc/letsencrypt
  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo-import/mongo-backup:/home/mongo-backup  # Kopie zapasowe bazy danych
      - ./docker/mongodump:/dump

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: M0nG0f69b54
      MONGO_INITDB_DATABASE: admin
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    container_name: mysql
    image: mariadb:10.5.13
    restart: always
    environment:
      SERVICE_IGNORE: 'true'
      MYSQL_ROOT_PASSWORD: dupa123
      MYSQL_DATABASE: printworks
    command: --max-allowed-packet=1073741824 --general-log=true --general-log-file=query.log
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/dump:/tmp/dump

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    depends_on:
      - proxy
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: dupa123
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpadmin.rule=Host(`myadmin.localtest.me`)
      - traefik.http.routers.phpadmin.entrypoints=http
      - traefik.http.services.phpadmin.loadbalancer.server.port=80


  authapp:
    container_name: authapp
    image: ds-authapp
    build:
      context: ./authApp
      dockerfile: ./Dockerfile
    links:
      - mongo
    depends_on:
      - proxy
      - mongo
    env_file:
      - ./authApp/.env
    ports:
      - 2600:2600
    labels:
      - traefik.enable=true
      - traefik.http.routers.authapp.rule=Host(`authapp.localtest.me`)
      - traefik.http.routers.authapp.entrypoints=http
      - traefik.http.services.authapp.loadbalancer.server.port=2600

  backend:
    container_name: backend
    image: ds-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
      - mysql
    volumes:
      - ./data:/var/www/app/data
    env_file:
      - ./backend/.env
    labels:
      - traefik.enable=true
      - traefik.http.services.backend.loadbalancer.server.port=80
      - traefik.http.routers.backend.entrypoints=http
      - traefik.http.routers.backend.rule=(Host(`localtest.me`) && PathPrefix(`/api`))
      - traefik.http.routers.backend.middlewares=backend
      - traefik.http.middlewares.backend.stripprefix.prefixes=/api
      - traefik.http.middlewares.backend.stripprefix.forceSlash=false
  manager:
    container_name: manager
    image: ds-manager
    build:
      context: ./manager
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
    env_file:
      - ./manager/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.manager.rule=Host(`manager.localtest.me`)
      - traefik.http.routers.manager.entrypoints=http
      - traefik.http.services.manager.loadbalancer.server.port=80

  static:
    container_name: static
    image: ds-static
    build:
      context: ./static
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
    volumes:
      - ./data/:/var/www/app/static
    env_file:
      - ./static/.env
    labels:
      - traefik.enable=true
      - traefik.http.services.static.loadbalancer.server.port=80
      - traefik.http.routers.static.entrypoints=http
      - traefik.http.routers.static.rule=(Host(`localtest.me`) && PathPrefix(`/static`))
      - traefik.http.routers.static.middlewares=static
      - traefik.http.middlewares.static.stripprefix.prefixes=/static
      - traefik.http.middlewares.static.stripprefix.forceSlash=false

  frontend:
    container_name: frontend
    image: ds-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
    env_file:
      - ./frontend/.env
    volumes:
      - ./data/templates/default:/app/.default
      - ./data/35/routing:/app/routing
      - ./frontend/.docker_nginx.conf:/etc/nginx/nginx.conf.tmp
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=(Host(`localtest.me`) && PathPrefix(`/`))
      - traefik.http.routers.frontend.entrypoints=http
      - traefik.http.services.frontend.loadbalancer.server.port=80

  editor-backend:
    container_name: editor-backend
    image: ds-editor-backend
    build:
      context: ./editor-backend
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
      - mongo
    env_file:
      - ./editor-backend/.env

    labels:
      - traefik.enable=true
      - traefik.http.routers.editapi.entrypoints=http
      - traefik.http.services.editapi.loadbalancer.server.port=80
      - traefik.http.routers.editapi.rule=(Host(`editor.localtest.me`) && PathPrefix(`/api`))
      - traefik.http.routers.editapi.middlewares=editapi
      - traefik.http.middlewares.editapi.stripprefix.prefixes=/api
      - traefik.http.middlewares.editapi.stripprefix.forceSlash=false

  editor:
    container_name: editor
    image: ds-editor
    build:
      context: ./editor
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
    env_file:
      - ./editor/.env

    labels:
      - traefik.enable=true
      - traefik.http.routers.editor.rule=Host(`editor.localtest.me`)
      - traefik.http.routers.editor.entrypoints=http
      - traefik.http.services.editor.loadbalancer.server.port=80
  rendertron:
    container_name: rendertron
    image: rendertron
    build:
      context: ./rendertron
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "3003:3000"  # Expose Rendertron's port; adjust if necessary
    environment:
      RENDERTRON_PORT: 3000
    depends_on:
      - proxy  # Ensure that the proxy is running if you plan to access Rendertron through it
    networks:
      default: