version: "3"
services:

  # director
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./proxy/data:/data
      - ./letsencrypt:/etc/letsencrypt

  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo-import/mongo-backup:/home/mongo-backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: M0nG0f69b54
      MONGO_INITDB_DATABASE: admin
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    links:
      - mongo
    depends_on:
      - proxy
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: M0nG0f69b54
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_SERVER: mongo

  mysql:
    container_name: mysql
    image: mariadb:10.5.13
    restart: always
    environment:
      SERVICE_IGNORE: 'true'
      MYSQL_ROOT_PASSWORD: dupa123
      MYSQL_DATABASE: printworks
    command: --max-allowed-packet=1073741824 --general-log=true --general-log-file=query.log
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/dump:/tmp/dump

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    depends_on:
      - proxy
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: dupa123
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M

  sql-migrate:
    container_name: sql-migrate
    image: ds-sqlmigrate
    build:
      context: .
      dockerfile: ./docker/sql-migrate/Dockerfile
    depends_on:
      - mysql
    env_file:
      - ./docker/sql-migrate/.env
    restart: on-failure
    volumes:
      - ./docker/sql-migrate/migrations:/app

  get-data:
    container_name: get-data
    image: kacian/base:alpine
    restart: "no"
    command: "bash -c '[ -d /data/25 ] || (curl https://printworks.pl/static/localtest_data.tar.gz -o - |tar zx |chown -R 33.33 /data)'"
    volumes:
      - ./data:/data

  static:
    container_name: static
    image: ds-static
    build:
      context: ./static
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
    volumes:
      - ./static/data:/var/www/app
    env_file:
      - ./static/.env

  authapp:
    container_name: authapp
    image: ds-authapp
    build:
      context: ./authApp
      dockerfile: ./Dockerfile
    links:
      - mongo
    depends_on:
      - proxy
      - mongo
    env_file:
      - ./authApp/.env
    ports:
      - 2600:2600

  backend:
    container_name: backend
    image: ds-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
      - mysql
    volumes:
      - ./data:/var/www/app/data
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    image: ds-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
    env_file:
      - ./frontend/.env
    volumes:
      - ./data/templates/default:/app/.default
      - ./data/35/routing:/app/routing

  editor-backend:
    container_name: editor-backend
    image: ds-editor-backend
    build:
      context: ./editor-backend
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
      - mongo
    env_file:
      - ./editor-backend/.env

  editor:
    container_name: editor
    image: ds-editor
    build:
      context: ./editor
      dockerfile: ./Dockerfile
    depends_on:
      - proxy
    env_file:
      - ./editor/.env

  manager:
    container_name: manager
    image: ds-manager-dev
    build:
      context: ./manager
      dockerfile: ./Dockerfile-dev
    depends_on:
      - proxy
    env_file:
      - ./manager/.env
    volumes:
      - ./manager:/app
    command: 'npm run dev'
