<?php


use Phinx\Migration\AbstractMigration;

class CountriesTable extends AbstractMigration
{

    public function up()
    {
        $this->query('create table dp_countries(
    code char(2) not null,
    areaCode char(10) null,
    name_pl varchar(255) not null,
    name_en varchar(255) null,
    disabled int not null default 0,
    unique key(code,areaCode)
    )
    charset = utf8;');
        $this->query("insert into dp_countries (code,areaCode,name_pl,name_en) values('AF','','Afganistan','Afghanistan')
,('AL','355','Albania','Albania')
,('DZ','213','Algieria','Algeria')
,('AD','376','Andora','Andorra')
,('AO','244','Angola','Angola')
,('AI','','Anguilla','Anguilla')
,('AQ','','Antarktyka','Antarctica')
,('AG','','Antigua i Barbuda','Antigua and Barbuda')
,('SA','','Arabia Saudyjska','Saudi Arabia')
,('AR','','Argentyna','Argentina')
,('AM','374','Armenia','Armenia')
,('AW','','Aruba','Aruba')
,('AU','','Australia','Australia')
,('AT','43','Austria','Austria')
,('AZ','','Azerbejdżan','Azerbaijan')
,('BS','','Bahamy','Bahamas')
,('BH','','Bahrajn','Bahrain')
,('BD','','Bangladesz','Bangladesh')
,('BB','','Barbados','Barbados')
,('BE','32','Belgia','Belgium')
,('BZ','','Belize','Belize')
,('BJ','','Benin','Benin')
,('BM','','Bermudy','Bermuda')
,('BT','','Bhutan','Bhutan')
,('BY','375','Białoruś','Belarus')
,('BO','','Boliwia','Bolivia, Plurinational State of')
,('BQ','','Bonaire, Sint Eustatius i Saba','Bonaire, Sint Eustatius and Saba')
,('BA','387','Bośnia i Hercegowina','Bosnia and Herzegovina')
,('BW','','Botswana','Botswana')
,('BR','','Brazylia','Brazil')
,('BN','','Brunei','Brunei Darussalam')
,('IO','','Brytyjskie Terytorium Oceanu Indyjskiego','British Indian Ocean Territory')
,('VG','','Brytyjskie Wyspy Dziewicze','Virgin Islands, British')
,('BG','359','Bułgaria','Bulgaria')
,('BF','','Burkina Faso','Burkina Faso')
,('BI','','Burundi','Burundi')
,('CL','','Chile','Chile')
,('CN','','Chiny','China')
,('HR','385','Chorwacja','Croatia')
,('CW','','Curaçao','Curaçao')
,('CY','357','Cypr','Cyprus')
,('TD','','Czad','Chad')
,('ME','','Czarnogóra','Montenegro')
,('CZ','420','Czechy','Czech Republic')
,('UM','','Dalekie Wyspy Mniejsze Stanów Zjednoczonych','United States Minor Outlying Islands')
,('DK','45','Dania','Denmark')
,('CD','','Demokratyczna Republika Konga','Congo, the Democratic Republic of the')
,('DM','','Dominika','Dominica')
,('DO','','Dominikana','Dominican Republic')
,('DJ','','Dżibuti','Djibouti')
,('EG','','Egipt','Egypt')
,('EC','','Ekwador','Ecuador')
,('ER','','Erytrea','Eritrea')
,('EE','372','Estonia','Estonia')
,('ET','','Etiopia','Ethiopia')
,('FK','500','Falklandy','Falkland Islands (Malvinas)')
,('FJ','','Fidżi','Fiji')
,('PH','','Filipiny','Philippines')
,('FI','358','Finlandia','Finland')
,('FR','33','Francja','France')
,('TF','','Francuskie Terytoria Południowe i Antarktyczne','French Southern Territories')
,('GA','','Gabon','Gabon')
,('GM','','Gambia','Gambia')
,('GS','','Georgia Południowa i Sandwich Południowy','South Georgia and the South Sandwich Islands')
,('GH','','Ghana','Ghana')
,('GI','','Gibraltar','Gibraltar')
,('GR','30','Grecja','Greece')
,('GD','','Grenada','Grenada')
,('GL','','Grenlandia','Greenland')
,('GE','995','Gruzja','Georgia')
,('GU','','Guam','Guam')
,('GG','','Guernsey','Guernsey')
,('GF','','Gujana Francuska','French Guiana')
,('GY','','Gujana','Guyana')
,('GP','','Gwadelupa','Guadeloupe')
,('GT','','Gwatemala','Guatemala')
,('GW','','Gwinea Bissau','Guinea-Bissau')
,('GQ','','Gwinea Równikowa','Equatorial Guinea')
,('GN','','Gwinea','Guinea')
,('HT','','Haiti','Haiti')
,('ES','355','Hiszpania','Spain')
,('NL','31','Holandia','Netherlands')
,('HN','','Honduras','Honduras')
,('HK','','Hongkong','Hong Kong')
,('IN','','Indie','India')
,('ID','','Indonezja','Indonesia')
,('IQ','','Irak','Iraq')
,('IR','','Iran','Iran, Islamic Republic of')
,('IE','353','Irlandia','Ireland')
,('IS','354','Islandia','Iceland')
,('IL','','Izrael','Israel')
,('JM','','Jamajka','Jamaica')
,('JP','','Japonia','Japan')
,('YE','','Jemen','Yemen')
,('JE','44-1534','Jersey','Jersey')
,('JO','','Jordania','Jordan')
,('KY','','Kajmany','Cayman Islands')
,('KH','','Kambodża','Cambodia')
,('CM','','Kamerun','Cameroon')
,('CA','','Kanada','Canada')
,('QA','','Katar','Qatar')
,('KZ','','Kazachstan','Kazakhstan')
,('KE','','Kenia','Kenya')
,('KG','','Kirgistan','Kyrgyzstan')
,('KI','','Kiribati','Kiribati')
,('CO','','Kolumbia','Colombia')
,('KM','','Komory','Comoros')
,('CG','','Kongo','Congo')
,('KR','','Korea Południowa','Korea, Republic of')
,('KP','','Korea Północna','Korea, Democratic People\'s Republic of')
,('CR','','Kostaryka','Costa Rica')
,('CU','','Kuba','Cuba')
,('KW','','Kuwejt','Kuwait')
,('LA','','Laos','Lao People\'s Democratic Republic')
,('LS','','Lesotho','Lesotho')
,('LB','','Liban','Lebanon')
,('LR','','Liberia','Liberia')
,('LY','','Libia','Libyan Arab Jamahiriya')
,('LI','423','Liechtenstein','Liechtenstein')
,('LT','370','Litwa','Lithuania')
,('LU','352','Luksemburg','Luxembourg')
,('LV','371','Łotwa','Latvia')
,('MK','','Macedonia','Macedonia, the former Yugoslav Republic of')
,('MG','','Madagaskar','Madagascar')
,('YT','','Majotta','Mayotte')
,('MO','','Makau','Macao')
,('MW','','Malawi','Malawi')
,('MV','','Malediwy','Maldives')
,('MY','','Malezja','Malaysia')
,('ML','','Mali','Mali')
,('MT','356','Malta','Malta')
,('MP','','Mariany Północne','Northern Mariana Islands')
,('MA','','Maroko','Morocco')
,('MQ','','Martynika','Martinique')
,('MR','','Mauretania','Mauritania')
,('MU','','Mauritius','Mauritius')
,('MX','','Meksyk','Mexico')
,('FM','','Mikronezja','Micronesia, Federated States of')
,('MM','','Mjanma','Myanmar')
,('MD','','Mołdawia','Moldova, Republic of')
,('MC','377','Monako','Monaco')
,('MN','976','Mongolia','Mongolia')
,('MS','','Montserrat','Montserrat')
,('MZ','','Mozambik','Mozambique')
,('NA','','Namibia','Namibia')
,('NR','','Nauru','Nauru')
,('NP','','Nepal','Nepal')
,('DE','49','Niemcy','Germany')
,('NE','','Niger','Niger')
,('NG','','Nigeria','Nigeria')
,('NI','','Nikaragua','Nicaragua')
,('NU','','Niue','Niue')
,('NF','','Norfolk','Norfolk Island')
,('NO','47','Norwegia','Norway')
,('NC','','Nowa Kaledonia','New Caledonia')
,('NZ','','Nowa Zelandia','New Zealand')
,('OM','','Oman','Oman')
,('PK','','Pakistan','Pakistan')
,('PW','','Palau','Palau')
,('PS','','Palestyna','Palestinian Territory, Occupied')
,('PA','','Panama','Panama')
,('PG','','Papua-Nowa Gwinea','Papua New Guinea')
,('PY','','Paragwaj','Paraguay')
,('PE','','Peru','Peru')
,('PN','','Pitcairn','Pitcairn')
,('PF','','Polinezja Francuska','French Polynesia')
,('PL','48','Polska','Poland')
,('PR','','Portoryko','Puerto Rico')
,('PT','351','Portugalia','Portugal')
,('ZA','','Republika Południowej Afryki','South Africa')
,('CF','','Republika Środkowoafrykańska','Central African Republic')
,('CV','','Republika Zielonego Przylądka','Cape Verde')
,('RE','','Reunion','Réunion')
,('RU','7','Rosja','Russian Federation')
,('RO','40','Rumunia','Romania')
,('RW','','Rwanda','Rwanda')
,('EH','','Sahara Zachodnia','Western Sahara')
,('KN','','Saint Kitts i Nevis','Saint Kitts and Nevis')
,('LC','','Saint Lucia','Saint Lucia')
,('VC','','Saint Vincent i Grenadyny','Saint Vincent and the Grenadines')
,('BL','','Saint-Barthélemy','Saint-Barthélemy')
,('MF','','Saint-Martin','Saint Martin (French part)')
,('PM','','Saint-Pierre i Miquelon','Saint Pierre and Miquelon')
,('SV','','Salwador','El Salvador')
,('AS','','Samoa Amerykańskie','American Samoa')
,('WS','','Samoa','Samoa')
,('SM','378','San Marino','San Marino')
,('SN','','Senegal','Senegal')
,('RS','381','Serbia','Serbia')
,('SC','','Seszele','Seychelles')
,('SL','','Sierra Leone','Sierra Leone')
,('SG','','Singapur','Singapore')
,('SX','','Sint Maarten','Sint Maarten (Dutch part)')
,('SK','421','Słowacja','Slovakia')
,('SI','386','Słowenia','Slovenia')
,('SO','','Somalia','Somalia')
,('LK','','Sri Lanka','Sri Lanka')
,('US','','Stany Zjednoczone','United States')
,('SZ','','Suazi','Swaziland')
,('SD','','Sudan','Sudan')
,('SS','','Sudan Południowy','South Sudan')
,('SR','','Surinam','Suriname')
,('SJ','','Svalbard i Jan Mayen','Svalbard and Jan Mayen')
,('SY','','Syria','Syrian Arab Republic')
,('CH','41','Szwajcaria','Switzerland')
,('SE','46','Szwecja','Sweden')
,('TJ','','Tadżykistan','Tajikistan')
,('TH','','Tajlandia','Thailand')
,('TW','','Tajwan','Taiwan, Province of China')
,('TZ','','Tanzania','Tanzania, United Republic of')
,('TL','','Timor Wschodni','Timor-Leste')
,('TG','','Togo','Togo')
,('TK','','Tokelau','Tokelau')
,('TO','','Tonga','Tonga')
,('TT','','Trynidad i Tobago','Trinidad and Tobago')
,('TN','','Tunezja','Tunisia')
,('TR','','Turcja','Turkey')
,('TM','','Turkmenistan','Turkmenistan')
,('TC','','Turks i Caicos','Turks and Caicos Islands')
,('TV','','Tuvalu','Tuvalu')
,('UG','','Uganda','Uganda')
,('UA','380','Ukraina','Ukraine')
,('UY','','Urugwaj','Uruguay')
,('UZ','','Uzbekistan','Uzbekistan')
,('VU','','Vanuatu','Vanuatu')
,('WF','','Wallis i Futuna','Wallis and Futuna')
,('VA','379','Watykan','Holy See (Vatican City State)')
,('VE','','Wenezuela','Venezuela, Bolivarian Republic of')
,('HU','36','Węgry','Hungary')
,('GB','44','Wielka Brytania','United Kingdom')
,('VN','','Wietnam','Viet Nam')
,('IT','39','Włochy','Italy')
,('CI','','Wybrzeże Kości Słoniowej','Côte d\'Ivoire')
,('BV','','Wyspa Bouveta','Bouvet Island')
,('CX','','Wyspa Bożego Narodzenia','Christmas Island')
,('IM','','Wyspa Man','Isle of Man')
,('SH','','Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha','Saint Helena, Ascension and Tristan Cunha')
,('AX','','Wyspy Alandzkie','Åland Islands')
,('CK','','Wyspy Cooka','Cook Islands')
,('VI','','Wyspy Dziewicze Stanów Zjednoczonych','Virgin Islands, U . S . ')
,('HM','','Wyspy Heard i McDonalda','Heard Island and McDonald Islands')
,('CC','','Wyspy Kokosowe','Cocos(Keeling) Islands')
,('MH','','Wyspy Marshalla','Marshall Islands')
,('FO','','Wyspy Owcze','Faroe Islands')
,('SB','','Wyspy Salomona','Solomon Islands')
,('ST','','Wyspy Świętego Tomasza i Książęca','Sao Tome and Principe')
,('ZM','','Zambia','Zambia')
,('ZW','','Zimbabwe','Zimbabwe')
,('AE','','Zjednoczone Emiraty Arabskie','United Arab Emirates');");
    }

    public function down()
    {
        $this->query('drop table if exists dp_countries;');
    }
}
