# Generated by Django 5.2.9 on 2025-12-28 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("SHIFT_END", "Shift End Report"),
                            ("DAILY_SUMMARY", "Daily Summary"),
                            ("ON_DEMAND", "On Demand"),
                        ],
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(help_text="The date this report covers")),
                ("shift_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Structured data of the report"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Optional PDF/CSV file",
                        null=True,
                        upload_to="reports/",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
