FROM node:8-alpine

WORKDIR /app

RUN echo "${companyId}"

RUN apk --update add git gettext && rm -rf /var/cache/apk/*

COPY ./.docker_entrypoint /usr/bin/entrypoint.sh
COPY ./.docker_nginx.conf /etc/nginx/nginx.conf.tmp
RUN chmod a+x /usr/bin/entrypoint.sh

ENV NGX_WORKERS 1
ENV NGX_SRVNAME _
ENV NGX_CONN 1024

COPY ./ /app
RUN rm ./.docker*
RUN npm install -g grunt grunt-cli bower
RUN npm install grunt-parallel

RUN npm install


RUN chmod a+x /usr/bin/entrypoint.sh

EXPOSE 80
EXPOSE 9000

ENTRYPOINT ["/usr/bin/entrypoint.sh"]

CMD ["grunt","serve-dev"]