# Generated by Django 5.2.9 on 2025-12-27 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0002_machine_legacy_connection"),
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryHourlyRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, help_text="Start of the hour"),
                ),
                ("kind", models.CharField(db_index=True, max_length=32)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("avg_value", models.FloatField(blank=True, null=True)),
                ("sum_value", models.FloatField(blank=True, null=True)),
                ("count_points", models.IntegerField(default=0)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_rollups",
                        to="registry.machine",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["machine", "timestamp", "kind"],
                        name="telemetry_t_machine_aed8ad_idx",
                    )
                ],
                "unique_together": {("machine", "timestamp", "kind")},
            },
        ),
    ]
