# Generated by Django 5.2.10 on 2026-01-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0002_telemetryhourlyrollup"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Ink Consumption')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Internal ID (e.g., 'ink_usage')", unique=True
                    ),
                ),
                (
                    "json_key",
                    models.CharField(
                        help_text="Path in JSON payload (e.g., 'metrics.ink' or 'speed')",
                        max_length=200,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit symbol (e.g., 'kg', 'm2', '°C')",
                        max_length=20,
                    ),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("avg", "Average"),
                            ("sum", "Sum"),
                            ("max", "Max"),
                            ("min", "Min"),
                        ],
                        default="avg",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="telemetrypoint",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveIndex(
            model_name="telemetrypoint",
            name="telemetry_t_timesta_2045fb_idx",
        ),
        migrations.RemoveField(
            model_name="telemetrypoint",
            name="kind",
        ),
        migrations.AlterField(
            model_name="telemetrypoint",
            name="payload",
            field=models.JSONField(),
        ),
    ]
