# Generated by Django 5.2.9 on 2026-01-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_shift'),
        ('telemetry', '0004_telemetryhourlyrollup_metrics_summary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telemetrypoint',
            name='telemetry_t_machine_8c91a9_idx',
        ),
        migrations.AddField(
            model_name='telemetrypoint',
            name='kind',
            field=models.CharField(db_index=True, default='raw', max_length=32),
        ),
        migrations.AddIndex(
            model_name='telemetrypoint',
            index=models.Index(fields=['machine', 'timestamp', 'kind'], name='telemetry_t_machine_af21c0_idx'),
        ),
    ]
