# Generated by Django 4.2.27 on 2025-12-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("legacy_integration", "0001_initial"),
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="legacy_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machines",
                to="legacy_integration.connectionprofile",
            ),
        ),
    ]
