from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

# --- Core Memory Models ---


class MemoryLayer(str, Enum):
    """
    Enum for memory layers, representing different levels of processing and retention.
    - stm: Short-term memory, volatile and immediate.
    - ltm: Long-term memory, consolidated and durable.
    - rm: Reflective memory, synthesized from other memories.
    """

    stm = "stm"
    ltm = "ltm"
    rm = "rm"


class MemoryRecord(BaseModel):
    """
    The standard, unified format for a memory record.
    """

    id: str
    content: str
    source: Optional[str] = None
    importance: float = 0.5
    layer: MemoryLayer = MemoryLayer.ltm
    tags: Optional[List[str]] = None
    timestamp: datetime = Field(default_factory=datetime.now)
    last_accessed_at: Optional[datetime] = None
    usage_count: int = 0


class ScoredMemoryRecord(MemoryRecord):
    """
    A memory record augmented with a relevance score, typically from a query.
    """

    score: float


# --- API Request/Response Models ---


class StoreMemoryRequest(BaseModel):
    """
    Request model for storing a new memory.
    The 'id' and other metadata are generated by the service.
    """

    content: str
    source: Optional[str] = None
    importance: Optional[float] = None
    layer: Optional[str] = None  # Changed from MemoryLayer to str for flexibility
    tags: Optional[List[str]] = None
    timestamp: Optional[datetime] = None
    project: Optional[str] = None  # Added for project-scoped memories


class StoreMemoryResponse(BaseModel):
    id: str
    message: str = "Memory stored successfully."


class QueryMemoryRequest(BaseModel):
    query_text: str
    k: int = 10
    filters: Optional[Dict[str, Any]] = None


class QueryMemoryResponse(BaseModel):
    results: List[ScoredMemoryRecord] = []


class DeleteMemoryRequest(BaseModel):
    memory_id: str


class DeleteMemoryResponse(BaseModel):
    message: str
