{
 "title": "TrueJet2 - Production & Microstops",
 "tags": [
  "TJ02",
  "Production"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Wydajność Maszyny (Prędkość)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "screenwatcher",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value AS \"Prędkość (m2/h)\"\nFROM screenwatcher.collector_metricreading\nWHERE\n  name = 'speed_m2h'\n  AND machine_id = '224bf64a-d590-486f-8aee-9e4b5cedc198'\n  AND $__timeFilter(timestamp)\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Timeline Statusów (RUN / STOP)",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "screenwatcher",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  value AS \"Status\"\nFROM screenwatcher.collector_metriccontext\nWHERE\n  key = 'status'\n  AND machine_id = '224bf64a-d590-486f-8aee-9e4b5cedc198'\n  AND $__timeFilter(timestamp)\nORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Mikroprzestoje (<= 30s)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "screenwatcher",
     "rawSql": "WITH RawData AS (\n    SELECT\n        timestamp,\n        value AS status,\n        LEAD(timestamp) OVER (ORDER BY timestamp) AS next_ts\n    FROM screenwatcher.collector_metriccontext\n    WHERE\n        key = 'status'\n        AND machine_id = '224bf64a-d590-486f-8aee-9e4b5cedc198'\n        AND $__timeFilter(timestamp)\n)\nSELECT\n    timestamp AS \"time\",\n    TIMESTAMPDIFF(SECOND, timestamp, next_ts) AS \"Czas Trwania (s)\"\nFROM RawData\nWHERE\n    status = 'STOPPED'\n    AND TIMESTAMPDIFF(SECOND, timestamp, next_ts) > 0\n    AND TIMESTAMPDIFF(SECOND, timestamp, next_ts) <= 30\nORDER BY timestamp ASC"
    }
   ]
  }
 ]
}