#!/usr/bin/env python
"""
Management utility for Django's command-line interface.

This script executes administrative tasks for the ScreenWatcher project. It
mirrors the default manage.py generated by Django but is kept here to ensure
the repository includes a runnable entrypoint out‑of‑the‑box. Running any
management commands (e.g. ``runserver``, ``migrate``) will use the
configuration defined in ``screenwatcher_project/settings.py``.
"""
import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'screenwatcher_project.settings')
    try:
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()