# Generated by Django 4.2.27 on 2025-12-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobsdata",
            fields=[
                (
                    "jdnr",
                    models.CharField(
                        db_column="jdnr",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jdline",
                    models.CharField(
                        blank=True, db_column="jdline", max_length=64, null=True
                    ),
                ),
                (
                    "qtyordered",
                    models.IntegerField(blank=True, db_column="qtyordered", null=True),
                ),
                (
                    "linedesc",
                    models.CharField(
                        blank=True, db_column="linedesc", max_length=255, null=True
                    ),
                ),
                (
                    "jobformat",
                    models.CharField(
                        blank=True, db_column="jobformat", max_length=64, null=True
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        blank=True, db_column="customer", max_length=255, null=True
                    ),
                ),
                (
                    "printformat",
                    models.CharField(
                        blank=True, db_column="printformat", max_length=64, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Legacy Job Data",
                "verbose_name_plural": "Legacy Jobs Data",
                "db_table": "Jobsdata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Printtemp",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("jdnr", models.CharField(db_column="jdnr", max_length=64)),
                (
                    "jdline",
                    models.CharField(
                        blank=True, db_column="jdline", max_length=64, null=True
                    ),
                ),
                (
                    "tiles",
                    models.CharField(
                        blank=True, db_column="tiles", max_length=255, null=True
                    ),
                ),
                (
                    "tilecounter",
                    models.IntegerField(blank=True, db_column="tilecounter", null=True),
                ),
                (
                    "qtyprint",
                    models.IntegerField(blank=True, db_column="qtyprint", null=True),
                ),
                (
                    "dtime",
                    models.DateTimeField(blank=True, db_column="dtime", null=True),
                ),
                (
                    "timeprinted",
                    models.CharField(
                        blank=True, db_column="timeprinted", max_length=64, null=True
                    ),
                ),
                (
                    "printer",
                    models.CharField(
                        blank=True, db_column="printer", max_length=64, null=True
                    ),
                ),
                (
                    "machine",
                    models.CharField(
                        blank=True, db_column="machine", max_length=64, null=True
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        blank=True, db_column="profile", max_length=64, null=True
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, db_column="format", max_length=64, null=True
                    ),
                ),
                (
                    "isprinted",
                    models.BooleanField(db_column="isprinted", default=False),
                ),
                (
                    "bcodeprinted",
                    models.CharField(
                        blank=True, db_column="bcodeprinted", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Legacy Print Temp",
                "verbose_name_plural": "Legacy Print Temp Entries",
                "db_table": "Printtemp",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ConnectionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField(default=3306)),
                ("database", models.CharField(max_length=100)),
                ("user", models.CharField(max_length=100)),
                ("password", models.CharField(blank=True, max_length=255)),
                (
                    "use_central_config",
                    models.BooleanField(
                        default=False,
                        help_text="If True, Edge client cannot override these settings.",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Connection Profile",
            },
        ),
    ]
