# Generated by Django 4.2.27 on 2025-12-27 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.SlugField(
                        help_text="Department code (e.g., 'DEPT-ASSEMBLY')"
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.SlugField(
                        help_text="Unique identifier for the factory (e.g., 'FACTORY-01')",
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Factories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(help_text="Line code (e.g., 'LINE-01')")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="registry.department",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("department", "code")},
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.SlugField(
                        help_text="Unique Machine ID (e.g., 'M-001')", unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cycle_time_ideal",
                    models.FloatField(
                        default=0.0, help_text="Ideal cycle time in seconds"
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="registry.line",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Interface name (e.g., 'Main PLC')", max_length=100
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("mqtt", "MQTT"),
                            ("opcua", "OPC UA"),
                            ("rest", "REST API"),
                            ("modbus", "Modbus TCP"),
                        ],
                        default="mqtt",
                        max_length=20,
                    ),
                ),
                (
                    "connection_details",
                    models.JSONField(
                        default=dict,
                        help_text="Protocol specific settings (IP, Port, Topic)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="registry.machine",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="department",
            name="factory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="registry.factory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("factory", "code")},
        ),
    ]
