# Generated by Django 5.2 on 2026-01-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_file', models.FileField(upload_to='imports/%Y/%m/%d/')),
                ('import_type', models.CharField(choices=[('sw_jsonl', 'ScreenWatcher JSONL (OCR)'), ('machine_csv', 'Machine Log CSV')], default='sw_jsonl', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(blank=True, help_text='Processing logs and errors')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_imports', to='registry.machine')),
            ],
        ),
    ]
