# Generated by Django 5.2.10 on 2026-01-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0001_initial"),
        ("registry", "0003_shift"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("key", models.CharField(db_index=True, max_length=100)),
                ("value", models.TextField()),
                ("group_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="registry.machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric Context",
                "verbose_name_plural": "Metric Contexts",
                "indexes": [
                    models.Index(
                        fields=["machine", "key", "timestamp"],
                        name="collector_m_machine_ef60c6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("value", models.FloatField()),
                ("group_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="registry.machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric Reading",
                "verbose_name_plural": "Metric Readings",
                "indexes": [
                    models.Index(
                        fields=["machine", "name", "timestamp"],
                        name="collector_m_machine_49b52c_idx",
                    )
                ],
            },
        ),
    ]
