global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  http:
    address: :80
  https:
    address: :443
  ping:
    address: :8082

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
  # file:
  #   filename: /etc/traefik/file_config.yml
  #   watch: true

# API and dashboard configuration
api:
  insecure: true
  dashboard: true

ping:
  entryPoint: ping

log:
  level: INFO

# certificatesResolvers:
#   default:
#     acme:
#       email: kacian@kacian.pl
#       storage: /acme.json
#       httpChallenge:
#         entryPoint: http
