FROM node:12.22.12-alpine AS build
RUN apk --update add git curl nginx gettext && rm -rf /var/cache/apk/*
RUN npm install -g bower grunt-cli && \
    echo '{ "allow_root": true }' > ./.bowerrc

WORKDIR /app
COPY ./ /app


COPY ./.docker_entrypoint_dev /usr/bin/entrypoint.sh
COPY ./.docker_nginx.conf /etc/nginx/nginx.conf.tmp

RUN rm ./.docker*
RUN npm install

RUN chmod a+x /usr/bin/entrypoint.sh

EXPOSE 80
EXPOSE 9001
EXPOSE 4200

ENTRYPOINT ["/usr/bin/entrypoint.sh"]

CMD ["grunt", "serve"]
