# Generated by Django 4.2.27 on 2025-12-27 08:39

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        db_index=True,
                        help_text="Metric type, e.g., 'status', 'rate', 'count_good'",
                        max_length=32,
                    ),
                ),
                ("payload", apps.core.fields.LegacyJSONField(default=dict)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_points",
                        to="registry.machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telemetry Point",
                "verbose_name_plural": "Telemetry Points",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["machine", "timestamp"],
                        name="telemetry_t_machine_8c91a9_idx",
                    ),
                    models.Index(
                        fields=["timestamp", "kind"],
                        name="telemetry_t_timesta_2045fb_idx",
                    ),
                ],
            },
        ),
    ]
