# Generated by Django 5.2.10 on 2026-01-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0003_metricdefinition_alter_telemetrypoint_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telemetryhourlyrollup",
            name="metrics_summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Aggregated metrics e.g. {'ink_drops': 500, 'area_m2': 12}",
            ),
        ),
    ]
