# Generated by Django 5.2.9 on 2025-12-30 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_alter_widget_widget_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_code",
                    models.CharField(
                        help_text="Unique code, e.g., 'production_trend'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "default_config",
                    models.JSONField(
                        default=dict, help_text="Default configuration (JSON)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
