# Generated by Django 5.2.10 on 2026-01-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0003_widgetdefinition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("oee_gauge", "OEE Gauge"),
                    ("production_trend", "Production Trend"),
                    ("oee_trend", "OEE Trend Line"),
                    ("oee_bar", "OEE Components Bar"),
                    ("downtime_pareto", "Downtime Pareto"),
                    ("status_card", "Machine Status Card"),
                    ("machine_gantt", "Machine Status Gantt"),
                    ("reliability_card", "Reliability (MTBF/MTTR)"),
                    ("oee_heatmap", "OEE Heatmap (Lines vs Time)"),
                    ("alerts_list", "Recent Alerts List"),
                ],
                max_length=50,
            ),
        ),
    ]
